// Code generated by Kitex v0.15.2. DO NOT EDIT.

package messageservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	message "shortvideo/kitex_gen/message"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	SendMessage(ctx context.Context, req *message.SendMessageReq, callOptions ...callopt.Option) (r *message.SendMessageResp, err error)
	GetChatHistory(ctx context.Context, req *message.GetChatHistoryReq, callOptions ...callopt.Option) (r *message.GetChatHistoryResp, err error)
	GetLatestMessages(ctx context.Context, req *message.GetLatestMessagesReq, callOptions ...callopt.Option) (r *message.GetLatestMessagesResp, err error)
	MarkMessageRead(ctx context.Context, req *message.MarkMessageReadReq, callOptions ...callopt.Option) (r *message.MarkMessageReadResp, err error)
	DeleteMessage(ctx context.Context, req *message.DeleteMessageReq, callOptions ...callopt.Option) (r *message.DeleteMessageResp, err error)
	GetUnreadCount(ctx context.Context, req *message.GetUnreadCountReq, callOptions ...callopt.Option) (r *message.GetUnreadCountResp, err error)
	GetNotifications(ctx context.Context, req *message.GetNotificationsReq, callOptions ...callopt.Option) (r *message.GetNotificationsResp, err error)
	MarkNotificationRead(ctx context.Context, req *message.MarkNotificationReadReq, callOptions ...callopt.Option) (r *message.MarkNotificationReadResp, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfoForClient(), options...)
	if err != nil {
		return nil, err
	}
	return &kMessageServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kMessageServiceClient struct {
	*kClient
}

func (p *kMessageServiceClient) SendMessage(ctx context.Context, req *message.SendMessageReq, callOptions ...callopt.Option) (r *message.SendMessageResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.SendMessage(ctx, req)
}

func (p *kMessageServiceClient) GetChatHistory(ctx context.Context, req *message.GetChatHistoryReq, callOptions ...callopt.Option) (r *message.GetChatHistoryResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetChatHistory(ctx, req)
}

func (p *kMessageServiceClient) GetLatestMessages(ctx context.Context, req *message.GetLatestMessagesReq, callOptions ...callopt.Option) (r *message.GetLatestMessagesResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetLatestMessages(ctx, req)
}

func (p *kMessageServiceClient) MarkMessageRead(ctx context.Context, req *message.MarkMessageReadReq, callOptions ...callopt.Option) (r *message.MarkMessageReadResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.MarkMessageRead(ctx, req)
}

func (p *kMessageServiceClient) DeleteMessage(ctx context.Context, req *message.DeleteMessageReq, callOptions ...callopt.Option) (r *message.DeleteMessageResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.DeleteMessage(ctx, req)
}

func (p *kMessageServiceClient) GetUnreadCount(ctx context.Context, req *message.GetUnreadCountReq, callOptions ...callopt.Option) (r *message.GetUnreadCountResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetUnreadCount(ctx, req)
}

func (p *kMessageServiceClient) GetNotifications(ctx context.Context, req *message.GetNotificationsReq, callOptions ...callopt.Option) (r *message.GetNotificationsResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetNotifications(ctx, req)
}

func (p *kMessageServiceClient) MarkNotificationRead(ctx context.Context, req *message.MarkNotificationReadReq, callOptions ...callopt.Option) (r *message.MarkNotificationReadResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.MarkNotificationRead(ctx, req)
}
