// Code generated by thriftgo (0.4.3). DO NOT EDIT.

package danmu

import (
	"context"
	"fmt"
	"shortvideo/kitex_gen/common"
)

type SendDanmuReq struct {
	UserId   int64   `thrift:"userId,1" frugal:"1,default,i64" json:"userId"`
	LiveId   int64   `thrift:"liveId,2" frugal:"2,default,i64" json:"liveId"`
	Content  string  `thrift:"content,3" frugal:"3,default,string" json:"content"`
	Color    *string `thrift:"color,4,optional" frugal:"4,optional,string" json:"color,omitempty"`
	FontSize *int32  `thrift:"fontSize,5,optional" frugal:"5,optional,i32" json:"fontSize,omitempty"`
	Position *int32  `thrift:"position,6,optional" frugal:"6,optional,i32" json:"position,omitempty"`
}

func NewSendDanmuReq() *SendDanmuReq {
	return &SendDanmuReq{}
}

func (p *SendDanmuReq) InitDefault() {
}

func (p *SendDanmuReq) GetUserId() (v int64) {
	return p.UserId
}

func (p *SendDanmuReq) GetLiveId() (v int64) {
	return p.LiveId
}

func (p *SendDanmuReq) GetContent() (v string) {
	return p.Content
}

var SendDanmuReq_Color_DEFAULT string

func (p *SendDanmuReq) GetColor() (v string) {
	if !p.IsSetColor() {
		return SendDanmuReq_Color_DEFAULT
	}
	return *p.Color
}

var SendDanmuReq_FontSize_DEFAULT int32

func (p *SendDanmuReq) GetFontSize() (v int32) {
	if !p.IsSetFontSize() {
		return SendDanmuReq_FontSize_DEFAULT
	}
	return *p.FontSize
}

var SendDanmuReq_Position_DEFAULT int32

func (p *SendDanmuReq) GetPosition() (v int32) {
	if !p.IsSetPosition() {
		return SendDanmuReq_Position_DEFAULT
	}
	return *p.Position
}
func (p *SendDanmuReq) SetUserId(val int64) {
	p.UserId = val
}
func (p *SendDanmuReq) SetLiveId(val int64) {
	p.LiveId = val
}
func (p *SendDanmuReq) SetContent(val string) {
	p.Content = val
}
func (p *SendDanmuReq) SetColor(val *string) {
	p.Color = val
}
func (p *SendDanmuReq) SetFontSize(val *int32) {
	p.FontSize = val
}
func (p *SendDanmuReq) SetPosition(val *int32) {
	p.Position = val
}

func (p *SendDanmuReq) IsSetColor() bool {
	return p.Color != nil
}

func (p *SendDanmuReq) IsSetFontSize() bool {
	return p.FontSize != nil
}

func (p *SendDanmuReq) IsSetPosition() bool {
	return p.Position != nil
}

func (p *SendDanmuReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SendDanmuReq(%+v)", *p)
}

var fieldIDToName_SendDanmuReq = map[int16]string{
	1: "userId",
	2: "liveId",
	3: "content",
	4: "color",
	5: "fontSize",
	6: "position",
}

type SendDanmuResp struct {
	BaseResp *common.BaseResp `thrift:"BaseResp,1" frugal:"1,default,common.BaseResp" json:"BaseResp"`
	DanmuId  int64            `thrift:"danmuId,2" frugal:"2,default,i64" json:"danmuId"`
}

func NewSendDanmuResp() *SendDanmuResp {
	return &SendDanmuResp{}
}

func (p *SendDanmuResp) InitDefault() {
}

var SendDanmuResp_BaseResp_DEFAULT *common.BaseResp

func (p *SendDanmuResp) GetBaseResp() (v *common.BaseResp) {
	if !p.IsSetBaseResp() {
		return SendDanmuResp_BaseResp_DEFAULT
	}
	return p.BaseResp
}

func (p *SendDanmuResp) GetDanmuId() (v int64) {
	return p.DanmuId
}
func (p *SendDanmuResp) SetBaseResp(val *common.BaseResp) {
	p.BaseResp = val
}
func (p *SendDanmuResp) SetDanmuId(val int64) {
	p.DanmuId = val
}

func (p *SendDanmuResp) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *SendDanmuResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SendDanmuResp(%+v)", *p)
}

var fieldIDToName_SendDanmuResp = map[int16]string{
	1: "BaseResp",
	2: "danmuId",
}

type GetDanmuHistoryReq struct {
	LiveId    int64 `thrift:"liveId,1" frugal:"1,default,i64" json:"liveId"`
	StartTime int64 `thrift:"startTime,2" frugal:"2,default,i64" json:"startTime"`
	EndTime   int64 `thrift:"endTime,3" frugal:"3,default,i64" json:"endTime"`
	Limit     int32 `thrift:"limit,4" frugal:"4,default,i32" json:"limit"`
}

func NewGetDanmuHistoryReq() *GetDanmuHistoryReq {
	return &GetDanmuHistoryReq{}
}

func (p *GetDanmuHistoryReq) InitDefault() {
}

func (p *GetDanmuHistoryReq) GetLiveId() (v int64) {
	return p.LiveId
}

func (p *GetDanmuHistoryReq) GetStartTime() (v int64) {
	return p.StartTime
}

func (p *GetDanmuHistoryReq) GetEndTime() (v int64) {
	return p.EndTime
}

func (p *GetDanmuHistoryReq) GetLimit() (v int32) {
	return p.Limit
}
func (p *GetDanmuHistoryReq) SetLiveId(val int64) {
	p.LiveId = val
}
func (p *GetDanmuHistoryReq) SetStartTime(val int64) {
	p.StartTime = val
}
func (p *GetDanmuHistoryReq) SetEndTime(val int64) {
	p.EndTime = val
}
func (p *GetDanmuHistoryReq) SetLimit(val int32) {
	p.Limit = val
}

func (p *GetDanmuHistoryReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetDanmuHistoryReq(%+v)", *p)
}

var fieldIDToName_GetDanmuHistoryReq = map[int16]string{
	1: "liveId",
	2: "startTime",
	3: "endTime",
	4: "limit",
}

type GetDanmuHistoryResp struct {
	BaseResp *common.BaseResp `thrift:"BaseResp,1" frugal:"1,default,common.BaseResp" json:"BaseResp"`
	Danmus   []*common.Danmu  `thrift:"danmus,2" frugal:"2,default,list<common.Danmu>" json:"danmus"`
}

func NewGetDanmuHistoryResp() *GetDanmuHistoryResp {
	return &GetDanmuHistoryResp{}
}

func (p *GetDanmuHistoryResp) InitDefault() {
}

var GetDanmuHistoryResp_BaseResp_DEFAULT *common.BaseResp

func (p *GetDanmuHistoryResp) GetBaseResp() (v *common.BaseResp) {
	if !p.IsSetBaseResp() {
		return GetDanmuHistoryResp_BaseResp_DEFAULT
	}
	return p.BaseResp
}

func (p *GetDanmuHistoryResp) GetDanmus() (v []*common.Danmu) {
	return p.Danmus
}
func (p *GetDanmuHistoryResp) SetBaseResp(val *common.BaseResp) {
	p.BaseResp = val
}
func (p *GetDanmuHistoryResp) SetDanmus(val []*common.Danmu) {
	p.Danmus = val
}

func (p *GetDanmuHistoryResp) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *GetDanmuHistoryResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetDanmuHistoryResp(%+v)", *p)
}

var fieldIDToName_GetDanmuHistoryResp = map[int16]string{
	1: "BaseResp",
	2: "danmus",
}

type DanmuFilter struct {
	UserId        int64    `thrift:"userId,1" frugal:"1,default,i64" json:"userId"`
	LiveId        int64    `thrift:"liveId,2" frugal:"2,default,i64" json:"liveId"`
	Keywords      []string `thrift:"keywords,3" frugal:"3,default,list<string>" json:"keywords"`
	HideAnonymous bool     `thrift:"hideAnonymous,4" frugal:"4,default,bool" json:"hideAnonymous"`
	HideLowLevel  bool     `thrift:"hideLowLevel,5" frugal:"5,default,bool" json:"hideLowLevel"`
}

func NewDanmuFilter() *DanmuFilter {
	return &DanmuFilter{}
}

func (p *DanmuFilter) InitDefault() {
}

func (p *DanmuFilter) GetUserId() (v int64) {
	return p.UserId
}

func (p *DanmuFilter) GetLiveId() (v int64) {
	return p.LiveId
}

func (p *DanmuFilter) GetKeywords() (v []string) {
	return p.Keywords
}

func (p *DanmuFilter) GetHideAnonymous() (v bool) {
	return p.HideAnonymous
}

func (p *DanmuFilter) GetHideLowLevel() (v bool) {
	return p.HideLowLevel
}
func (p *DanmuFilter) SetUserId(val int64) {
	p.UserId = val
}
func (p *DanmuFilter) SetLiveId(val int64) {
	p.LiveId = val
}
func (p *DanmuFilter) SetKeywords(val []string) {
	p.Keywords = val
}
func (p *DanmuFilter) SetHideAnonymous(val bool) {
	p.HideAnonymous = val
}
func (p *DanmuFilter) SetHideLowLevel(val bool) {
	p.HideLowLevel = val
}

func (p *DanmuFilter) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DanmuFilter(%+v)", *p)
}

var fieldIDToName_DanmuFilter = map[int16]string{
	1: "userId",
	2: "liveId",
	3: "keywords",
	4: "hideAnonymous",
	5: "hideLowLevel",
}

type SetDanmuFilterReq struct {
	UserId int64        `thrift:"userId,1" frugal:"1,default,i64" json:"userId"`
	LiveId int64        `thrift:"liveId,2" frugal:"2,default,i64" json:"liveId"`
	Filter *DanmuFilter `thrift:"filter,3" frugal:"3,default,DanmuFilter" json:"filter"`
}

func NewSetDanmuFilterReq() *SetDanmuFilterReq {
	return &SetDanmuFilterReq{}
}

func (p *SetDanmuFilterReq) InitDefault() {
}

func (p *SetDanmuFilterReq) GetUserId() (v int64) {
	return p.UserId
}

func (p *SetDanmuFilterReq) GetLiveId() (v int64) {
	return p.LiveId
}

var SetDanmuFilterReq_Filter_DEFAULT *DanmuFilter

func (p *SetDanmuFilterReq) GetFilter() (v *DanmuFilter) {
	if !p.IsSetFilter() {
		return SetDanmuFilterReq_Filter_DEFAULT
	}
	return p.Filter
}
func (p *SetDanmuFilterReq) SetUserId(val int64) {
	p.UserId = val
}
func (p *SetDanmuFilterReq) SetLiveId(val int64) {
	p.LiveId = val
}
func (p *SetDanmuFilterReq) SetFilter(val *DanmuFilter) {
	p.Filter = val
}

func (p *SetDanmuFilterReq) IsSetFilter() bool {
	return p.Filter != nil
}

func (p *SetDanmuFilterReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SetDanmuFilterReq(%+v)", *p)
}

var fieldIDToName_SetDanmuFilterReq = map[int16]string{
	1: "userId",
	2: "liveId",
	3: "filter",
}

type SetDanmuFilterResp struct {
	BaseResp *common.BaseResp `thrift:"BaseResp,1" frugal:"1,default,common.BaseResp" json:"BaseResp"`
}

func NewSetDanmuFilterResp() *SetDanmuFilterResp {
	return &SetDanmuFilterResp{}
}

func (p *SetDanmuFilterResp) InitDefault() {
}

var SetDanmuFilterResp_BaseResp_DEFAULT *common.BaseResp

func (p *SetDanmuFilterResp) GetBaseResp() (v *common.BaseResp) {
	if !p.IsSetBaseResp() {
		return SetDanmuFilterResp_BaseResp_DEFAULT
	}
	return p.BaseResp
}
func (p *SetDanmuFilterResp) SetBaseResp(val *common.BaseResp) {
	p.BaseResp = val
}

func (p *SetDanmuFilterResp) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *SetDanmuFilterResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SetDanmuFilterResp(%+v)", *p)
}

var fieldIDToName_SetDanmuFilterResp = map[int16]string{
	1: "BaseResp",
}

type GetDanmuFilterReq struct {
	UserId int64 `thrift:"userId,1" frugal:"1,default,i64" json:"userId"`
	LiveId int64 `thrift:"liveId,2" frugal:"2,default,i64" json:"liveId"`
}

func NewGetDanmuFilterReq() *GetDanmuFilterReq {
	return &GetDanmuFilterReq{}
}

func (p *GetDanmuFilterReq) InitDefault() {
}

func (p *GetDanmuFilterReq) GetUserId() (v int64) {
	return p.UserId
}

func (p *GetDanmuFilterReq) GetLiveId() (v int64) {
	return p.LiveId
}
func (p *GetDanmuFilterReq) SetUserId(val int64) {
	p.UserId = val
}
func (p *GetDanmuFilterReq) SetLiveId(val int64) {
	p.LiveId = val
}

func (p *GetDanmuFilterReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetDanmuFilterReq(%+v)", *p)
}

var fieldIDToName_GetDanmuFilterReq = map[int16]string{
	1: "userId",
	2: "liveId",
}

type GetDanmuFilterResp struct {
	BaseResp *common.BaseResp `thrift:"BaseResp,1" frugal:"1,default,common.BaseResp" json:"BaseResp"`
	Filter   *DanmuFilter     `thrift:"filter,2" frugal:"2,default,DanmuFilter" json:"filter"`
}

func NewGetDanmuFilterResp() *GetDanmuFilterResp {
	return &GetDanmuFilterResp{}
}

func (p *GetDanmuFilterResp) InitDefault() {
}

var GetDanmuFilterResp_BaseResp_DEFAULT *common.BaseResp

func (p *GetDanmuFilterResp) GetBaseResp() (v *common.BaseResp) {
	if !p.IsSetBaseResp() {
		return GetDanmuFilterResp_BaseResp_DEFAULT
	}
	return p.BaseResp
}

var GetDanmuFilterResp_Filter_DEFAULT *DanmuFilter

func (p *GetDanmuFilterResp) GetFilter() (v *DanmuFilter) {
	if !p.IsSetFilter() {
		return GetDanmuFilterResp_Filter_DEFAULT
	}
	return p.Filter
}
func (p *GetDanmuFilterResp) SetBaseResp(val *common.BaseResp) {
	p.BaseResp = val
}
func (p *GetDanmuFilterResp) SetFilter(val *DanmuFilter) {
	p.Filter = val
}

func (p *GetDanmuFilterResp) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *GetDanmuFilterResp) IsSetFilter() bool {
	return p.Filter != nil
}

func (p *GetDanmuFilterResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetDanmuFilterResp(%+v)", *p)
}

var fieldIDToName_GetDanmuFilterResp = map[int16]string{
	1: "BaseResp",
	2: "filter",
}

type DanmuStats struct {
	LiveId             int64            `thrift:"liveId,1" frugal:"1,default,i64" json:"liveId"`
	TotalDanmuCount    int64            `thrift:"totalDanmuCount,2" frugal:"2,default,i64" json:"totalDanmuCount"`
	ActiveUserCount    int64            `thrift:"activeUserCount,3" frugal:"3,default,i64" json:"activeUserCount"`
	PeakDanmuPerMinute int64            `thrift:"peakDanmuPerMinute,4" frugal:"4,default,i64" json:"peakDanmuPerMinute"`
	WordCloud          map[string]int64 `thrift:"wordCloud,5" frugal:"5,default,map<string:i64>" json:"wordCloud"`
}

func NewDanmuStats() *DanmuStats {
	return &DanmuStats{}
}

func (p *DanmuStats) InitDefault() {
}

func (p *DanmuStats) GetLiveId() (v int64) {
	return p.LiveId
}

func (p *DanmuStats) GetTotalDanmuCount() (v int64) {
	return p.TotalDanmuCount
}

func (p *DanmuStats) GetActiveUserCount() (v int64) {
	return p.ActiveUserCount
}

func (p *DanmuStats) GetPeakDanmuPerMinute() (v int64) {
	return p.PeakDanmuPerMinute
}

func (p *DanmuStats) GetWordCloud() (v map[string]int64) {
	return p.WordCloud
}
func (p *DanmuStats) SetLiveId(val int64) {
	p.LiveId = val
}
func (p *DanmuStats) SetTotalDanmuCount(val int64) {
	p.TotalDanmuCount = val
}
func (p *DanmuStats) SetActiveUserCount(val int64) {
	p.ActiveUserCount = val
}
func (p *DanmuStats) SetPeakDanmuPerMinute(val int64) {
	p.PeakDanmuPerMinute = val
}
func (p *DanmuStats) SetWordCloud(val map[string]int64) {
	p.WordCloud = val
}

func (p *DanmuStats) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DanmuStats(%+v)", *p)
}

var fieldIDToName_DanmuStats = map[int16]string{
	1: "liveId",
	2: "totalDanmuCount",
	3: "activeUserCount",
	4: "peakDanmuPerMinute",
	5: "wordCloud",
}

type GetDanmuStatsReq struct {
	LiveId int64 `thrift:"liveId,1" frugal:"1,default,i64" json:"liveId"`
}

func NewGetDanmuStatsReq() *GetDanmuStatsReq {
	return &GetDanmuStatsReq{}
}

func (p *GetDanmuStatsReq) InitDefault() {
}

func (p *GetDanmuStatsReq) GetLiveId() (v int64) {
	return p.LiveId
}
func (p *GetDanmuStatsReq) SetLiveId(val int64) {
	p.LiveId = val
}

func (p *GetDanmuStatsReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetDanmuStatsReq(%+v)", *p)
}

var fieldIDToName_GetDanmuStatsReq = map[int16]string{
	1: "liveId",
}

type GetDanmuStatsResp struct {
	BaseResp *common.BaseResp `thrift:"BaseResp,1" frugal:"1,default,common.BaseResp" json:"BaseResp"`
	Stats    *DanmuStats      `thrift:"stats,2" frugal:"2,default,DanmuStats" json:"stats"`
}

func NewGetDanmuStatsResp() *GetDanmuStatsResp {
	return &GetDanmuStatsResp{}
}

func (p *GetDanmuStatsResp) InitDefault() {
}

var GetDanmuStatsResp_BaseResp_DEFAULT *common.BaseResp

func (p *GetDanmuStatsResp) GetBaseResp() (v *common.BaseResp) {
	if !p.IsSetBaseResp() {
		return GetDanmuStatsResp_BaseResp_DEFAULT
	}
	return p.BaseResp
}

var GetDanmuStatsResp_Stats_DEFAULT *DanmuStats

func (p *GetDanmuStatsResp) GetStats() (v *DanmuStats) {
	if !p.IsSetStats() {
		return GetDanmuStatsResp_Stats_DEFAULT
	}
	return p.Stats
}
func (p *GetDanmuStatsResp) SetBaseResp(val *common.BaseResp) {
	p.BaseResp = val
}
func (p *GetDanmuStatsResp) SetStats(val *DanmuStats) {
	p.Stats = val
}

func (p *GetDanmuStatsResp) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *GetDanmuStatsResp) IsSetStats() bool {
	return p.Stats != nil
}

func (p *GetDanmuStatsResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetDanmuStatsResp(%+v)", *p)
}

var fieldIDToName_GetDanmuStatsResp = map[int16]string{
	1: "BaseResp",
	2: "stats",
}

type ManageDanmuReq struct {
	ManagerId int64 `thrift:"managerId,1" frugal:"1,default,i64" json:"managerId"`
	LiveId    int64 `thrift:"liveId,2" frugal:"2,default,i64" json:"liveId"`
	DanmuId   int64 `thrift:"danmuId,3" frugal:"3,default,i64" json:"danmuId"`
	Action    int32 `thrift:"action,4" frugal:"4,default,i32" json:"action"`
}

func NewManageDanmuReq() *ManageDanmuReq {
	return &ManageDanmuReq{}
}

func (p *ManageDanmuReq) InitDefault() {
}

func (p *ManageDanmuReq) GetManagerId() (v int64) {
	return p.ManagerId
}

func (p *ManageDanmuReq) GetLiveId() (v int64) {
	return p.LiveId
}

func (p *ManageDanmuReq) GetDanmuId() (v int64) {
	return p.DanmuId
}

func (p *ManageDanmuReq) GetAction() (v int32) {
	return p.Action
}
func (p *ManageDanmuReq) SetManagerId(val int64) {
	p.ManagerId = val
}
func (p *ManageDanmuReq) SetLiveId(val int64) {
	p.LiveId = val
}
func (p *ManageDanmuReq) SetDanmuId(val int64) {
	p.DanmuId = val
}
func (p *ManageDanmuReq) SetAction(val int32) {
	p.Action = val
}

func (p *ManageDanmuReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ManageDanmuReq(%+v)", *p)
}

var fieldIDToName_ManageDanmuReq = map[int16]string{
	1: "managerId",
	2: "liveId",
	3: "danmuId",
	4: "action",
}

type ManageDanmuResp struct {
	BaseResp *common.BaseResp `thrift:"BaseResp,1" frugal:"1,default,common.BaseResp" json:"BaseResp"`
}

func NewManageDanmuResp() *ManageDanmuResp {
	return &ManageDanmuResp{}
}

func (p *ManageDanmuResp) InitDefault() {
}

var ManageDanmuResp_BaseResp_DEFAULT *common.BaseResp

func (p *ManageDanmuResp) GetBaseResp() (v *common.BaseResp) {
	if !p.IsSetBaseResp() {
		return ManageDanmuResp_BaseResp_DEFAULT
	}
	return p.BaseResp
}
func (p *ManageDanmuResp) SetBaseResp(val *common.BaseResp) {
	p.BaseResp = val
}

func (p *ManageDanmuResp) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *ManageDanmuResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ManageDanmuResp(%+v)", *p)
}

var fieldIDToName_ManageDanmuResp = map[int16]string{
	1: "BaseResp",
}

type LikeDanmuReq struct {
	UserId  int64 `thrift:"userId,1" frugal:"1,default,i64" json:"userId"`
	DanmuId int64 `thrift:"danmuId,2" frugal:"2,default,i64" json:"danmuId"`
}

func NewLikeDanmuReq() *LikeDanmuReq {
	return &LikeDanmuReq{}
}

func (p *LikeDanmuReq) InitDefault() {
}

func (p *LikeDanmuReq) GetUserId() (v int64) {
	return p.UserId
}

func (p *LikeDanmuReq) GetDanmuId() (v int64) {
	return p.DanmuId
}
func (p *LikeDanmuReq) SetUserId(val int64) {
	p.UserId = val
}
func (p *LikeDanmuReq) SetDanmuId(val int64) {
	p.DanmuId = val
}

func (p *LikeDanmuReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("LikeDanmuReq(%+v)", *p)
}

var fieldIDToName_LikeDanmuReq = map[int16]string{
	1: "userId",
	2: "danmuId",
}

type LikeDanmuResp struct {
	BaseResp  *common.BaseResp `thrift:"BaseResp,1" frugal:"1,default,common.BaseResp" json:"BaseResp"`
	LikeCount int64            `thrift:"likeCount,2" frugal:"2,default,i64" json:"likeCount"`
}

func NewLikeDanmuResp() *LikeDanmuResp {
	return &LikeDanmuResp{}
}

func (p *LikeDanmuResp) InitDefault() {
}

var LikeDanmuResp_BaseResp_DEFAULT *common.BaseResp

func (p *LikeDanmuResp) GetBaseResp() (v *common.BaseResp) {
	if !p.IsSetBaseResp() {
		return LikeDanmuResp_BaseResp_DEFAULT
	}
	return p.BaseResp
}

func (p *LikeDanmuResp) GetLikeCount() (v int64) {
	return p.LikeCount
}
func (p *LikeDanmuResp) SetBaseResp(val *common.BaseResp) {
	p.BaseResp = val
}
func (p *LikeDanmuResp) SetLikeCount(val int64) {
	p.LikeCount = val
}

func (p *LikeDanmuResp) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *LikeDanmuResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("LikeDanmuResp(%+v)", *p)
}

var fieldIDToName_LikeDanmuResp = map[int16]string{
	1: "BaseResp",
	2: "likeCount",
}

type DanmuService interface {
	SendDanmu(ctx context.Context, req *SendDanmuReq) (r *SendDanmuResp, err error)

	GetDanmuHistory(ctx context.Context, req *GetDanmuHistoryReq) (r *GetDanmuHistoryResp, err error)

	SetDanmuFilter(ctx context.Context, req *SetDanmuFilterReq) (r *SetDanmuFilterResp, err error)

	GetDanmuFilter(ctx context.Context, req *GetDanmuFilterReq) (r *GetDanmuFilterResp, err error)

	GetDanmuStats(ctx context.Context, req *GetDanmuStatsReq) (r *GetDanmuStatsResp, err error)

	ManageDanmu(ctx context.Context, req *ManageDanmuReq) (r *ManageDanmuResp, err error)

	LikeDanmu(ctx context.Context, req *LikeDanmuReq) (r *LikeDanmuResp, err error)
}

type DanmuServiceSendDanmuArgs struct {
	Req *SendDanmuReq `thrift:"req,1" frugal:"1,default,SendDanmuReq" json:"req"`
}

func NewDanmuServiceSendDanmuArgs() *DanmuServiceSendDanmuArgs {
	return &DanmuServiceSendDanmuArgs{}
}

func (p *DanmuServiceSendDanmuArgs) InitDefault() {
}

var DanmuServiceSendDanmuArgs_Req_DEFAULT *SendDanmuReq

func (p *DanmuServiceSendDanmuArgs) GetReq() (v *SendDanmuReq) {
	if !p.IsSetReq() {
		return DanmuServiceSendDanmuArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *DanmuServiceSendDanmuArgs) SetReq(val *SendDanmuReq) {
	p.Req = val
}

func (p *DanmuServiceSendDanmuArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *DanmuServiceSendDanmuArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DanmuServiceSendDanmuArgs(%+v)", *p)
}

var fieldIDToName_DanmuServiceSendDanmuArgs = map[int16]string{
	1: "req",
}

type DanmuServiceSendDanmuResult struct {
	Success *SendDanmuResp `thrift:"success,0,optional" frugal:"0,optional,SendDanmuResp" json:"success,omitempty"`
}

func NewDanmuServiceSendDanmuResult() *DanmuServiceSendDanmuResult {
	return &DanmuServiceSendDanmuResult{}
}

func (p *DanmuServiceSendDanmuResult) InitDefault() {
}

var DanmuServiceSendDanmuResult_Success_DEFAULT *SendDanmuResp

func (p *DanmuServiceSendDanmuResult) GetSuccess() (v *SendDanmuResp) {
	if !p.IsSetSuccess() {
		return DanmuServiceSendDanmuResult_Success_DEFAULT
	}
	return p.Success
}
func (p *DanmuServiceSendDanmuResult) SetSuccess(x interface{}) {
	p.Success = x.(*SendDanmuResp)
}

func (p *DanmuServiceSendDanmuResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *DanmuServiceSendDanmuResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DanmuServiceSendDanmuResult(%+v)", *p)
}

var fieldIDToName_DanmuServiceSendDanmuResult = map[int16]string{
	0: "success",
}

type DanmuServiceGetDanmuHistoryArgs struct {
	Req *GetDanmuHistoryReq `thrift:"req,1" frugal:"1,default,GetDanmuHistoryReq" json:"req"`
}

func NewDanmuServiceGetDanmuHistoryArgs() *DanmuServiceGetDanmuHistoryArgs {
	return &DanmuServiceGetDanmuHistoryArgs{}
}

func (p *DanmuServiceGetDanmuHistoryArgs) InitDefault() {
}

var DanmuServiceGetDanmuHistoryArgs_Req_DEFAULT *GetDanmuHistoryReq

func (p *DanmuServiceGetDanmuHistoryArgs) GetReq() (v *GetDanmuHistoryReq) {
	if !p.IsSetReq() {
		return DanmuServiceGetDanmuHistoryArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *DanmuServiceGetDanmuHistoryArgs) SetReq(val *GetDanmuHistoryReq) {
	p.Req = val
}

func (p *DanmuServiceGetDanmuHistoryArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *DanmuServiceGetDanmuHistoryArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DanmuServiceGetDanmuHistoryArgs(%+v)", *p)
}

var fieldIDToName_DanmuServiceGetDanmuHistoryArgs = map[int16]string{
	1: "req",
}

type DanmuServiceGetDanmuHistoryResult struct {
	Success *GetDanmuHistoryResp `thrift:"success,0,optional" frugal:"0,optional,GetDanmuHistoryResp" json:"success,omitempty"`
}

func NewDanmuServiceGetDanmuHistoryResult() *DanmuServiceGetDanmuHistoryResult {
	return &DanmuServiceGetDanmuHistoryResult{}
}

func (p *DanmuServiceGetDanmuHistoryResult) InitDefault() {
}

var DanmuServiceGetDanmuHistoryResult_Success_DEFAULT *GetDanmuHistoryResp

func (p *DanmuServiceGetDanmuHistoryResult) GetSuccess() (v *GetDanmuHistoryResp) {
	if !p.IsSetSuccess() {
		return DanmuServiceGetDanmuHistoryResult_Success_DEFAULT
	}
	return p.Success
}
func (p *DanmuServiceGetDanmuHistoryResult) SetSuccess(x interface{}) {
	p.Success = x.(*GetDanmuHistoryResp)
}

func (p *DanmuServiceGetDanmuHistoryResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *DanmuServiceGetDanmuHistoryResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DanmuServiceGetDanmuHistoryResult(%+v)", *p)
}

var fieldIDToName_DanmuServiceGetDanmuHistoryResult = map[int16]string{
	0: "success",
}

type DanmuServiceSetDanmuFilterArgs struct {
	Req *SetDanmuFilterReq `thrift:"req,1" frugal:"1,default,SetDanmuFilterReq" json:"req"`
}

func NewDanmuServiceSetDanmuFilterArgs() *DanmuServiceSetDanmuFilterArgs {
	return &DanmuServiceSetDanmuFilterArgs{}
}

func (p *DanmuServiceSetDanmuFilterArgs) InitDefault() {
}

var DanmuServiceSetDanmuFilterArgs_Req_DEFAULT *SetDanmuFilterReq

func (p *DanmuServiceSetDanmuFilterArgs) GetReq() (v *SetDanmuFilterReq) {
	if !p.IsSetReq() {
		return DanmuServiceSetDanmuFilterArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *DanmuServiceSetDanmuFilterArgs) SetReq(val *SetDanmuFilterReq) {
	p.Req = val
}

func (p *DanmuServiceSetDanmuFilterArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *DanmuServiceSetDanmuFilterArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DanmuServiceSetDanmuFilterArgs(%+v)", *p)
}

var fieldIDToName_DanmuServiceSetDanmuFilterArgs = map[int16]string{
	1: "req",
}

type DanmuServiceSetDanmuFilterResult struct {
	Success *SetDanmuFilterResp `thrift:"success,0,optional" frugal:"0,optional,SetDanmuFilterResp" json:"success,omitempty"`
}

func NewDanmuServiceSetDanmuFilterResult() *DanmuServiceSetDanmuFilterResult {
	return &DanmuServiceSetDanmuFilterResult{}
}

func (p *DanmuServiceSetDanmuFilterResult) InitDefault() {
}

var DanmuServiceSetDanmuFilterResult_Success_DEFAULT *SetDanmuFilterResp

func (p *DanmuServiceSetDanmuFilterResult) GetSuccess() (v *SetDanmuFilterResp) {
	if !p.IsSetSuccess() {
		return DanmuServiceSetDanmuFilterResult_Success_DEFAULT
	}
	return p.Success
}
func (p *DanmuServiceSetDanmuFilterResult) SetSuccess(x interface{}) {
	p.Success = x.(*SetDanmuFilterResp)
}

func (p *DanmuServiceSetDanmuFilterResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *DanmuServiceSetDanmuFilterResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DanmuServiceSetDanmuFilterResult(%+v)", *p)
}

var fieldIDToName_DanmuServiceSetDanmuFilterResult = map[int16]string{
	0: "success",
}

type DanmuServiceGetDanmuFilterArgs struct {
	Req *GetDanmuFilterReq `thrift:"req,1" frugal:"1,default,GetDanmuFilterReq" json:"req"`
}

func NewDanmuServiceGetDanmuFilterArgs() *DanmuServiceGetDanmuFilterArgs {
	return &DanmuServiceGetDanmuFilterArgs{}
}

func (p *DanmuServiceGetDanmuFilterArgs) InitDefault() {
}

var DanmuServiceGetDanmuFilterArgs_Req_DEFAULT *GetDanmuFilterReq

func (p *DanmuServiceGetDanmuFilterArgs) GetReq() (v *GetDanmuFilterReq) {
	if !p.IsSetReq() {
		return DanmuServiceGetDanmuFilterArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *DanmuServiceGetDanmuFilterArgs) SetReq(val *GetDanmuFilterReq) {
	p.Req = val
}

func (p *DanmuServiceGetDanmuFilterArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *DanmuServiceGetDanmuFilterArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DanmuServiceGetDanmuFilterArgs(%+v)", *p)
}

var fieldIDToName_DanmuServiceGetDanmuFilterArgs = map[int16]string{
	1: "req",
}

type DanmuServiceGetDanmuFilterResult struct {
	Success *GetDanmuFilterResp `thrift:"success,0,optional" frugal:"0,optional,GetDanmuFilterResp" json:"success,omitempty"`
}

func NewDanmuServiceGetDanmuFilterResult() *DanmuServiceGetDanmuFilterResult {
	return &DanmuServiceGetDanmuFilterResult{}
}

func (p *DanmuServiceGetDanmuFilterResult) InitDefault() {
}

var DanmuServiceGetDanmuFilterResult_Success_DEFAULT *GetDanmuFilterResp

func (p *DanmuServiceGetDanmuFilterResult) GetSuccess() (v *GetDanmuFilterResp) {
	if !p.IsSetSuccess() {
		return DanmuServiceGetDanmuFilterResult_Success_DEFAULT
	}
	return p.Success
}
func (p *DanmuServiceGetDanmuFilterResult) SetSuccess(x interface{}) {
	p.Success = x.(*GetDanmuFilterResp)
}

func (p *DanmuServiceGetDanmuFilterResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *DanmuServiceGetDanmuFilterResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DanmuServiceGetDanmuFilterResult(%+v)", *p)
}

var fieldIDToName_DanmuServiceGetDanmuFilterResult = map[int16]string{
	0: "success",
}

type DanmuServiceGetDanmuStatsArgs struct {
	Req *GetDanmuStatsReq `thrift:"req,1" frugal:"1,default,GetDanmuStatsReq" json:"req"`
}

func NewDanmuServiceGetDanmuStatsArgs() *DanmuServiceGetDanmuStatsArgs {
	return &DanmuServiceGetDanmuStatsArgs{}
}

func (p *DanmuServiceGetDanmuStatsArgs) InitDefault() {
}

var DanmuServiceGetDanmuStatsArgs_Req_DEFAULT *GetDanmuStatsReq

func (p *DanmuServiceGetDanmuStatsArgs) GetReq() (v *GetDanmuStatsReq) {
	if !p.IsSetReq() {
		return DanmuServiceGetDanmuStatsArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *DanmuServiceGetDanmuStatsArgs) SetReq(val *GetDanmuStatsReq) {
	p.Req = val
}

func (p *DanmuServiceGetDanmuStatsArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *DanmuServiceGetDanmuStatsArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DanmuServiceGetDanmuStatsArgs(%+v)", *p)
}

var fieldIDToName_DanmuServiceGetDanmuStatsArgs = map[int16]string{
	1: "req",
}

type DanmuServiceGetDanmuStatsResult struct {
	Success *GetDanmuStatsResp `thrift:"success,0,optional" frugal:"0,optional,GetDanmuStatsResp" json:"success,omitempty"`
}

func NewDanmuServiceGetDanmuStatsResult() *DanmuServiceGetDanmuStatsResult {
	return &DanmuServiceGetDanmuStatsResult{}
}

func (p *DanmuServiceGetDanmuStatsResult) InitDefault() {
}

var DanmuServiceGetDanmuStatsResult_Success_DEFAULT *GetDanmuStatsResp

func (p *DanmuServiceGetDanmuStatsResult) GetSuccess() (v *GetDanmuStatsResp) {
	if !p.IsSetSuccess() {
		return DanmuServiceGetDanmuStatsResult_Success_DEFAULT
	}
	return p.Success
}
func (p *DanmuServiceGetDanmuStatsResult) SetSuccess(x interface{}) {
	p.Success = x.(*GetDanmuStatsResp)
}

func (p *DanmuServiceGetDanmuStatsResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *DanmuServiceGetDanmuStatsResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DanmuServiceGetDanmuStatsResult(%+v)", *p)
}

var fieldIDToName_DanmuServiceGetDanmuStatsResult = map[int16]string{
	0: "success",
}

type DanmuServiceManageDanmuArgs struct {
	Req *ManageDanmuReq `thrift:"req,1" frugal:"1,default,ManageDanmuReq" json:"req"`
}

func NewDanmuServiceManageDanmuArgs() *DanmuServiceManageDanmuArgs {
	return &DanmuServiceManageDanmuArgs{}
}

func (p *DanmuServiceManageDanmuArgs) InitDefault() {
}

var DanmuServiceManageDanmuArgs_Req_DEFAULT *ManageDanmuReq

func (p *DanmuServiceManageDanmuArgs) GetReq() (v *ManageDanmuReq) {
	if !p.IsSetReq() {
		return DanmuServiceManageDanmuArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *DanmuServiceManageDanmuArgs) SetReq(val *ManageDanmuReq) {
	p.Req = val
}

func (p *DanmuServiceManageDanmuArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *DanmuServiceManageDanmuArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DanmuServiceManageDanmuArgs(%+v)", *p)
}

var fieldIDToName_DanmuServiceManageDanmuArgs = map[int16]string{
	1: "req",
}

type DanmuServiceManageDanmuResult struct {
	Success *ManageDanmuResp `thrift:"success,0,optional" frugal:"0,optional,ManageDanmuResp" json:"success,omitempty"`
}

func NewDanmuServiceManageDanmuResult() *DanmuServiceManageDanmuResult {
	return &DanmuServiceManageDanmuResult{}
}

func (p *DanmuServiceManageDanmuResult) InitDefault() {
}

var DanmuServiceManageDanmuResult_Success_DEFAULT *ManageDanmuResp

func (p *DanmuServiceManageDanmuResult) GetSuccess() (v *ManageDanmuResp) {
	if !p.IsSetSuccess() {
		return DanmuServiceManageDanmuResult_Success_DEFAULT
	}
	return p.Success
}
func (p *DanmuServiceManageDanmuResult) SetSuccess(x interface{}) {
	p.Success = x.(*ManageDanmuResp)
}

func (p *DanmuServiceManageDanmuResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *DanmuServiceManageDanmuResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DanmuServiceManageDanmuResult(%+v)", *p)
}

var fieldIDToName_DanmuServiceManageDanmuResult = map[int16]string{
	0: "success",
}

type DanmuServiceLikeDanmuArgs struct {
	Req *LikeDanmuReq `thrift:"req,1" frugal:"1,default,LikeDanmuReq" json:"req"`
}

func NewDanmuServiceLikeDanmuArgs() *DanmuServiceLikeDanmuArgs {
	return &DanmuServiceLikeDanmuArgs{}
}

func (p *DanmuServiceLikeDanmuArgs) InitDefault() {
}

var DanmuServiceLikeDanmuArgs_Req_DEFAULT *LikeDanmuReq

func (p *DanmuServiceLikeDanmuArgs) GetReq() (v *LikeDanmuReq) {
	if !p.IsSetReq() {
		return DanmuServiceLikeDanmuArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *DanmuServiceLikeDanmuArgs) SetReq(val *LikeDanmuReq) {
	p.Req = val
}

func (p *DanmuServiceLikeDanmuArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *DanmuServiceLikeDanmuArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DanmuServiceLikeDanmuArgs(%+v)", *p)
}

var fieldIDToName_DanmuServiceLikeDanmuArgs = map[int16]string{
	1: "req",
}

type DanmuServiceLikeDanmuResult struct {
	Success *LikeDanmuResp `thrift:"success,0,optional" frugal:"0,optional,LikeDanmuResp" json:"success,omitempty"`
}

func NewDanmuServiceLikeDanmuResult() *DanmuServiceLikeDanmuResult {
	return &DanmuServiceLikeDanmuResult{}
}

func (p *DanmuServiceLikeDanmuResult) InitDefault() {
}

var DanmuServiceLikeDanmuResult_Success_DEFAULT *LikeDanmuResp

func (p *DanmuServiceLikeDanmuResult) GetSuccess() (v *LikeDanmuResp) {
	if !p.IsSetSuccess() {
		return DanmuServiceLikeDanmuResult_Success_DEFAULT
	}
	return p.Success
}
func (p *DanmuServiceLikeDanmuResult) SetSuccess(x interface{}) {
	p.Success = x.(*LikeDanmuResp)
}

func (p *DanmuServiceLikeDanmuResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *DanmuServiceLikeDanmuResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DanmuServiceLikeDanmuResult(%+v)", *p)
}

var fieldIDToName_DanmuServiceLikeDanmuResult = map[int16]string{
	0: "success",
}
