// Code generated by Kitex v0.15.2. DO NOT EDIT.

package userservice

import (
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	common "shortvideo/kitex_gen/common"
	user "shortvideo/kitex_gen/user"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"Register": kitex.NewMethodInfo(
		registerHandler,
		newUserServiceRegisterArgs,
		newUserServiceRegisterResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"Login": kitex.NewMethodInfo(
		loginHandler,
		newUserServiceLoginArgs,
		newUserServiceLoginResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetUserInfo": kitex.NewMethodInfo(
		getUserInfoHandler,
		newUserServiceGetUserInfoArgs,
		newUserServiceGetUserInfoResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetUserInfoByUsername": kitex.NewMethodInfo(
		getUserInfoByUsernameHandler,
		newUserServiceGetUserInfoByUsernameArgs,
		newUserServiceGetUserInfoByUsernameResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"BatchGetUserInfo": kitex.NewMethodInfo(
		batchGetUserInfoHandler,
		newUserServiceBatchGetUserInfoArgs,
		newUserServiceBatchGetUserInfoResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"UpdateUser": kitex.NewMethodInfo(
		updateUserHandler,
		newUserServiceUpdateUserArgs,
		newUserServiceUpdateUserResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"UpdateAvatar": kitex.NewMethodInfo(
		updateAvatarHandler,
		newUserServiceUpdateAvatarArgs,
		newUserServiceUpdateAvatarResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"CheckUsername": kitex.NewMethodInfo(
		checkUsernameHandler,
		newUserServiceCheckUsernameArgs,
		newUserServiceCheckUsernameResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"BatchCheckUsernames": kitex.NewMethodInfo(
		batchCheckUsernamesHandler,
		newUserServiceBatchCheckUsernamesArgs,
		newUserServiceBatchCheckUsernamesResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetUserStats": kitex.NewMethodInfo(
		getUserStatsHandler,
		newUserServiceGetUserStatsArgs,
		newUserServiceGetUserStatsResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"SearchUsers": kitex.NewMethodInfo(
		searchUsersHandler,
		newUserServiceSearchUsersArgs,
		newUserServiceSearchUsersResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"UpdateFollowCount": kitex.NewMethodInfo(
		updateFollowCountHandler,
		newUserServiceUpdateFollowCountArgs,
		newUserServiceUpdateFollowCountResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"UpdateFollowerCount": kitex.NewMethodInfo(
		updateFollowerCountHandler,
		newUserServiceUpdateFollowerCountArgs,
		newUserServiceUpdateFollowerCountResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"VerifyToken": kitex.NewMethodInfo(
		verifyTokenHandler,
		newUserServiceVerifyTokenArgs,
		newUserServiceVerifyTokenResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	userServiceServiceInfo                = NewServiceInfo()
	userServiceServiceInfoForClient       = NewServiceInfoForClient()
	userServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return userServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return userServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return userServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "UserService"
	handlerType := (*user.UserService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "user",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.15.2",
		Extra:           extra,
	}
	return svcInfo
}

func registerHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*user.UserServiceRegisterArgs)
	realResult := result.(*user.UserServiceRegisterResult)
	success, err := handler.(user.UserService).Register(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUserServiceRegisterArgs() interface{} {
	return user.NewUserServiceRegisterArgs()
}

func newUserServiceRegisterResult() interface{} {
	return user.NewUserServiceRegisterResult()
}

func loginHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*user.UserServiceLoginArgs)
	realResult := result.(*user.UserServiceLoginResult)
	success, err := handler.(user.UserService).Login(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUserServiceLoginArgs() interface{} {
	return user.NewUserServiceLoginArgs()
}

func newUserServiceLoginResult() interface{} {
	return user.NewUserServiceLoginResult()
}

func getUserInfoHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*user.UserServiceGetUserInfoArgs)
	realResult := result.(*user.UserServiceGetUserInfoResult)
	success, err := handler.(user.UserService).GetUserInfo(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUserServiceGetUserInfoArgs() interface{} {
	return user.NewUserServiceGetUserInfoArgs()
}

func newUserServiceGetUserInfoResult() interface{} {
	return user.NewUserServiceGetUserInfoResult()
}

func getUserInfoByUsernameHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*user.UserServiceGetUserInfoByUsernameArgs)
	realResult := result.(*user.UserServiceGetUserInfoByUsernameResult)
	success, err := handler.(user.UserService).GetUserInfoByUsername(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUserServiceGetUserInfoByUsernameArgs() interface{} {
	return user.NewUserServiceGetUserInfoByUsernameArgs()
}

func newUserServiceGetUserInfoByUsernameResult() interface{} {
	return user.NewUserServiceGetUserInfoByUsernameResult()
}

func batchGetUserInfoHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*user.UserServiceBatchGetUserInfoArgs)
	realResult := result.(*user.UserServiceBatchGetUserInfoResult)
	success, err := handler.(user.UserService).BatchGetUserInfo(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUserServiceBatchGetUserInfoArgs() interface{} {
	return user.NewUserServiceBatchGetUserInfoArgs()
}

func newUserServiceBatchGetUserInfoResult() interface{} {
	return user.NewUserServiceBatchGetUserInfoResult()
}

func updateUserHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*user.UserServiceUpdateUserArgs)
	realResult := result.(*user.UserServiceUpdateUserResult)
	success, err := handler.(user.UserService).UpdateUser(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUserServiceUpdateUserArgs() interface{} {
	return user.NewUserServiceUpdateUserArgs()
}

func newUserServiceUpdateUserResult() interface{} {
	return user.NewUserServiceUpdateUserResult()
}

func updateAvatarHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*user.UserServiceUpdateAvatarArgs)
	realResult := result.(*user.UserServiceUpdateAvatarResult)
	success, err := handler.(user.UserService).UpdateAvatar(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUserServiceUpdateAvatarArgs() interface{} {
	return user.NewUserServiceUpdateAvatarArgs()
}

func newUserServiceUpdateAvatarResult() interface{} {
	return user.NewUserServiceUpdateAvatarResult()
}

func checkUsernameHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*user.UserServiceCheckUsernameArgs)
	realResult := result.(*user.UserServiceCheckUsernameResult)
	success, err := handler.(user.UserService).CheckUsername(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUserServiceCheckUsernameArgs() interface{} {
	return user.NewUserServiceCheckUsernameArgs()
}

func newUserServiceCheckUsernameResult() interface{} {
	return user.NewUserServiceCheckUsernameResult()
}

func batchCheckUsernamesHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*user.UserServiceBatchCheckUsernamesArgs)
	realResult := result.(*user.UserServiceBatchCheckUsernamesResult)
	success, err := handler.(user.UserService).BatchCheckUsernames(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUserServiceBatchCheckUsernamesArgs() interface{} {
	return user.NewUserServiceBatchCheckUsernamesArgs()
}

func newUserServiceBatchCheckUsernamesResult() interface{} {
	return user.NewUserServiceBatchCheckUsernamesResult()
}

func getUserStatsHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*user.UserServiceGetUserStatsArgs)
	realResult := result.(*user.UserServiceGetUserStatsResult)
	success, err := handler.(user.UserService).GetUserStats(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUserServiceGetUserStatsArgs() interface{} {
	return user.NewUserServiceGetUserStatsArgs()
}

func newUserServiceGetUserStatsResult() interface{} {
	return user.NewUserServiceGetUserStatsResult()
}

func searchUsersHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*user.UserServiceSearchUsersArgs)
	realResult := result.(*user.UserServiceSearchUsersResult)
	success, err := handler.(user.UserService).SearchUsers(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUserServiceSearchUsersArgs() interface{} {
	return user.NewUserServiceSearchUsersArgs()
}

func newUserServiceSearchUsersResult() interface{} {
	return user.NewUserServiceSearchUsersResult()
}

func updateFollowCountHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*user.UserServiceUpdateFollowCountArgs)
	realResult := result.(*user.UserServiceUpdateFollowCountResult)
	success, err := handler.(user.UserService).UpdateFollowCount(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUserServiceUpdateFollowCountArgs() interface{} {
	return user.NewUserServiceUpdateFollowCountArgs()
}

func newUserServiceUpdateFollowCountResult() interface{} {
	return user.NewUserServiceUpdateFollowCountResult()
}

func updateFollowerCountHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*user.UserServiceUpdateFollowerCountArgs)
	realResult := result.(*user.UserServiceUpdateFollowerCountResult)
	success, err := handler.(user.UserService).UpdateFollowerCount(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUserServiceUpdateFollowerCountArgs() interface{} {
	return user.NewUserServiceUpdateFollowerCountArgs()
}

func newUserServiceUpdateFollowerCountResult() interface{} {
	return user.NewUserServiceUpdateFollowerCountResult()
}

func verifyTokenHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*user.UserServiceVerifyTokenArgs)
	realResult := result.(*user.UserServiceVerifyTokenResult)
	success, err := handler.(user.UserService).VerifyToken(ctx, realArg.Token)
	if err != nil {
		return err
	}
	realResult.Success = &success
	return nil
}
func newUserServiceVerifyTokenArgs() interface{} {
	return user.NewUserServiceVerifyTokenArgs()
}

func newUserServiceVerifyTokenResult() interface{} {
	return user.NewUserServiceVerifyTokenResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) Register(ctx context.Context, req *user.RegisterReq) (r *user.LoginRegisterResp, err error) {
	var _args user.UserServiceRegisterArgs
	_args.Req = req
	var _result user.UserServiceRegisterResult
	if err = p.c.Call(ctx, "Register", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) Login(ctx context.Context, req *user.LoginReq) (r *user.LoginRegisterResp, err error) {
	var _args user.UserServiceLoginArgs
	_args.Req = req
	var _result user.UserServiceLoginResult
	if err = p.c.Call(ctx, "Login", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetUserInfo(ctx context.Context, req *user.UserInfoReq) (r *user.UserInfoResp, err error) {
	var _args user.UserServiceGetUserInfoArgs
	_args.Req = req
	var _result user.UserServiceGetUserInfoResult
	if err = p.c.Call(ctx, "GetUserInfo", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetUserInfoByUsername(ctx context.Context, req *user.UserInfoByUsernameReq) (r *user.UserInfoResp, err error) {
	var _args user.UserServiceGetUserInfoByUsernameArgs
	_args.Req = req
	var _result user.UserServiceGetUserInfoByUsernameResult
	if err = p.c.Call(ctx, "GetUserInfoByUsername", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) BatchGetUserInfo(ctx context.Context, req *user.BatchUserInfoReq) (r *user.BatchUserInfoResp, err error) {
	var _args user.UserServiceBatchGetUserInfoArgs
	_args.Req = req
	var _result user.UserServiceBatchGetUserInfoResult
	if err = p.c.Call(ctx, "BatchGetUserInfo", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) UpdateUser(ctx context.Context, req *user.UpdateUserReq) (r *common.BaseResp, err error) {
	var _args user.UserServiceUpdateUserArgs
	_args.Req = req
	var _result user.UserServiceUpdateUserResult
	if err = p.c.Call(ctx, "UpdateUser", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) UpdateAvatar(ctx context.Context, req *user.UpdateAvatarReq) (r *common.BaseResp, err error) {
	var _args user.UserServiceUpdateAvatarArgs
	_args.Req = req
	var _result user.UserServiceUpdateAvatarResult
	if err = p.c.Call(ctx, "UpdateAvatar", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) CheckUsername(ctx context.Context, req *user.CheckUsernameReq) (r *user.CheckUsernameResp, err error) {
	var _args user.UserServiceCheckUsernameArgs
	_args.Req = req
	var _result user.UserServiceCheckUsernameResult
	if err = p.c.Call(ctx, "CheckUsername", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) BatchCheckUsernames(ctx context.Context, req *user.BatchCheckUsernamesReq) (r *user.BatchCheckUsernamesResp, err error) {
	var _args user.UserServiceBatchCheckUsernamesArgs
	_args.Req = req
	var _result user.UserServiceBatchCheckUsernamesResult
	if err = p.c.Call(ctx, "BatchCheckUsernames", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetUserStats(ctx context.Context, req *user.UserStatsReq) (r *user.UserStatsResp, err error) {
	var _args user.UserServiceGetUserStatsArgs
	_args.Req = req
	var _result user.UserServiceGetUserStatsResult
	if err = p.c.Call(ctx, "GetUserStats", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) SearchUsers(ctx context.Context, req *user.SearchUsersReq) (r *user.SearchUsersResp, err error) {
	var _args user.UserServiceSearchUsersArgs
	_args.Req = req
	var _result user.UserServiceSearchUsersResult
	if err = p.c.Call(ctx, "SearchUsers", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) UpdateFollowCount(ctx context.Context, req *user.UpdateFollowCountReq) (r *common.BaseResp, err error) {
	var _args user.UserServiceUpdateFollowCountArgs
	_args.Req = req
	var _result user.UserServiceUpdateFollowCountResult
	if err = p.c.Call(ctx, "UpdateFollowCount", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) UpdateFollowerCount(ctx context.Context, req *user.UpdateFollowerCountReq) (r *common.BaseResp, err error) {
	var _args user.UserServiceUpdateFollowerCountArgs
	_args.Req = req
	var _result user.UserServiceUpdateFollowerCountResult
	if err = p.c.Call(ctx, "UpdateFollowerCount", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) VerifyToken(ctx context.Context, token string) (r bool, err error) {
	var _args user.UserServiceVerifyTokenArgs
	_args.Token = token
	var _result user.UserServiceVerifyTokenResult
	if err = p.c.Call(ctx, "VerifyToken", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
