// Code generated by Kitex v0.15.2. DO NOT EDIT.

package videoservice

import (
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	video "shortvideo/kitex_gen/video"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"PublishVideo": kitex.NewMethodInfo(
		publishVideoHandler,
		newVideoServicePublishVideoArgs,
		newVideoServicePublishVideoResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetUserVideoList": kitex.NewMethodInfo(
		getUserVideoListHandler,
		newVideoServiceGetUserVideoListArgs,
		newVideoServiceGetUserVideoListResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetFeed": kitex.NewMethodInfo(
		getFeedHandler,
		newVideoServiceGetFeedArgs,
		newVideoServiceGetFeedResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"SearchVideo": kitex.NewMethodInfo(
		searchVideoHandler,
		newVideoServiceSearchVideoArgs,
		newVideoServiceSearchVideoResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetVideoDetail": kitex.NewMethodInfo(
		getVideoDetailHandler,
		newVideoServiceGetVideoDetailArgs,
		newVideoServiceGetVideoDetailResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"BatchGetVideoInfo": kitex.NewMethodInfo(
		batchGetVideoInfoHandler,
		newVideoServiceBatchGetVideoInfoArgs,
		newVideoServiceBatchGetVideoInfoResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"DeleteVideo": kitex.NewMethodInfo(
		deleteVideoHandler,
		newVideoServiceDeleteVideoArgs,
		newVideoServiceDeleteVideoResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"UpdateVideoInfo": kitex.NewMethodInfo(
		updateVideoInfoHandler,
		newVideoServiceUpdateVideoInfoArgs,
		newVideoServiceUpdateVideoInfoResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetVideoStats": kitex.NewMethodInfo(
		getVideoStatsHandler,
		newVideoServiceGetVideoStatsArgs,
		newVideoServiceGetVideoStatsResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetHotVideos": kitex.NewMethodInfo(
		getHotVideosHandler,
		newVideoServiceGetHotVideosArgs,
		newVideoServiceGetHotVideosResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	videoServiceServiceInfo                = NewServiceInfo()
	videoServiceServiceInfoForClient       = NewServiceInfoForClient()
	videoServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return videoServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return videoServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return videoServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "VideoService"
	handlerType := (*video.VideoService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "video",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.15.2",
		Extra:           extra,
	}
	return svcInfo
}

func publishVideoHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*video.VideoServicePublishVideoArgs)
	realResult := result.(*video.VideoServicePublishVideoResult)
	success, err := handler.(video.VideoService).PublishVideo(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newVideoServicePublishVideoArgs() interface{} {
	return video.NewVideoServicePublishVideoArgs()
}

func newVideoServicePublishVideoResult() interface{} {
	return video.NewVideoServicePublishVideoResult()
}

func getUserVideoListHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*video.VideoServiceGetUserVideoListArgs)
	realResult := result.(*video.VideoServiceGetUserVideoListResult)
	success, err := handler.(video.VideoService).GetUserVideoList(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newVideoServiceGetUserVideoListArgs() interface{} {
	return video.NewVideoServiceGetUserVideoListArgs()
}

func newVideoServiceGetUserVideoListResult() interface{} {
	return video.NewVideoServiceGetUserVideoListResult()
}

func getFeedHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*video.VideoServiceGetFeedArgs)
	realResult := result.(*video.VideoServiceGetFeedResult)
	success, err := handler.(video.VideoService).GetFeed(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newVideoServiceGetFeedArgs() interface{} {
	return video.NewVideoServiceGetFeedArgs()
}

func newVideoServiceGetFeedResult() interface{} {
	return video.NewVideoServiceGetFeedResult()
}

func searchVideoHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*video.VideoServiceSearchVideoArgs)
	realResult := result.(*video.VideoServiceSearchVideoResult)
	success, err := handler.(video.VideoService).SearchVideo(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newVideoServiceSearchVideoArgs() interface{} {
	return video.NewVideoServiceSearchVideoArgs()
}

func newVideoServiceSearchVideoResult() interface{} {
	return video.NewVideoServiceSearchVideoResult()
}

func getVideoDetailHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*video.VideoServiceGetVideoDetailArgs)
	realResult := result.(*video.VideoServiceGetVideoDetailResult)
	success, err := handler.(video.VideoService).GetVideoDetail(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newVideoServiceGetVideoDetailArgs() interface{} {
	return video.NewVideoServiceGetVideoDetailArgs()
}

func newVideoServiceGetVideoDetailResult() interface{} {
	return video.NewVideoServiceGetVideoDetailResult()
}

func batchGetVideoInfoHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*video.VideoServiceBatchGetVideoInfoArgs)
	realResult := result.(*video.VideoServiceBatchGetVideoInfoResult)
	success, err := handler.(video.VideoService).BatchGetVideoInfo(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newVideoServiceBatchGetVideoInfoArgs() interface{} {
	return video.NewVideoServiceBatchGetVideoInfoArgs()
}

func newVideoServiceBatchGetVideoInfoResult() interface{} {
	return video.NewVideoServiceBatchGetVideoInfoResult()
}

func deleteVideoHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*video.VideoServiceDeleteVideoArgs)
	realResult := result.(*video.VideoServiceDeleteVideoResult)
	success, err := handler.(video.VideoService).DeleteVideo(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newVideoServiceDeleteVideoArgs() interface{} {
	return video.NewVideoServiceDeleteVideoArgs()
}

func newVideoServiceDeleteVideoResult() interface{} {
	return video.NewVideoServiceDeleteVideoResult()
}

func updateVideoInfoHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*video.VideoServiceUpdateVideoInfoArgs)
	realResult := result.(*video.VideoServiceUpdateVideoInfoResult)
	success, err := handler.(video.VideoService).UpdateVideoInfo(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newVideoServiceUpdateVideoInfoArgs() interface{} {
	return video.NewVideoServiceUpdateVideoInfoArgs()
}

func newVideoServiceUpdateVideoInfoResult() interface{} {
	return video.NewVideoServiceUpdateVideoInfoResult()
}

func getVideoStatsHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*video.VideoServiceGetVideoStatsArgs)
	realResult := result.(*video.VideoServiceGetVideoStatsResult)
	success, err := handler.(video.VideoService).GetVideoStats(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newVideoServiceGetVideoStatsArgs() interface{} {
	return video.NewVideoServiceGetVideoStatsArgs()
}

func newVideoServiceGetVideoStatsResult() interface{} {
	return video.NewVideoServiceGetVideoStatsResult()
}

func getHotVideosHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*video.VideoServiceGetHotVideosArgs)
	realResult := result.(*video.VideoServiceGetHotVideosResult)
	success, err := handler.(video.VideoService).GetHotVideos(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newVideoServiceGetHotVideosArgs() interface{} {
	return video.NewVideoServiceGetHotVideosArgs()
}

func newVideoServiceGetHotVideosResult() interface{} {
	return video.NewVideoServiceGetHotVideosResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) PublishVideo(ctx context.Context, req *video.PublishVideoReq) (r *video.PublishVideoResp, err error) {
	var _args video.VideoServicePublishVideoArgs
	_args.Req = req
	var _result video.VideoServicePublishVideoResult
	if err = p.c.Call(ctx, "PublishVideo", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetUserVideoList(ctx context.Context, req *video.UserVideoListReq) (r *video.UserVideoListResp, err error) {
	var _args video.VideoServiceGetUserVideoListArgs
	_args.Req = req
	var _result video.VideoServiceGetUserVideoListResult
	if err = p.c.Call(ctx, "GetUserVideoList", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetFeed(ctx context.Context, req *video.FeedReq) (r *video.FeedResp, err error) {
	var _args video.VideoServiceGetFeedArgs
	_args.Req = req
	var _result video.VideoServiceGetFeedResult
	if err = p.c.Call(ctx, "GetFeed", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) SearchVideo(ctx context.Context, req *video.SearchVideoReq) (r *video.SearchVideoResp, err error) {
	var _args video.VideoServiceSearchVideoArgs
	_args.Req = req
	var _result video.VideoServiceSearchVideoResult
	if err = p.c.Call(ctx, "SearchVideo", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetVideoDetail(ctx context.Context, req *video.VideoDetailReq) (r *video.VideoDetailResp, err error) {
	var _args video.VideoServiceGetVideoDetailArgs
	_args.Req = req
	var _result video.VideoServiceGetVideoDetailResult
	if err = p.c.Call(ctx, "GetVideoDetail", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) BatchGetVideoInfo(ctx context.Context, req *video.BatchVideoInfoReq) (r *video.BatchVideoInfoResp, err error) {
	var _args video.VideoServiceBatchGetVideoInfoArgs
	_args.Req = req
	var _result video.VideoServiceBatchGetVideoInfoResult
	if err = p.c.Call(ctx, "BatchGetVideoInfo", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) DeleteVideo(ctx context.Context, req *video.DeleteVideoReq) (r *video.DeleteVideoResp, err error) {
	var _args video.VideoServiceDeleteVideoArgs
	_args.Req = req
	var _result video.VideoServiceDeleteVideoResult
	if err = p.c.Call(ctx, "DeleteVideo", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) UpdateVideoInfo(ctx context.Context, req *video.UpdateVideoInfoReq) (r *video.UpdateVideoInfoResp, err error) {
	var _args video.VideoServiceUpdateVideoInfoArgs
	_args.Req = req
	var _result video.VideoServiceUpdateVideoInfoResult
	if err = p.c.Call(ctx, "UpdateVideoInfo", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetVideoStats(ctx context.Context, req *video.VideoStatsReq) (r *video.VideoStatsResp, err error) {
	var _args video.VideoServiceGetVideoStatsArgs
	_args.Req = req
	var _result video.VideoServiceGetVideoStatsResult
	if err = p.c.Call(ctx, "GetVideoStats", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetHotVideos(ctx context.Context, req *video.HotVideoReq) (r *video.HotVideoResp, err error) {
	var _args video.VideoServiceGetHotVideosArgs
	_args.Req = req
	var _result video.VideoServiceGetHotVideosResult
	if err = p.c.Call(ctx, "GetHotVideos", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
