// Code generated by Kitex v0.15.2. DO NOT EDIT.

package recommendservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	recommend "shortvideo/kitex_gen/recommend"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	GetRecommendVideos(ctx context.Context, req *recommend.GetRecommendVideosReq, callOptions ...callopt.Option) (r *recommend.GetRecommendVideosResp, err error)
	GetRecommendUsers(ctx context.Context, req *recommend.GetRecommendUsersReq, callOptions ...callopt.Option) (r *recommend.GetRecommendUsersResp, err error)
	RecordUserAction(ctx context.Context, req *recommend.UserActionReq, callOptions ...callopt.Option) (r *recommend.UserActionResp, err error)
	GetHotTags(ctx context.Context, req *recommend.GetHotTagsReq, callOptions ...callopt.Option) (r *recommend.GetHotTagsResp, err error)
	GetTagVideos(ctx context.Context, req *recommend.GetTagVideosReq, callOptions ...callopt.Option) (r *recommend.GetTagVideosResp, err error)
	GetPersonalizedFeed(ctx context.Context, req *recommend.GetPersonalizedFeedReq, callOptions ...callopt.Option) (r *recommend.GetPersonalizedFeedResp, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfoForClient(), options...)
	if err != nil {
		return nil, err
	}
	return &kRecommendServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kRecommendServiceClient struct {
	*kClient
}

func (p *kRecommendServiceClient) GetRecommendVideos(ctx context.Context, req *recommend.GetRecommendVideosReq, callOptions ...callopt.Option) (r *recommend.GetRecommendVideosResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetRecommendVideos(ctx, req)
}

func (p *kRecommendServiceClient) GetRecommendUsers(ctx context.Context, req *recommend.GetRecommendUsersReq, callOptions ...callopt.Option) (r *recommend.GetRecommendUsersResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetRecommendUsers(ctx, req)
}

func (p *kRecommendServiceClient) RecordUserAction(ctx context.Context, req *recommend.UserActionReq, callOptions ...callopt.Option) (r *recommend.UserActionResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.RecordUserAction(ctx, req)
}

func (p *kRecommendServiceClient) GetHotTags(ctx context.Context, req *recommend.GetHotTagsReq, callOptions ...callopt.Option) (r *recommend.GetHotTagsResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetHotTags(ctx, req)
}

func (p *kRecommendServiceClient) GetTagVideos(ctx context.Context, req *recommend.GetTagVideosReq, callOptions ...callopt.Option) (r *recommend.GetTagVideosResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetTagVideos(ctx, req)
}

func (p *kRecommendServiceClient) GetPersonalizedFeed(ctx context.Context, req *recommend.GetPersonalizedFeedReq, callOptions ...callopt.Option) (r *recommend.GetPersonalizedFeedResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetPersonalizedFeed(ctx, req)
}
