// Code generated by Kitex v0.15.2. DO NOT EDIT.

package recommendservice

import (
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	recommend "shortvideo/kitex_gen/recommend"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"GetRecommendVideos": kitex.NewMethodInfo(
		getRecommendVideosHandler,
		newRecommendServiceGetRecommendVideosArgs,
		newRecommendServiceGetRecommendVideosResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetRecommendUsers": kitex.NewMethodInfo(
		getRecommendUsersHandler,
		newRecommendServiceGetRecommendUsersArgs,
		newRecommendServiceGetRecommendUsersResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"RecordUserAction": kitex.NewMethodInfo(
		recordUserActionHandler,
		newRecommendServiceRecordUserActionArgs,
		newRecommendServiceRecordUserActionResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetHotTags": kitex.NewMethodInfo(
		getHotTagsHandler,
		newRecommendServiceGetHotTagsArgs,
		newRecommendServiceGetHotTagsResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetTagVideos": kitex.NewMethodInfo(
		getTagVideosHandler,
		newRecommendServiceGetTagVideosArgs,
		newRecommendServiceGetTagVideosResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetPersonalizedFeed": kitex.NewMethodInfo(
		getPersonalizedFeedHandler,
		newRecommendServiceGetPersonalizedFeedArgs,
		newRecommendServiceGetPersonalizedFeedResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	recommendServiceServiceInfo                = NewServiceInfo()
	recommendServiceServiceInfoForClient       = NewServiceInfoForClient()
	recommendServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return recommendServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return recommendServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return recommendServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "RecommendService"
	handlerType := (*recommend.RecommendService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "recommend",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.15.2",
		Extra:           extra,
	}
	return svcInfo
}

func getRecommendVideosHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*recommend.RecommendServiceGetRecommendVideosArgs)
	realResult := result.(*recommend.RecommendServiceGetRecommendVideosResult)
	success, err := handler.(recommend.RecommendService).GetRecommendVideos(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newRecommendServiceGetRecommendVideosArgs() interface{} {
	return recommend.NewRecommendServiceGetRecommendVideosArgs()
}

func newRecommendServiceGetRecommendVideosResult() interface{} {
	return recommend.NewRecommendServiceGetRecommendVideosResult()
}

func getRecommendUsersHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*recommend.RecommendServiceGetRecommendUsersArgs)
	realResult := result.(*recommend.RecommendServiceGetRecommendUsersResult)
	success, err := handler.(recommend.RecommendService).GetRecommendUsers(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newRecommendServiceGetRecommendUsersArgs() interface{} {
	return recommend.NewRecommendServiceGetRecommendUsersArgs()
}

func newRecommendServiceGetRecommendUsersResult() interface{} {
	return recommend.NewRecommendServiceGetRecommendUsersResult()
}

func recordUserActionHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*recommend.RecommendServiceRecordUserActionArgs)
	realResult := result.(*recommend.RecommendServiceRecordUserActionResult)
	success, err := handler.(recommend.RecommendService).RecordUserAction(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newRecommendServiceRecordUserActionArgs() interface{} {
	return recommend.NewRecommendServiceRecordUserActionArgs()
}

func newRecommendServiceRecordUserActionResult() interface{} {
	return recommend.NewRecommendServiceRecordUserActionResult()
}

func getHotTagsHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*recommend.RecommendServiceGetHotTagsArgs)
	realResult := result.(*recommend.RecommendServiceGetHotTagsResult)
	success, err := handler.(recommend.RecommendService).GetHotTags(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newRecommendServiceGetHotTagsArgs() interface{} {
	return recommend.NewRecommendServiceGetHotTagsArgs()
}

func newRecommendServiceGetHotTagsResult() interface{} {
	return recommend.NewRecommendServiceGetHotTagsResult()
}

func getTagVideosHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*recommend.RecommendServiceGetTagVideosArgs)
	realResult := result.(*recommend.RecommendServiceGetTagVideosResult)
	success, err := handler.(recommend.RecommendService).GetTagVideos(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newRecommendServiceGetTagVideosArgs() interface{} {
	return recommend.NewRecommendServiceGetTagVideosArgs()
}

func newRecommendServiceGetTagVideosResult() interface{} {
	return recommend.NewRecommendServiceGetTagVideosResult()
}

func getPersonalizedFeedHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*recommend.RecommendServiceGetPersonalizedFeedArgs)
	realResult := result.(*recommend.RecommendServiceGetPersonalizedFeedResult)
	success, err := handler.(recommend.RecommendService).GetPersonalizedFeed(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newRecommendServiceGetPersonalizedFeedArgs() interface{} {
	return recommend.NewRecommendServiceGetPersonalizedFeedArgs()
}

func newRecommendServiceGetPersonalizedFeedResult() interface{} {
	return recommend.NewRecommendServiceGetPersonalizedFeedResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) GetRecommendVideos(ctx context.Context, req *recommend.GetRecommendVideosReq) (r *recommend.GetRecommendVideosResp, err error) {
	var _args recommend.RecommendServiceGetRecommendVideosArgs
	_args.Req = req
	var _result recommend.RecommendServiceGetRecommendVideosResult
	if err = p.c.Call(ctx, "GetRecommendVideos", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetRecommendUsers(ctx context.Context, req *recommend.GetRecommendUsersReq) (r *recommend.GetRecommendUsersResp, err error) {
	var _args recommend.RecommendServiceGetRecommendUsersArgs
	_args.Req = req
	var _result recommend.RecommendServiceGetRecommendUsersResult
	if err = p.c.Call(ctx, "GetRecommendUsers", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) RecordUserAction(ctx context.Context, req *recommend.UserActionReq) (r *recommend.UserActionResp, err error) {
	var _args recommend.RecommendServiceRecordUserActionArgs
	_args.Req = req
	var _result recommend.RecommendServiceRecordUserActionResult
	if err = p.c.Call(ctx, "RecordUserAction", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetHotTags(ctx context.Context, req *recommend.GetHotTagsReq) (r *recommend.GetHotTagsResp, err error) {
	var _args recommend.RecommendServiceGetHotTagsArgs
	_args.Req = req
	var _result recommend.RecommendServiceGetHotTagsResult
	if err = p.c.Call(ctx, "GetHotTags", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetTagVideos(ctx context.Context, req *recommend.GetTagVideosReq) (r *recommend.GetTagVideosResp, err error) {
	var _args recommend.RecommendServiceGetTagVideosArgs
	_args.Req = req
	var _result recommend.RecommendServiceGetTagVideosResult
	if err = p.c.Call(ctx, "GetTagVideos", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetPersonalizedFeed(ctx context.Context, req *recommend.GetPersonalizedFeedReq) (r *recommend.GetPersonalizedFeedResp, err error) {
	var _args recommend.RecommendServiceGetPersonalizedFeedArgs
	_args.Req = req
	var _result recommend.RecommendServiceGetPersonalizedFeedResult
	if err = p.c.Call(ctx, "GetPersonalizedFeed", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
