// Code generated by thriftgo (0.4.3). DO NOT EDIT.

package video

import (
	"context"
	"fmt"
	"shortvideo/kitex_gen/common"
)

type PublishVideoReq struct {
	UserId      int64  `thrift:"userId,1" frugal:"1,default,i64" json:"userId"`
	Title       string `thrift:"title,2" frugal:"2,default,string" json:"title"`
	VideoUrl    string `thrift:"videoUrl,3" frugal:"3,default,string" json:"videoUrl"`
	CoverUrl    string `thrift:"coverUrl,4" frugal:"4,default,string" json:"coverUrl"`
	Description string `thrift:"description,5" frugal:"5,default,string" json:"description"`
}

func NewPublishVideoReq() *PublishVideoReq {
	return &PublishVideoReq{}
}

func (p *PublishVideoReq) InitDefault() {
}

func (p *PublishVideoReq) GetUserId() (v int64) {
	return p.UserId
}

func (p *PublishVideoReq) GetTitle() (v string) {
	return p.Title
}

func (p *PublishVideoReq) GetVideoUrl() (v string) {
	return p.VideoUrl
}

func (p *PublishVideoReq) GetCoverUrl() (v string) {
	return p.CoverUrl
}

func (p *PublishVideoReq) GetDescription() (v string) {
	return p.Description
}
func (p *PublishVideoReq) SetUserId(val int64) {
	p.UserId = val
}
func (p *PublishVideoReq) SetTitle(val string) {
	p.Title = val
}
func (p *PublishVideoReq) SetVideoUrl(val string) {
	p.VideoUrl = val
}
func (p *PublishVideoReq) SetCoverUrl(val string) {
	p.CoverUrl = val
}
func (p *PublishVideoReq) SetDescription(val string) {
	p.Description = val
}

func (p *PublishVideoReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PublishVideoReq(%+v)", *p)
}

var fieldIDToName_PublishVideoReq = map[int16]string{
	1: "userId",
	2: "title",
	3: "videoUrl",
	4: "coverUrl",
	5: "description",
}

type PublishVideoResp struct {
	BaseResp *common.BaseResp `thrift:"BaseResp,1" frugal:"1,default,common.BaseResp" json:"BaseResp"`
	VideoId  int64            `thrift:"videoId,2" frugal:"2,default,i64" json:"videoId"`
}

func NewPublishVideoResp() *PublishVideoResp {
	return &PublishVideoResp{}
}

func (p *PublishVideoResp) InitDefault() {
}

var PublishVideoResp_BaseResp_DEFAULT *common.BaseResp

func (p *PublishVideoResp) GetBaseResp() (v *common.BaseResp) {
	if !p.IsSetBaseResp() {
		return PublishVideoResp_BaseResp_DEFAULT
	}
	return p.BaseResp
}

func (p *PublishVideoResp) GetVideoId() (v int64) {
	return p.VideoId
}
func (p *PublishVideoResp) SetBaseResp(val *common.BaseResp) {
	p.BaseResp = val
}
func (p *PublishVideoResp) SetVideoId(val int64) {
	p.VideoId = val
}

func (p *PublishVideoResp) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *PublishVideoResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PublishVideoResp(%+v)", *p)
}

var fieldIDToName_PublishVideoResp = map[int16]string{
	1: "BaseResp",
	2: "videoId",
}

type UserVideoListReq struct {
	UserId        int64 `thrift:"userId,1" frugal:"1,default,i64" json:"userId"`
	CurrentUserId int64 `thrift:"currentUserId,2" frugal:"2,default,i64" json:"currentUserId"`
	Page          int32 `thrift:"page,3" frugal:"3,default,i32" json:"page"`
	PageSize      int32 `thrift:"pageSize,4" frugal:"4,default,i32" json:"pageSize"`
}

func NewUserVideoListReq() *UserVideoListReq {
	return &UserVideoListReq{}
}

func (p *UserVideoListReq) InitDefault() {
}

func (p *UserVideoListReq) GetUserId() (v int64) {
	return p.UserId
}

func (p *UserVideoListReq) GetCurrentUserId() (v int64) {
	return p.CurrentUserId
}

func (p *UserVideoListReq) GetPage() (v int32) {
	return p.Page
}

func (p *UserVideoListReq) GetPageSize() (v int32) {
	return p.PageSize
}
func (p *UserVideoListReq) SetUserId(val int64) {
	p.UserId = val
}
func (p *UserVideoListReq) SetCurrentUserId(val int64) {
	p.CurrentUserId = val
}
func (p *UserVideoListReq) SetPage(val int32) {
	p.Page = val
}
func (p *UserVideoListReq) SetPageSize(val int32) {
	p.PageSize = val
}

func (p *UserVideoListReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserVideoListReq(%+v)", *p)
}

var fieldIDToName_UserVideoListReq = map[int16]string{
	1: "userId",
	2: "currentUserId",
	3: "page",
	4: "pageSize",
}

type UserVideoListResp struct {
	BaseResp   *common.BaseResp `thrift:"BaseResp,1" frugal:"1,default,common.BaseResp" json:"BaseResp"`
	Videos     []*common.Video  `thrift:"videos,2" frugal:"2,default,list<common.Video>" json:"videos"`
	TotalCount int32            `thrift:"totalCount,3" frugal:"3,default,i32" json:"totalCount"`
}

func NewUserVideoListResp() *UserVideoListResp {
	return &UserVideoListResp{}
}

func (p *UserVideoListResp) InitDefault() {
}

var UserVideoListResp_BaseResp_DEFAULT *common.BaseResp

func (p *UserVideoListResp) GetBaseResp() (v *common.BaseResp) {
	if !p.IsSetBaseResp() {
		return UserVideoListResp_BaseResp_DEFAULT
	}
	return p.BaseResp
}

func (p *UserVideoListResp) GetVideos() (v []*common.Video) {
	return p.Videos
}

func (p *UserVideoListResp) GetTotalCount() (v int32) {
	return p.TotalCount
}
func (p *UserVideoListResp) SetBaseResp(val *common.BaseResp) {
	p.BaseResp = val
}
func (p *UserVideoListResp) SetVideos(val []*common.Video) {
	p.Videos = val
}
func (p *UserVideoListResp) SetTotalCount(val int32) {
	p.TotalCount = val
}

func (p *UserVideoListResp) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *UserVideoListResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserVideoListResp(%+v)", *p)
}

var fieldIDToName_UserVideoListResp = map[int16]string{
	1: "BaseResp",
	2: "videos",
	3: "totalCount",
}

type FeedReq struct {
	UserId     int64 `thrift:"userId,1" frugal:"1,default,i64" json:"userId"`
	LatestTime int64 `thrift:"latestTime,2" frugal:"2,default,i64" json:"latestTime"`
	PageSize   int32 `thrift:"pageSize,3" frugal:"3,default,i32" json:"pageSize"`
}

func NewFeedReq() *FeedReq {
	return &FeedReq{}
}

func (p *FeedReq) InitDefault() {
}

func (p *FeedReq) GetUserId() (v int64) {
	return p.UserId
}

func (p *FeedReq) GetLatestTime() (v int64) {
	return p.LatestTime
}

func (p *FeedReq) GetPageSize() (v int32) {
	return p.PageSize
}
func (p *FeedReq) SetUserId(val int64) {
	p.UserId = val
}
func (p *FeedReq) SetLatestTime(val int64) {
	p.LatestTime = val
}
func (p *FeedReq) SetPageSize(val int32) {
	p.PageSize = val
}

func (p *FeedReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("FeedReq(%+v)", *p)
}

var fieldIDToName_FeedReq = map[int16]string{
	1: "userId",
	2: "latestTime",
	3: "pageSize",
}

type FeedResp struct {
	BaseResp *common.BaseResp `thrift:"BaseResp,1" frugal:"1,default,common.BaseResp" json:"BaseResp"`
	Videos   []*common.Video  `thrift:"videos,2" frugal:"2,default,list<common.Video>" json:"videos"`
	NextTime int64            `thrift:"nextTime,3" frugal:"3,default,i64" json:"nextTime"`
}

func NewFeedResp() *FeedResp {
	return &FeedResp{}
}

func (p *FeedResp) InitDefault() {
}

var FeedResp_BaseResp_DEFAULT *common.BaseResp

func (p *FeedResp) GetBaseResp() (v *common.BaseResp) {
	if !p.IsSetBaseResp() {
		return FeedResp_BaseResp_DEFAULT
	}
	return p.BaseResp
}

func (p *FeedResp) GetVideos() (v []*common.Video) {
	return p.Videos
}

func (p *FeedResp) GetNextTime() (v int64) {
	return p.NextTime
}
func (p *FeedResp) SetBaseResp(val *common.BaseResp) {
	p.BaseResp = val
}
func (p *FeedResp) SetVideos(val []*common.Video) {
	p.Videos = val
}
func (p *FeedResp) SetNextTime(val int64) {
	p.NextTime = val
}

func (p *FeedResp) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *FeedResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("FeedResp(%+v)", *p)
}

var fieldIDToName_FeedResp = map[int16]string{
	1: "BaseResp",
	2: "videos",
	3: "nextTime",
}

type SearchVideoReq struct {
	Keyword       string `thrift:"keyword,1" frugal:"1,default,string" json:"keyword"`
	CurrentUserId int64  `thrift:"currentUserId,2" frugal:"2,default,i64" json:"currentUserId"`
	Page          int32  `thrift:"page,3" frugal:"3,default,i32" json:"page"`
	PageSize      int32  `thrift:"pageSize,4" frugal:"4,default,i32" json:"pageSize"`
}

func NewSearchVideoReq() *SearchVideoReq {
	return &SearchVideoReq{}
}

func (p *SearchVideoReq) InitDefault() {
}

func (p *SearchVideoReq) GetKeyword() (v string) {
	return p.Keyword
}

func (p *SearchVideoReq) GetCurrentUserId() (v int64) {
	return p.CurrentUserId
}

func (p *SearchVideoReq) GetPage() (v int32) {
	return p.Page
}

func (p *SearchVideoReq) GetPageSize() (v int32) {
	return p.PageSize
}
func (p *SearchVideoReq) SetKeyword(val string) {
	p.Keyword = val
}
func (p *SearchVideoReq) SetCurrentUserId(val int64) {
	p.CurrentUserId = val
}
func (p *SearchVideoReq) SetPage(val int32) {
	p.Page = val
}
func (p *SearchVideoReq) SetPageSize(val int32) {
	p.PageSize = val
}

func (p *SearchVideoReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SearchVideoReq(%+v)", *p)
}

var fieldIDToName_SearchVideoReq = map[int16]string{
	1: "keyword",
	2: "currentUserId",
	3: "page",
	4: "pageSize",
}

type SearchVideoResp struct {
	BaseResp   *common.BaseResp `thrift:"BaseResp,1" frugal:"1,default,common.BaseResp" json:"BaseResp"`
	Videos     []*common.Video  `thrift:"videos,2" frugal:"2,default,list<common.Video>" json:"videos"`
	TotalCount int32            `thrift:"totalCount,3" frugal:"3,default,i32" json:"totalCount"`
}

func NewSearchVideoResp() *SearchVideoResp {
	return &SearchVideoResp{}
}

func (p *SearchVideoResp) InitDefault() {
}

var SearchVideoResp_BaseResp_DEFAULT *common.BaseResp

func (p *SearchVideoResp) GetBaseResp() (v *common.BaseResp) {
	if !p.IsSetBaseResp() {
		return SearchVideoResp_BaseResp_DEFAULT
	}
	return p.BaseResp
}

func (p *SearchVideoResp) GetVideos() (v []*common.Video) {
	return p.Videos
}

func (p *SearchVideoResp) GetTotalCount() (v int32) {
	return p.TotalCount
}
func (p *SearchVideoResp) SetBaseResp(val *common.BaseResp) {
	p.BaseResp = val
}
func (p *SearchVideoResp) SetVideos(val []*common.Video) {
	p.Videos = val
}
func (p *SearchVideoResp) SetTotalCount(val int32) {
	p.TotalCount = val
}

func (p *SearchVideoResp) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *SearchVideoResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SearchVideoResp(%+v)", *p)
}

var fieldIDToName_SearchVideoResp = map[int16]string{
	1: "BaseResp",
	2: "videos",
	3: "totalCount",
}

type VideoDetailReq struct {
	VideoId       int64 `thrift:"videoId,1" frugal:"1,default,i64" json:"videoId"`
	CurrentUserId int64 `thrift:"currentUserId,2" frugal:"2,default,i64" json:"currentUserId"`
}

func NewVideoDetailReq() *VideoDetailReq {
	return &VideoDetailReq{}
}

func (p *VideoDetailReq) InitDefault() {
}

func (p *VideoDetailReq) GetVideoId() (v int64) {
	return p.VideoId
}

func (p *VideoDetailReq) GetCurrentUserId() (v int64) {
	return p.CurrentUserId
}
func (p *VideoDetailReq) SetVideoId(val int64) {
	p.VideoId = val
}
func (p *VideoDetailReq) SetCurrentUserId(val int64) {
	p.CurrentUserId = val
}

func (p *VideoDetailReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("VideoDetailReq(%+v)", *p)
}

var fieldIDToName_VideoDetailReq = map[int16]string{
	1: "videoId",
	2: "currentUserId",
}

type VideoDetailResp struct {
	BaseResp *common.BaseResp `thrift:"BaseResp,1" frugal:"1,default,common.BaseResp" json:"BaseResp"`
	Video    *common.Video    `thrift:"video,2" frugal:"2,default,common.Video" json:"video"`
}

func NewVideoDetailResp() *VideoDetailResp {
	return &VideoDetailResp{}
}

func (p *VideoDetailResp) InitDefault() {
}

var VideoDetailResp_BaseResp_DEFAULT *common.BaseResp

func (p *VideoDetailResp) GetBaseResp() (v *common.BaseResp) {
	if !p.IsSetBaseResp() {
		return VideoDetailResp_BaseResp_DEFAULT
	}
	return p.BaseResp
}

var VideoDetailResp_Video_DEFAULT *common.Video

func (p *VideoDetailResp) GetVideo() (v *common.Video) {
	if !p.IsSetVideo() {
		return VideoDetailResp_Video_DEFAULT
	}
	return p.Video
}
func (p *VideoDetailResp) SetBaseResp(val *common.BaseResp) {
	p.BaseResp = val
}
func (p *VideoDetailResp) SetVideo(val *common.Video) {
	p.Video = val
}

func (p *VideoDetailResp) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *VideoDetailResp) IsSetVideo() bool {
	return p.Video != nil
}

func (p *VideoDetailResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("VideoDetailResp(%+v)", *p)
}

var fieldIDToName_VideoDetailResp = map[int16]string{
	1: "BaseResp",
	2: "video",
}

type BatchVideoInfoReq struct {
	CurrentUserId int64   `thrift:"currentUserId,1" frugal:"1,default,i64" json:"currentUserId"`
	VideoIds      []int64 `thrift:"videoIds,2" frugal:"2,default,list<i64>" json:"videoIds"`
}

func NewBatchVideoInfoReq() *BatchVideoInfoReq {
	return &BatchVideoInfoReq{}
}

func (p *BatchVideoInfoReq) InitDefault() {
}

func (p *BatchVideoInfoReq) GetCurrentUserId() (v int64) {
	return p.CurrentUserId
}

func (p *BatchVideoInfoReq) GetVideoIds() (v []int64) {
	return p.VideoIds
}
func (p *BatchVideoInfoReq) SetCurrentUserId(val int64) {
	p.CurrentUserId = val
}
func (p *BatchVideoInfoReq) SetVideoIds(val []int64) {
	p.VideoIds = val
}

func (p *BatchVideoInfoReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("BatchVideoInfoReq(%+v)", *p)
}

var fieldIDToName_BatchVideoInfoReq = map[int16]string{
	1: "currentUserId",
	2: "videoIds",
}

type BatchVideoInfoResp struct {
	BaseResp *common.BaseResp        `thrift:"BaseResp,1" frugal:"1,default,common.BaseResp" json:"BaseResp"`
	Videos   map[int64]*common.Video `thrift:"videos,2" frugal:"2,default,map<i64:common.Video>" json:"videos"`
}

func NewBatchVideoInfoResp() *BatchVideoInfoResp {
	return &BatchVideoInfoResp{}
}

func (p *BatchVideoInfoResp) InitDefault() {
}

var BatchVideoInfoResp_BaseResp_DEFAULT *common.BaseResp

func (p *BatchVideoInfoResp) GetBaseResp() (v *common.BaseResp) {
	if !p.IsSetBaseResp() {
		return BatchVideoInfoResp_BaseResp_DEFAULT
	}
	return p.BaseResp
}

func (p *BatchVideoInfoResp) GetVideos() (v map[int64]*common.Video) {
	return p.Videos
}
func (p *BatchVideoInfoResp) SetBaseResp(val *common.BaseResp) {
	p.BaseResp = val
}
func (p *BatchVideoInfoResp) SetVideos(val map[int64]*common.Video) {
	p.Videos = val
}

func (p *BatchVideoInfoResp) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *BatchVideoInfoResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("BatchVideoInfoResp(%+v)", *p)
}

var fieldIDToName_BatchVideoInfoResp = map[int16]string{
	1: "BaseResp",
	2: "videos",
}

type DeleteVideoReq struct {
	VideoId int64 `thrift:"videoId,1" frugal:"1,default,i64" json:"videoId"`
	UserId  int64 `thrift:"userId,2" frugal:"2,default,i64" json:"userId"`
}

func NewDeleteVideoReq() *DeleteVideoReq {
	return &DeleteVideoReq{}
}

func (p *DeleteVideoReq) InitDefault() {
}

func (p *DeleteVideoReq) GetVideoId() (v int64) {
	return p.VideoId
}

func (p *DeleteVideoReq) GetUserId() (v int64) {
	return p.UserId
}
func (p *DeleteVideoReq) SetVideoId(val int64) {
	p.VideoId = val
}
func (p *DeleteVideoReq) SetUserId(val int64) {
	p.UserId = val
}

func (p *DeleteVideoReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DeleteVideoReq(%+v)", *p)
}

var fieldIDToName_DeleteVideoReq = map[int16]string{
	1: "videoId",
	2: "userId",
}

type DeleteVideoResp struct {
	BaseResp *common.BaseResp `thrift:"BaseResp,1" frugal:"1,default,common.BaseResp" json:"BaseResp"`
}

func NewDeleteVideoResp() *DeleteVideoResp {
	return &DeleteVideoResp{}
}

func (p *DeleteVideoResp) InitDefault() {
}

var DeleteVideoResp_BaseResp_DEFAULT *common.BaseResp

func (p *DeleteVideoResp) GetBaseResp() (v *common.BaseResp) {
	if !p.IsSetBaseResp() {
		return DeleteVideoResp_BaseResp_DEFAULT
	}
	return p.BaseResp
}
func (p *DeleteVideoResp) SetBaseResp(val *common.BaseResp) {
	p.BaseResp = val
}

func (p *DeleteVideoResp) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *DeleteVideoResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DeleteVideoResp(%+v)", *p)
}

var fieldIDToName_DeleteVideoResp = map[int16]string{
	1: "BaseResp",
}

type UpdateVideoInfoReq struct {
	VideoId     int64   `thrift:"videoId,1" frugal:"1,default,i64" json:"videoId"`
	UserId      int64   `thrift:"userId,2" frugal:"2,default,i64" json:"userId"`
	Title       *string `thrift:"title,3,optional" frugal:"3,optional,string" json:"title,omitempty"`
	Description *string `thrift:"description,4,optional" frugal:"4,optional,string" json:"description,omitempty"`
}

func NewUpdateVideoInfoReq() *UpdateVideoInfoReq {
	return &UpdateVideoInfoReq{}
}

func (p *UpdateVideoInfoReq) InitDefault() {
}

func (p *UpdateVideoInfoReq) GetVideoId() (v int64) {
	return p.VideoId
}

func (p *UpdateVideoInfoReq) GetUserId() (v int64) {
	return p.UserId
}

var UpdateVideoInfoReq_Title_DEFAULT string

func (p *UpdateVideoInfoReq) GetTitle() (v string) {
	if !p.IsSetTitle() {
		return UpdateVideoInfoReq_Title_DEFAULT
	}
	return *p.Title
}

var UpdateVideoInfoReq_Description_DEFAULT string

func (p *UpdateVideoInfoReq) GetDescription() (v string) {
	if !p.IsSetDescription() {
		return UpdateVideoInfoReq_Description_DEFAULT
	}
	return *p.Description
}
func (p *UpdateVideoInfoReq) SetVideoId(val int64) {
	p.VideoId = val
}
func (p *UpdateVideoInfoReq) SetUserId(val int64) {
	p.UserId = val
}
func (p *UpdateVideoInfoReq) SetTitle(val *string) {
	p.Title = val
}
func (p *UpdateVideoInfoReq) SetDescription(val *string) {
	p.Description = val
}

func (p *UpdateVideoInfoReq) IsSetTitle() bool {
	return p.Title != nil
}

func (p *UpdateVideoInfoReq) IsSetDescription() bool {
	return p.Description != nil
}

func (p *UpdateVideoInfoReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UpdateVideoInfoReq(%+v)", *p)
}

var fieldIDToName_UpdateVideoInfoReq = map[int16]string{
	1: "videoId",
	2: "userId",
	3: "title",
	4: "description",
}

type UpdateVideoInfoResp struct {
	BaseResp *common.BaseResp `thrift:"BaseResp,1" frugal:"1,default,common.BaseResp" json:"BaseResp"`
}

func NewUpdateVideoInfoResp() *UpdateVideoInfoResp {
	return &UpdateVideoInfoResp{}
}

func (p *UpdateVideoInfoResp) InitDefault() {
}

var UpdateVideoInfoResp_BaseResp_DEFAULT *common.BaseResp

func (p *UpdateVideoInfoResp) GetBaseResp() (v *common.BaseResp) {
	if !p.IsSetBaseResp() {
		return UpdateVideoInfoResp_BaseResp_DEFAULT
	}
	return p.BaseResp
}
func (p *UpdateVideoInfoResp) SetBaseResp(val *common.BaseResp) {
	p.BaseResp = val
}

func (p *UpdateVideoInfoResp) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *UpdateVideoInfoResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UpdateVideoInfoResp(%+v)", *p)
}

var fieldIDToName_UpdateVideoInfoResp = map[int16]string{
	1: "BaseResp",
}

type VideoStatsReq struct {
	VideoId int64 `thrift:"videoId,1" frugal:"1,default,i64" json:"videoId"`
}

func NewVideoStatsReq() *VideoStatsReq {
	return &VideoStatsReq{}
}

func (p *VideoStatsReq) InitDefault() {
}

func (p *VideoStatsReq) GetVideoId() (v int64) {
	return p.VideoId
}
func (p *VideoStatsReq) SetVideoId(val int64) {
	p.VideoId = val
}

func (p *VideoStatsReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("VideoStatsReq(%+v)", *p)
}

var fieldIDToName_VideoStatsReq = map[int16]string{
	1: "videoId",
}

type VideoStats struct {
	VideoId      int64 `thrift:"videoId,1" frugal:"1,default,i64" json:"videoId"`
	ViewCount    int64 `thrift:"viewCount,2" frugal:"2,default,i64" json:"viewCount"`
	LikeCount    int64 `thrift:"likeCount,3" frugal:"3,default,i64" json:"likeCount"`
	CommentCount int64 `thrift:"commentCount,4" frugal:"4,default,i64" json:"commentCount"`
	ShareCount   int64 `thrift:"shareCount,5" frugal:"5,default,i64" json:"shareCount"`
}

func NewVideoStats() *VideoStats {
	return &VideoStats{}
}

func (p *VideoStats) InitDefault() {
}

func (p *VideoStats) GetVideoId() (v int64) {
	return p.VideoId
}

func (p *VideoStats) GetViewCount() (v int64) {
	return p.ViewCount
}

func (p *VideoStats) GetLikeCount() (v int64) {
	return p.LikeCount
}

func (p *VideoStats) GetCommentCount() (v int64) {
	return p.CommentCount
}

func (p *VideoStats) GetShareCount() (v int64) {
	return p.ShareCount
}
func (p *VideoStats) SetVideoId(val int64) {
	p.VideoId = val
}
func (p *VideoStats) SetViewCount(val int64) {
	p.ViewCount = val
}
func (p *VideoStats) SetLikeCount(val int64) {
	p.LikeCount = val
}
func (p *VideoStats) SetCommentCount(val int64) {
	p.CommentCount = val
}
func (p *VideoStats) SetShareCount(val int64) {
	p.ShareCount = val
}

func (p *VideoStats) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("VideoStats(%+v)", *p)
}

var fieldIDToName_VideoStats = map[int16]string{
	1: "videoId",
	2: "viewCount",
	3: "likeCount",
	4: "commentCount",
	5: "shareCount",
}

type VideoStatsResp struct {
	BaseResp *common.BaseResp `thrift:"BaseResp,1" frugal:"1,default,common.BaseResp" json:"BaseResp"`
	Stats    *VideoStats      `thrift:"stats,2" frugal:"2,default,VideoStats" json:"stats"`
}

func NewVideoStatsResp() *VideoStatsResp {
	return &VideoStatsResp{}
}

func (p *VideoStatsResp) InitDefault() {
}

var VideoStatsResp_BaseResp_DEFAULT *common.BaseResp

func (p *VideoStatsResp) GetBaseResp() (v *common.BaseResp) {
	if !p.IsSetBaseResp() {
		return VideoStatsResp_BaseResp_DEFAULT
	}
	return p.BaseResp
}

var VideoStatsResp_Stats_DEFAULT *VideoStats

func (p *VideoStatsResp) GetStats() (v *VideoStats) {
	if !p.IsSetStats() {
		return VideoStatsResp_Stats_DEFAULT
	}
	return p.Stats
}
func (p *VideoStatsResp) SetBaseResp(val *common.BaseResp) {
	p.BaseResp = val
}
func (p *VideoStatsResp) SetStats(val *VideoStats) {
	p.Stats = val
}

func (p *VideoStatsResp) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *VideoStatsResp) IsSetStats() bool {
	return p.Stats != nil
}

func (p *VideoStatsResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("VideoStatsResp(%+v)", *p)
}

var fieldIDToName_VideoStatsResp = map[int16]string{
	1: "BaseResp",
	2: "stats",
}

type HotVideoReq struct {
	UserId   int64 `thrift:"userId,1" frugal:"1,default,i64" json:"userId"`
	PageSize int32 `thrift:"pageSize,2" frugal:"2,default,i32" json:"pageSize"`
}

func NewHotVideoReq() *HotVideoReq {
	return &HotVideoReq{}
}

func (p *HotVideoReq) InitDefault() {
}

func (p *HotVideoReq) GetUserId() (v int64) {
	return p.UserId
}

func (p *HotVideoReq) GetPageSize() (v int32) {
	return p.PageSize
}
func (p *HotVideoReq) SetUserId(val int64) {
	p.UserId = val
}
func (p *HotVideoReq) SetPageSize(val int32) {
	p.PageSize = val
}

func (p *HotVideoReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("HotVideoReq(%+v)", *p)
}

var fieldIDToName_HotVideoReq = map[int16]string{
	1: "userId",
	2: "pageSize",
}

type HotVideoResp struct {
	BaseResp *common.BaseResp `thrift:"BaseResp,1" frugal:"1,default,common.BaseResp" json:"BaseResp"`
	Videos   []*common.Video  `thrift:"videos,2" frugal:"2,default,list<common.Video>" json:"videos"`
}

func NewHotVideoResp() *HotVideoResp {
	return &HotVideoResp{}
}

func (p *HotVideoResp) InitDefault() {
}

var HotVideoResp_BaseResp_DEFAULT *common.BaseResp

func (p *HotVideoResp) GetBaseResp() (v *common.BaseResp) {
	if !p.IsSetBaseResp() {
		return HotVideoResp_BaseResp_DEFAULT
	}
	return p.BaseResp
}

func (p *HotVideoResp) GetVideos() (v []*common.Video) {
	return p.Videos
}
func (p *HotVideoResp) SetBaseResp(val *common.BaseResp) {
	p.BaseResp = val
}
func (p *HotVideoResp) SetVideos(val []*common.Video) {
	p.Videos = val
}

func (p *HotVideoResp) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *HotVideoResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("HotVideoResp(%+v)", *p)
}

var fieldIDToName_HotVideoResp = map[int16]string{
	1: "BaseResp",
	2: "videos",
}

type VideoService interface {
	PublishVideo(ctx context.Context, req *PublishVideoReq) (r *PublishVideoResp, err error)

	GetUserVideoList(ctx context.Context, req *UserVideoListReq) (r *UserVideoListResp, err error)

	GetFeed(ctx context.Context, req *FeedReq) (r *FeedResp, err error)

	SearchVideo(ctx context.Context, req *SearchVideoReq) (r *SearchVideoResp, err error)

	GetVideoDetail(ctx context.Context, req *VideoDetailReq) (r *VideoDetailResp, err error)

	BatchGetVideoInfo(ctx context.Context, req *BatchVideoInfoReq) (r *BatchVideoInfoResp, err error)

	DeleteVideo(ctx context.Context, req *DeleteVideoReq) (r *DeleteVideoResp, err error)

	UpdateVideoInfo(ctx context.Context, req *UpdateVideoInfoReq) (r *UpdateVideoInfoResp, err error)

	GetVideoStats(ctx context.Context, req *VideoStatsReq) (r *VideoStatsResp, err error)

	GetHotVideos(ctx context.Context, req *HotVideoReq) (r *HotVideoResp, err error)
}

type VideoServicePublishVideoArgs struct {
	Req *PublishVideoReq `thrift:"req,1" frugal:"1,default,PublishVideoReq" json:"req"`
}

func NewVideoServicePublishVideoArgs() *VideoServicePublishVideoArgs {
	return &VideoServicePublishVideoArgs{}
}

func (p *VideoServicePublishVideoArgs) InitDefault() {
}

var VideoServicePublishVideoArgs_Req_DEFAULT *PublishVideoReq

func (p *VideoServicePublishVideoArgs) GetReq() (v *PublishVideoReq) {
	if !p.IsSetReq() {
		return VideoServicePublishVideoArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *VideoServicePublishVideoArgs) SetReq(val *PublishVideoReq) {
	p.Req = val
}

func (p *VideoServicePublishVideoArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *VideoServicePublishVideoArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("VideoServicePublishVideoArgs(%+v)", *p)
}

var fieldIDToName_VideoServicePublishVideoArgs = map[int16]string{
	1: "req",
}

type VideoServicePublishVideoResult struct {
	Success *PublishVideoResp `thrift:"success,0,optional" frugal:"0,optional,PublishVideoResp" json:"success,omitempty"`
}

func NewVideoServicePublishVideoResult() *VideoServicePublishVideoResult {
	return &VideoServicePublishVideoResult{}
}

func (p *VideoServicePublishVideoResult) InitDefault() {
}

var VideoServicePublishVideoResult_Success_DEFAULT *PublishVideoResp

func (p *VideoServicePublishVideoResult) GetSuccess() (v *PublishVideoResp) {
	if !p.IsSetSuccess() {
		return VideoServicePublishVideoResult_Success_DEFAULT
	}
	return p.Success
}
func (p *VideoServicePublishVideoResult) SetSuccess(x interface{}) {
	p.Success = x.(*PublishVideoResp)
}

func (p *VideoServicePublishVideoResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *VideoServicePublishVideoResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("VideoServicePublishVideoResult(%+v)", *p)
}

var fieldIDToName_VideoServicePublishVideoResult = map[int16]string{
	0: "success",
}

type VideoServiceGetUserVideoListArgs struct {
	Req *UserVideoListReq `thrift:"req,1" frugal:"1,default,UserVideoListReq" json:"req"`
}

func NewVideoServiceGetUserVideoListArgs() *VideoServiceGetUserVideoListArgs {
	return &VideoServiceGetUserVideoListArgs{}
}

func (p *VideoServiceGetUserVideoListArgs) InitDefault() {
}

var VideoServiceGetUserVideoListArgs_Req_DEFAULT *UserVideoListReq

func (p *VideoServiceGetUserVideoListArgs) GetReq() (v *UserVideoListReq) {
	if !p.IsSetReq() {
		return VideoServiceGetUserVideoListArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *VideoServiceGetUserVideoListArgs) SetReq(val *UserVideoListReq) {
	p.Req = val
}

func (p *VideoServiceGetUserVideoListArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *VideoServiceGetUserVideoListArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("VideoServiceGetUserVideoListArgs(%+v)", *p)
}

var fieldIDToName_VideoServiceGetUserVideoListArgs = map[int16]string{
	1: "req",
}

type VideoServiceGetUserVideoListResult struct {
	Success *UserVideoListResp `thrift:"success,0,optional" frugal:"0,optional,UserVideoListResp" json:"success,omitempty"`
}

func NewVideoServiceGetUserVideoListResult() *VideoServiceGetUserVideoListResult {
	return &VideoServiceGetUserVideoListResult{}
}

func (p *VideoServiceGetUserVideoListResult) InitDefault() {
}

var VideoServiceGetUserVideoListResult_Success_DEFAULT *UserVideoListResp

func (p *VideoServiceGetUserVideoListResult) GetSuccess() (v *UserVideoListResp) {
	if !p.IsSetSuccess() {
		return VideoServiceGetUserVideoListResult_Success_DEFAULT
	}
	return p.Success
}
func (p *VideoServiceGetUserVideoListResult) SetSuccess(x interface{}) {
	p.Success = x.(*UserVideoListResp)
}

func (p *VideoServiceGetUserVideoListResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *VideoServiceGetUserVideoListResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("VideoServiceGetUserVideoListResult(%+v)", *p)
}

var fieldIDToName_VideoServiceGetUserVideoListResult = map[int16]string{
	0: "success",
}

type VideoServiceGetFeedArgs struct {
	Req *FeedReq `thrift:"req,1" frugal:"1,default,FeedReq" json:"req"`
}

func NewVideoServiceGetFeedArgs() *VideoServiceGetFeedArgs {
	return &VideoServiceGetFeedArgs{}
}

func (p *VideoServiceGetFeedArgs) InitDefault() {
}

var VideoServiceGetFeedArgs_Req_DEFAULT *FeedReq

func (p *VideoServiceGetFeedArgs) GetReq() (v *FeedReq) {
	if !p.IsSetReq() {
		return VideoServiceGetFeedArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *VideoServiceGetFeedArgs) SetReq(val *FeedReq) {
	p.Req = val
}

func (p *VideoServiceGetFeedArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *VideoServiceGetFeedArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("VideoServiceGetFeedArgs(%+v)", *p)
}

var fieldIDToName_VideoServiceGetFeedArgs = map[int16]string{
	1: "req",
}

type VideoServiceGetFeedResult struct {
	Success *FeedResp `thrift:"success,0,optional" frugal:"0,optional,FeedResp" json:"success,omitempty"`
}

func NewVideoServiceGetFeedResult() *VideoServiceGetFeedResult {
	return &VideoServiceGetFeedResult{}
}

func (p *VideoServiceGetFeedResult) InitDefault() {
}

var VideoServiceGetFeedResult_Success_DEFAULT *FeedResp

func (p *VideoServiceGetFeedResult) GetSuccess() (v *FeedResp) {
	if !p.IsSetSuccess() {
		return VideoServiceGetFeedResult_Success_DEFAULT
	}
	return p.Success
}
func (p *VideoServiceGetFeedResult) SetSuccess(x interface{}) {
	p.Success = x.(*FeedResp)
}

func (p *VideoServiceGetFeedResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *VideoServiceGetFeedResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("VideoServiceGetFeedResult(%+v)", *p)
}

var fieldIDToName_VideoServiceGetFeedResult = map[int16]string{
	0: "success",
}

type VideoServiceSearchVideoArgs struct {
	Req *SearchVideoReq `thrift:"req,1" frugal:"1,default,SearchVideoReq" json:"req"`
}

func NewVideoServiceSearchVideoArgs() *VideoServiceSearchVideoArgs {
	return &VideoServiceSearchVideoArgs{}
}

func (p *VideoServiceSearchVideoArgs) InitDefault() {
}

var VideoServiceSearchVideoArgs_Req_DEFAULT *SearchVideoReq

func (p *VideoServiceSearchVideoArgs) GetReq() (v *SearchVideoReq) {
	if !p.IsSetReq() {
		return VideoServiceSearchVideoArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *VideoServiceSearchVideoArgs) SetReq(val *SearchVideoReq) {
	p.Req = val
}

func (p *VideoServiceSearchVideoArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *VideoServiceSearchVideoArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("VideoServiceSearchVideoArgs(%+v)", *p)
}

var fieldIDToName_VideoServiceSearchVideoArgs = map[int16]string{
	1: "req",
}

type VideoServiceSearchVideoResult struct {
	Success *SearchVideoResp `thrift:"success,0,optional" frugal:"0,optional,SearchVideoResp" json:"success,omitempty"`
}

func NewVideoServiceSearchVideoResult() *VideoServiceSearchVideoResult {
	return &VideoServiceSearchVideoResult{}
}

func (p *VideoServiceSearchVideoResult) InitDefault() {
}

var VideoServiceSearchVideoResult_Success_DEFAULT *SearchVideoResp

func (p *VideoServiceSearchVideoResult) GetSuccess() (v *SearchVideoResp) {
	if !p.IsSetSuccess() {
		return VideoServiceSearchVideoResult_Success_DEFAULT
	}
	return p.Success
}
func (p *VideoServiceSearchVideoResult) SetSuccess(x interface{}) {
	p.Success = x.(*SearchVideoResp)
}

func (p *VideoServiceSearchVideoResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *VideoServiceSearchVideoResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("VideoServiceSearchVideoResult(%+v)", *p)
}

var fieldIDToName_VideoServiceSearchVideoResult = map[int16]string{
	0: "success",
}

type VideoServiceGetVideoDetailArgs struct {
	Req *VideoDetailReq `thrift:"req,1" frugal:"1,default,VideoDetailReq" json:"req"`
}

func NewVideoServiceGetVideoDetailArgs() *VideoServiceGetVideoDetailArgs {
	return &VideoServiceGetVideoDetailArgs{}
}

func (p *VideoServiceGetVideoDetailArgs) InitDefault() {
}

var VideoServiceGetVideoDetailArgs_Req_DEFAULT *VideoDetailReq

func (p *VideoServiceGetVideoDetailArgs) GetReq() (v *VideoDetailReq) {
	if !p.IsSetReq() {
		return VideoServiceGetVideoDetailArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *VideoServiceGetVideoDetailArgs) SetReq(val *VideoDetailReq) {
	p.Req = val
}

func (p *VideoServiceGetVideoDetailArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *VideoServiceGetVideoDetailArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("VideoServiceGetVideoDetailArgs(%+v)", *p)
}

var fieldIDToName_VideoServiceGetVideoDetailArgs = map[int16]string{
	1: "req",
}

type VideoServiceGetVideoDetailResult struct {
	Success *VideoDetailResp `thrift:"success,0,optional" frugal:"0,optional,VideoDetailResp" json:"success,omitempty"`
}

func NewVideoServiceGetVideoDetailResult() *VideoServiceGetVideoDetailResult {
	return &VideoServiceGetVideoDetailResult{}
}

func (p *VideoServiceGetVideoDetailResult) InitDefault() {
}

var VideoServiceGetVideoDetailResult_Success_DEFAULT *VideoDetailResp

func (p *VideoServiceGetVideoDetailResult) GetSuccess() (v *VideoDetailResp) {
	if !p.IsSetSuccess() {
		return VideoServiceGetVideoDetailResult_Success_DEFAULT
	}
	return p.Success
}
func (p *VideoServiceGetVideoDetailResult) SetSuccess(x interface{}) {
	p.Success = x.(*VideoDetailResp)
}

func (p *VideoServiceGetVideoDetailResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *VideoServiceGetVideoDetailResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("VideoServiceGetVideoDetailResult(%+v)", *p)
}

var fieldIDToName_VideoServiceGetVideoDetailResult = map[int16]string{
	0: "success",
}

type VideoServiceBatchGetVideoInfoArgs struct {
	Req *BatchVideoInfoReq `thrift:"req,1" frugal:"1,default,BatchVideoInfoReq" json:"req"`
}

func NewVideoServiceBatchGetVideoInfoArgs() *VideoServiceBatchGetVideoInfoArgs {
	return &VideoServiceBatchGetVideoInfoArgs{}
}

func (p *VideoServiceBatchGetVideoInfoArgs) InitDefault() {
}

var VideoServiceBatchGetVideoInfoArgs_Req_DEFAULT *BatchVideoInfoReq

func (p *VideoServiceBatchGetVideoInfoArgs) GetReq() (v *BatchVideoInfoReq) {
	if !p.IsSetReq() {
		return VideoServiceBatchGetVideoInfoArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *VideoServiceBatchGetVideoInfoArgs) SetReq(val *BatchVideoInfoReq) {
	p.Req = val
}

func (p *VideoServiceBatchGetVideoInfoArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *VideoServiceBatchGetVideoInfoArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("VideoServiceBatchGetVideoInfoArgs(%+v)", *p)
}

var fieldIDToName_VideoServiceBatchGetVideoInfoArgs = map[int16]string{
	1: "req",
}

type VideoServiceBatchGetVideoInfoResult struct {
	Success *BatchVideoInfoResp `thrift:"success,0,optional" frugal:"0,optional,BatchVideoInfoResp" json:"success,omitempty"`
}

func NewVideoServiceBatchGetVideoInfoResult() *VideoServiceBatchGetVideoInfoResult {
	return &VideoServiceBatchGetVideoInfoResult{}
}

func (p *VideoServiceBatchGetVideoInfoResult) InitDefault() {
}

var VideoServiceBatchGetVideoInfoResult_Success_DEFAULT *BatchVideoInfoResp

func (p *VideoServiceBatchGetVideoInfoResult) GetSuccess() (v *BatchVideoInfoResp) {
	if !p.IsSetSuccess() {
		return VideoServiceBatchGetVideoInfoResult_Success_DEFAULT
	}
	return p.Success
}
func (p *VideoServiceBatchGetVideoInfoResult) SetSuccess(x interface{}) {
	p.Success = x.(*BatchVideoInfoResp)
}

func (p *VideoServiceBatchGetVideoInfoResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *VideoServiceBatchGetVideoInfoResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("VideoServiceBatchGetVideoInfoResult(%+v)", *p)
}

var fieldIDToName_VideoServiceBatchGetVideoInfoResult = map[int16]string{
	0: "success",
}

type VideoServiceDeleteVideoArgs struct {
	Req *DeleteVideoReq `thrift:"req,1" frugal:"1,default,DeleteVideoReq" json:"req"`
}

func NewVideoServiceDeleteVideoArgs() *VideoServiceDeleteVideoArgs {
	return &VideoServiceDeleteVideoArgs{}
}

func (p *VideoServiceDeleteVideoArgs) InitDefault() {
}

var VideoServiceDeleteVideoArgs_Req_DEFAULT *DeleteVideoReq

func (p *VideoServiceDeleteVideoArgs) GetReq() (v *DeleteVideoReq) {
	if !p.IsSetReq() {
		return VideoServiceDeleteVideoArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *VideoServiceDeleteVideoArgs) SetReq(val *DeleteVideoReq) {
	p.Req = val
}

func (p *VideoServiceDeleteVideoArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *VideoServiceDeleteVideoArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("VideoServiceDeleteVideoArgs(%+v)", *p)
}

var fieldIDToName_VideoServiceDeleteVideoArgs = map[int16]string{
	1: "req",
}

type VideoServiceDeleteVideoResult struct {
	Success *DeleteVideoResp `thrift:"success,0,optional" frugal:"0,optional,DeleteVideoResp" json:"success,omitempty"`
}

func NewVideoServiceDeleteVideoResult() *VideoServiceDeleteVideoResult {
	return &VideoServiceDeleteVideoResult{}
}

func (p *VideoServiceDeleteVideoResult) InitDefault() {
}

var VideoServiceDeleteVideoResult_Success_DEFAULT *DeleteVideoResp

func (p *VideoServiceDeleteVideoResult) GetSuccess() (v *DeleteVideoResp) {
	if !p.IsSetSuccess() {
		return VideoServiceDeleteVideoResult_Success_DEFAULT
	}
	return p.Success
}
func (p *VideoServiceDeleteVideoResult) SetSuccess(x interface{}) {
	p.Success = x.(*DeleteVideoResp)
}

func (p *VideoServiceDeleteVideoResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *VideoServiceDeleteVideoResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("VideoServiceDeleteVideoResult(%+v)", *p)
}

var fieldIDToName_VideoServiceDeleteVideoResult = map[int16]string{
	0: "success",
}

type VideoServiceUpdateVideoInfoArgs struct {
	Req *UpdateVideoInfoReq `thrift:"req,1" frugal:"1,default,UpdateVideoInfoReq" json:"req"`
}

func NewVideoServiceUpdateVideoInfoArgs() *VideoServiceUpdateVideoInfoArgs {
	return &VideoServiceUpdateVideoInfoArgs{}
}

func (p *VideoServiceUpdateVideoInfoArgs) InitDefault() {
}

var VideoServiceUpdateVideoInfoArgs_Req_DEFAULT *UpdateVideoInfoReq

func (p *VideoServiceUpdateVideoInfoArgs) GetReq() (v *UpdateVideoInfoReq) {
	if !p.IsSetReq() {
		return VideoServiceUpdateVideoInfoArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *VideoServiceUpdateVideoInfoArgs) SetReq(val *UpdateVideoInfoReq) {
	p.Req = val
}

func (p *VideoServiceUpdateVideoInfoArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *VideoServiceUpdateVideoInfoArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("VideoServiceUpdateVideoInfoArgs(%+v)", *p)
}

var fieldIDToName_VideoServiceUpdateVideoInfoArgs = map[int16]string{
	1: "req",
}

type VideoServiceUpdateVideoInfoResult struct {
	Success *UpdateVideoInfoResp `thrift:"success,0,optional" frugal:"0,optional,UpdateVideoInfoResp" json:"success,omitempty"`
}

func NewVideoServiceUpdateVideoInfoResult() *VideoServiceUpdateVideoInfoResult {
	return &VideoServiceUpdateVideoInfoResult{}
}

func (p *VideoServiceUpdateVideoInfoResult) InitDefault() {
}

var VideoServiceUpdateVideoInfoResult_Success_DEFAULT *UpdateVideoInfoResp

func (p *VideoServiceUpdateVideoInfoResult) GetSuccess() (v *UpdateVideoInfoResp) {
	if !p.IsSetSuccess() {
		return VideoServiceUpdateVideoInfoResult_Success_DEFAULT
	}
	return p.Success
}
func (p *VideoServiceUpdateVideoInfoResult) SetSuccess(x interface{}) {
	p.Success = x.(*UpdateVideoInfoResp)
}

func (p *VideoServiceUpdateVideoInfoResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *VideoServiceUpdateVideoInfoResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("VideoServiceUpdateVideoInfoResult(%+v)", *p)
}

var fieldIDToName_VideoServiceUpdateVideoInfoResult = map[int16]string{
	0: "success",
}

type VideoServiceGetVideoStatsArgs struct {
	Req *VideoStatsReq `thrift:"req,1" frugal:"1,default,VideoStatsReq" json:"req"`
}

func NewVideoServiceGetVideoStatsArgs() *VideoServiceGetVideoStatsArgs {
	return &VideoServiceGetVideoStatsArgs{}
}

func (p *VideoServiceGetVideoStatsArgs) InitDefault() {
}

var VideoServiceGetVideoStatsArgs_Req_DEFAULT *VideoStatsReq

func (p *VideoServiceGetVideoStatsArgs) GetReq() (v *VideoStatsReq) {
	if !p.IsSetReq() {
		return VideoServiceGetVideoStatsArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *VideoServiceGetVideoStatsArgs) SetReq(val *VideoStatsReq) {
	p.Req = val
}

func (p *VideoServiceGetVideoStatsArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *VideoServiceGetVideoStatsArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("VideoServiceGetVideoStatsArgs(%+v)", *p)
}

var fieldIDToName_VideoServiceGetVideoStatsArgs = map[int16]string{
	1: "req",
}

type VideoServiceGetVideoStatsResult struct {
	Success *VideoStatsResp `thrift:"success,0,optional" frugal:"0,optional,VideoStatsResp" json:"success,omitempty"`
}

func NewVideoServiceGetVideoStatsResult() *VideoServiceGetVideoStatsResult {
	return &VideoServiceGetVideoStatsResult{}
}

func (p *VideoServiceGetVideoStatsResult) InitDefault() {
}

var VideoServiceGetVideoStatsResult_Success_DEFAULT *VideoStatsResp

func (p *VideoServiceGetVideoStatsResult) GetSuccess() (v *VideoStatsResp) {
	if !p.IsSetSuccess() {
		return VideoServiceGetVideoStatsResult_Success_DEFAULT
	}
	return p.Success
}
func (p *VideoServiceGetVideoStatsResult) SetSuccess(x interface{}) {
	p.Success = x.(*VideoStatsResp)
}

func (p *VideoServiceGetVideoStatsResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *VideoServiceGetVideoStatsResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("VideoServiceGetVideoStatsResult(%+v)", *p)
}

var fieldIDToName_VideoServiceGetVideoStatsResult = map[int16]string{
	0: "success",
}

type VideoServiceGetHotVideosArgs struct {
	Req *HotVideoReq `thrift:"req,1" frugal:"1,default,HotVideoReq" json:"req"`
}

func NewVideoServiceGetHotVideosArgs() *VideoServiceGetHotVideosArgs {
	return &VideoServiceGetHotVideosArgs{}
}

func (p *VideoServiceGetHotVideosArgs) InitDefault() {
}

var VideoServiceGetHotVideosArgs_Req_DEFAULT *HotVideoReq

func (p *VideoServiceGetHotVideosArgs) GetReq() (v *HotVideoReq) {
	if !p.IsSetReq() {
		return VideoServiceGetHotVideosArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *VideoServiceGetHotVideosArgs) SetReq(val *HotVideoReq) {
	p.Req = val
}

func (p *VideoServiceGetHotVideosArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *VideoServiceGetHotVideosArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("VideoServiceGetHotVideosArgs(%+v)", *p)
}

var fieldIDToName_VideoServiceGetHotVideosArgs = map[int16]string{
	1: "req",
}

type VideoServiceGetHotVideosResult struct {
	Success *HotVideoResp `thrift:"success,0,optional" frugal:"0,optional,HotVideoResp" json:"success,omitempty"`
}

func NewVideoServiceGetHotVideosResult() *VideoServiceGetHotVideosResult {
	return &VideoServiceGetHotVideosResult{}
}

func (p *VideoServiceGetHotVideosResult) InitDefault() {
}

var VideoServiceGetHotVideosResult_Success_DEFAULT *HotVideoResp

func (p *VideoServiceGetHotVideosResult) GetSuccess() (v *HotVideoResp) {
	if !p.IsSetSuccess() {
		return VideoServiceGetHotVideosResult_Success_DEFAULT
	}
	return p.Success
}
func (p *VideoServiceGetHotVideosResult) SetSuccess(x interface{}) {
	p.Success = x.(*HotVideoResp)
}

func (p *VideoServiceGetHotVideosResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *VideoServiceGetHotVideosResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("VideoServiceGetHotVideosResult(%+v)", *p)
}

var fieldIDToName_VideoServiceGetHotVideosResult = map[int16]string{
	0: "success",
}
