// Code generated by thriftgo (0.4.3). DO NOT EDIT.

package recommend

import (
	"context"
	"fmt"
	"shortvideo/kitex_gen/common"
)

type GetRecommendVideosReq struct {
	UserId   int64  `thrift:"userId,1" frugal:"1,default,i64" json:"userId"`
	PageSize int32  `thrift:"pageSize,2" frugal:"2,default,i32" json:"pageSize"`
	Offset   *int64 `thrift:"offset,3,optional" frugal:"3,optional,i64" json:"offset,omitempty"`
}

func NewGetRecommendVideosReq() *GetRecommendVideosReq {
	return &GetRecommendVideosReq{}
}

func (p *GetRecommendVideosReq) InitDefault() {
}

func (p *GetRecommendVideosReq) GetUserId() (v int64) {
	return p.UserId
}

func (p *GetRecommendVideosReq) GetPageSize() (v int32) {
	return p.PageSize
}

var GetRecommendVideosReq_Offset_DEFAULT int64

func (p *GetRecommendVideosReq) GetOffset() (v int64) {
	if !p.IsSetOffset() {
		return GetRecommendVideosReq_Offset_DEFAULT
	}
	return *p.Offset
}
func (p *GetRecommendVideosReq) SetUserId(val int64) {
	p.UserId = val
}
func (p *GetRecommendVideosReq) SetPageSize(val int32) {
	p.PageSize = val
}
func (p *GetRecommendVideosReq) SetOffset(val *int64) {
	p.Offset = val
}

func (p *GetRecommendVideosReq) IsSetOffset() bool {
	return p.Offset != nil
}

func (p *GetRecommendVideosReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetRecommendVideosReq(%+v)", *p)
}

var fieldIDToName_GetRecommendVideosReq = map[int16]string{
	1: "userId",
	2: "pageSize",
	3: "offset",
}

type GetRecommendVideosResp struct {
	BaseResp   *common.BaseResp `thrift:"BaseResp,1" frugal:"1,default,common.BaseResp" json:"BaseResp"`
	Videos     []*common.Video  `thrift:"videos,2" frugal:"2,default,list<common.Video>" json:"videos"`
	NextOffset int64            `thrift:"nextOffset,3" frugal:"3,default,i64" json:"nextOffset"`
}

func NewGetRecommendVideosResp() *GetRecommendVideosResp {
	return &GetRecommendVideosResp{}
}

func (p *GetRecommendVideosResp) InitDefault() {
}

var GetRecommendVideosResp_BaseResp_DEFAULT *common.BaseResp

func (p *GetRecommendVideosResp) GetBaseResp() (v *common.BaseResp) {
	if !p.IsSetBaseResp() {
		return GetRecommendVideosResp_BaseResp_DEFAULT
	}
	return p.BaseResp
}

func (p *GetRecommendVideosResp) GetVideos() (v []*common.Video) {
	return p.Videos
}

func (p *GetRecommendVideosResp) GetNextOffset() (v int64) {
	return p.NextOffset
}
func (p *GetRecommendVideosResp) SetBaseResp(val *common.BaseResp) {
	p.BaseResp = val
}
func (p *GetRecommendVideosResp) SetVideos(val []*common.Video) {
	p.Videos = val
}
func (p *GetRecommendVideosResp) SetNextOffset(val int64) {
	p.NextOffset = val
}

func (p *GetRecommendVideosResp) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *GetRecommendVideosResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetRecommendVideosResp(%+v)", *p)
}

var fieldIDToName_GetRecommendVideosResp = map[int16]string{
	1: "BaseResp",
	2: "videos",
	3: "nextOffset",
}

type GetRecommendUsersReq struct {
	UserId int64 `thrift:"userId,1" frugal:"1,default,i64" json:"userId"`
	Count  int32 `thrift:"count,2" frugal:"2,default,i32" json:"count"`
}

func NewGetRecommendUsersReq() *GetRecommendUsersReq {
	return &GetRecommendUsersReq{}
}

func (p *GetRecommendUsersReq) InitDefault() {
}

func (p *GetRecommendUsersReq) GetUserId() (v int64) {
	return p.UserId
}

func (p *GetRecommendUsersReq) GetCount() (v int32) {
	return p.Count
}
func (p *GetRecommendUsersReq) SetUserId(val int64) {
	p.UserId = val
}
func (p *GetRecommendUsersReq) SetCount(val int32) {
	p.Count = val
}

func (p *GetRecommendUsersReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetRecommendUsersReq(%+v)", *p)
}

var fieldIDToName_GetRecommendUsersReq = map[int16]string{
	1: "userId",
	2: "count",
}

type GetRecommendUsersResp struct {
	BaseResp *common.BaseResp `thrift:"BaseResp,1" frugal:"1,default,common.BaseResp" json:"BaseResp"`
	Users    []*common.User   `thrift:"users,2" frugal:"2,default,list<common.User>" json:"users"`
}

func NewGetRecommendUsersResp() *GetRecommendUsersResp {
	return &GetRecommendUsersResp{}
}

func (p *GetRecommendUsersResp) InitDefault() {
}

var GetRecommendUsersResp_BaseResp_DEFAULT *common.BaseResp

func (p *GetRecommendUsersResp) GetBaseResp() (v *common.BaseResp) {
	if !p.IsSetBaseResp() {
		return GetRecommendUsersResp_BaseResp_DEFAULT
	}
	return p.BaseResp
}

func (p *GetRecommendUsersResp) GetUsers() (v []*common.User) {
	return p.Users
}
func (p *GetRecommendUsersResp) SetBaseResp(val *common.BaseResp) {
	p.BaseResp = val
}
func (p *GetRecommendUsersResp) SetUsers(val []*common.User) {
	p.Users = val
}

func (p *GetRecommendUsersResp) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *GetRecommendUsersResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetRecommendUsersResp(%+v)", *p)
}

var fieldIDToName_GetRecommendUsersResp = map[int16]string{
	1: "BaseResp",
	2: "users",
}

type UserActionReq struct {
	UserId     int64    `thrift:"userId,1" frugal:"1,default,i64" json:"userId"`
	ItemId     int64    `thrift:"itemId,2" frugal:"2,default,i64" json:"itemId"`
	ItemType   string   `thrift:"itemType,3" frugal:"3,default,string" json:"itemType"`
	ActionType string   `thrift:"actionType,4" frugal:"4,default,string" json:"actionType"`
	Duration   *int32   `thrift:"duration,5,optional" frugal:"5,optional,i32" json:"duration,omitempty"`
	Score      *float64 `thrift:"score,6,optional" frugal:"6,optional,double" json:"score,omitempty"`
	Timestamp  string   `thrift:"timestamp,7" frugal:"7,default,string" json:"timestamp"`
}

func NewUserActionReq() *UserActionReq {
	return &UserActionReq{}
}

func (p *UserActionReq) InitDefault() {
}

func (p *UserActionReq) GetUserId() (v int64) {
	return p.UserId
}

func (p *UserActionReq) GetItemId() (v int64) {
	return p.ItemId
}

func (p *UserActionReq) GetItemType() (v string) {
	return p.ItemType
}

func (p *UserActionReq) GetActionType() (v string) {
	return p.ActionType
}

var UserActionReq_Duration_DEFAULT int32

func (p *UserActionReq) GetDuration() (v int32) {
	if !p.IsSetDuration() {
		return UserActionReq_Duration_DEFAULT
	}
	return *p.Duration
}

var UserActionReq_Score_DEFAULT float64

func (p *UserActionReq) GetScore() (v float64) {
	if !p.IsSetScore() {
		return UserActionReq_Score_DEFAULT
	}
	return *p.Score
}

func (p *UserActionReq) GetTimestamp() (v string) {
	return p.Timestamp
}
func (p *UserActionReq) SetUserId(val int64) {
	p.UserId = val
}
func (p *UserActionReq) SetItemId(val int64) {
	p.ItemId = val
}
func (p *UserActionReq) SetItemType(val string) {
	p.ItemType = val
}
func (p *UserActionReq) SetActionType(val string) {
	p.ActionType = val
}
func (p *UserActionReq) SetDuration(val *int32) {
	p.Duration = val
}
func (p *UserActionReq) SetScore(val *float64) {
	p.Score = val
}
func (p *UserActionReq) SetTimestamp(val string) {
	p.Timestamp = val
}

func (p *UserActionReq) IsSetDuration() bool {
	return p.Duration != nil
}

func (p *UserActionReq) IsSetScore() bool {
	return p.Score != nil
}

func (p *UserActionReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserActionReq(%+v)", *p)
}

var fieldIDToName_UserActionReq = map[int16]string{
	1: "userId",
	2: "itemId",
	3: "itemType",
	4: "actionType",
	5: "duration",
	6: "score",
	7: "timestamp",
}

type UserActionResp struct {
	BaseResp *common.BaseResp `thrift:"BaseResp,1" frugal:"1,default,common.BaseResp" json:"BaseResp"`
}

func NewUserActionResp() *UserActionResp {
	return &UserActionResp{}
}

func (p *UserActionResp) InitDefault() {
}

var UserActionResp_BaseResp_DEFAULT *common.BaseResp

func (p *UserActionResp) GetBaseResp() (v *common.BaseResp) {
	if !p.IsSetBaseResp() {
		return UserActionResp_BaseResp_DEFAULT
	}
	return p.BaseResp
}
func (p *UserActionResp) SetBaseResp(val *common.BaseResp) {
	p.BaseResp = val
}

func (p *UserActionResp) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *UserActionResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserActionResp(%+v)", *p)
}

var fieldIDToName_UserActionResp = map[int16]string{
	1: "BaseResp",
}

type GetHotTagsReq struct {
	Count int32 `thrift:"count,1" frugal:"1,default,i32" json:"count"`
}

func NewGetHotTagsReq() *GetHotTagsReq {
	return &GetHotTagsReq{}
}

func (p *GetHotTagsReq) InitDefault() {
}

func (p *GetHotTagsReq) GetCount() (v int32) {
	return p.Count
}
func (p *GetHotTagsReq) SetCount(val int32) {
	p.Count = val
}

func (p *GetHotTagsReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetHotTagsReq(%+v)", *p)
}

var fieldIDToName_GetHotTagsReq = map[int16]string{
	1: "count",
}

type TagInfo struct {
	TagName    string `thrift:"tagName,1" frugal:"1,default,string" json:"tagName"`
	VideoCount int64  `thrift:"videoCount,2" frugal:"2,default,i64" json:"videoCount"`
	ViewCount  int64  `thrift:"viewCount,3" frugal:"3,default,i64" json:"viewCount"`
}

func NewTagInfo() *TagInfo {
	return &TagInfo{}
}

func (p *TagInfo) InitDefault() {
}

func (p *TagInfo) GetTagName() (v string) {
	return p.TagName
}

func (p *TagInfo) GetVideoCount() (v int64) {
	return p.VideoCount
}

func (p *TagInfo) GetViewCount() (v int64) {
	return p.ViewCount
}
func (p *TagInfo) SetTagName(val string) {
	p.TagName = val
}
func (p *TagInfo) SetVideoCount(val int64) {
	p.VideoCount = val
}
func (p *TagInfo) SetViewCount(val int64) {
	p.ViewCount = val
}

func (p *TagInfo) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("TagInfo(%+v)", *p)
}

var fieldIDToName_TagInfo = map[int16]string{
	1: "tagName",
	2: "videoCount",
	3: "viewCount",
}

type GetHotTagsResp struct {
	BaseResp *common.BaseResp `thrift:"BaseResp,1" frugal:"1,default,common.BaseResp" json:"BaseResp"`
	Tags     []*TagInfo       `thrift:"tags,2" frugal:"2,default,list<TagInfo>" json:"tags"`
}

func NewGetHotTagsResp() *GetHotTagsResp {
	return &GetHotTagsResp{}
}

func (p *GetHotTagsResp) InitDefault() {
}

var GetHotTagsResp_BaseResp_DEFAULT *common.BaseResp

func (p *GetHotTagsResp) GetBaseResp() (v *common.BaseResp) {
	if !p.IsSetBaseResp() {
		return GetHotTagsResp_BaseResp_DEFAULT
	}
	return p.BaseResp
}

func (p *GetHotTagsResp) GetTags() (v []*TagInfo) {
	return p.Tags
}
func (p *GetHotTagsResp) SetBaseResp(val *common.BaseResp) {
	p.BaseResp = val
}
func (p *GetHotTagsResp) SetTags(val []*TagInfo) {
	p.Tags = val
}

func (p *GetHotTagsResp) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *GetHotTagsResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetHotTagsResp(%+v)", *p)
}

var fieldIDToName_GetHotTagsResp = map[int16]string{
	1: "BaseResp",
	2: "tags",
}

type GetTagVideosReq struct {
	Tag      string `thrift:"tag,1" frugal:"1,default,string" json:"tag"`
	UserId   int64  `thrift:"userId,2" frugal:"2,default,i64" json:"userId"`
	PageSize int32  `thrift:"pageSize,3" frugal:"3,default,i32" json:"pageSize"`
}

func NewGetTagVideosReq() *GetTagVideosReq {
	return &GetTagVideosReq{}
}

func (p *GetTagVideosReq) InitDefault() {
}

func (p *GetTagVideosReq) GetTag() (v string) {
	return p.Tag
}

func (p *GetTagVideosReq) GetUserId() (v int64) {
	return p.UserId
}

func (p *GetTagVideosReq) GetPageSize() (v int32) {
	return p.PageSize
}
func (p *GetTagVideosReq) SetTag(val string) {
	p.Tag = val
}
func (p *GetTagVideosReq) SetUserId(val int64) {
	p.UserId = val
}
func (p *GetTagVideosReq) SetPageSize(val int32) {
	p.PageSize = val
}

func (p *GetTagVideosReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetTagVideosReq(%+v)", *p)
}

var fieldIDToName_GetTagVideosReq = map[int16]string{
	1: "tag",
	2: "userId",
	3: "pageSize",
}

type GetTagVideosResp struct {
	BaseResp *common.BaseResp `thrift:"BaseResp,1" frugal:"1,default,common.BaseResp" json:"BaseResp"`
	Videos   []*common.Video  `thrift:"videos,2" frugal:"2,default,list<common.Video>" json:"videos"`
}

func NewGetTagVideosResp() *GetTagVideosResp {
	return &GetTagVideosResp{}
}

func (p *GetTagVideosResp) InitDefault() {
}

var GetTagVideosResp_BaseResp_DEFAULT *common.BaseResp

func (p *GetTagVideosResp) GetBaseResp() (v *common.BaseResp) {
	if !p.IsSetBaseResp() {
		return GetTagVideosResp_BaseResp_DEFAULT
	}
	return p.BaseResp
}

func (p *GetTagVideosResp) GetVideos() (v []*common.Video) {
	return p.Videos
}
func (p *GetTagVideosResp) SetBaseResp(val *common.BaseResp) {
	p.BaseResp = val
}
func (p *GetTagVideosResp) SetVideos(val []*common.Video) {
	p.Videos = val
}

func (p *GetTagVideosResp) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *GetTagVideosResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetTagVideosResp(%+v)", *p)
}

var fieldIDToName_GetTagVideosResp = map[int16]string{
	1: "BaseResp",
	2: "videos",
}

type GetPersonalizedFeedReq struct {
	UserId      int64  `thrift:"userId,1" frugal:"1,default,i64" json:"userId"`
	PageSize    int32  `thrift:"pageSize,2" frugal:"2,default,i32" json:"pageSize"`
	LastVideoId *int64 `thrift:"lastVideoId,3,optional" frugal:"3,optional,i64" json:"lastVideoId,omitempty"`
}

func NewGetPersonalizedFeedReq() *GetPersonalizedFeedReq {
	return &GetPersonalizedFeedReq{}
}

func (p *GetPersonalizedFeedReq) InitDefault() {
}

func (p *GetPersonalizedFeedReq) GetUserId() (v int64) {
	return p.UserId
}

func (p *GetPersonalizedFeedReq) GetPageSize() (v int32) {
	return p.PageSize
}

var GetPersonalizedFeedReq_LastVideoId_DEFAULT int64

func (p *GetPersonalizedFeedReq) GetLastVideoId() (v int64) {
	if !p.IsSetLastVideoId() {
		return GetPersonalizedFeedReq_LastVideoId_DEFAULT
	}
	return *p.LastVideoId
}
func (p *GetPersonalizedFeedReq) SetUserId(val int64) {
	p.UserId = val
}
func (p *GetPersonalizedFeedReq) SetPageSize(val int32) {
	p.PageSize = val
}
func (p *GetPersonalizedFeedReq) SetLastVideoId(val *int64) {
	p.LastVideoId = val
}

func (p *GetPersonalizedFeedReq) IsSetLastVideoId() bool {
	return p.LastVideoId != nil
}

func (p *GetPersonalizedFeedReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetPersonalizedFeedReq(%+v)", *p)
}

var fieldIDToName_GetPersonalizedFeedReq = map[int16]string{
	1: "userId",
	2: "pageSize",
	3: "lastVideoId",
}

type GetPersonalizedFeedResp struct {
	BaseResp        *common.BaseResp `thrift:"BaseResp,1" frugal:"1,default,common.BaseResp" json:"BaseResp"`
	Videos          []*common.Video  `thrift:"videos,2" frugal:"2,default,list<common.Video>" json:"videos"`
	NextLastVideoId int64            `thrift:"nextLastVideoId,3" frugal:"3,default,i64" json:"nextLastVideoId"`
}

func NewGetPersonalizedFeedResp() *GetPersonalizedFeedResp {
	return &GetPersonalizedFeedResp{}
}

func (p *GetPersonalizedFeedResp) InitDefault() {
}

var GetPersonalizedFeedResp_BaseResp_DEFAULT *common.BaseResp

func (p *GetPersonalizedFeedResp) GetBaseResp() (v *common.BaseResp) {
	if !p.IsSetBaseResp() {
		return GetPersonalizedFeedResp_BaseResp_DEFAULT
	}
	return p.BaseResp
}

func (p *GetPersonalizedFeedResp) GetVideos() (v []*common.Video) {
	return p.Videos
}

func (p *GetPersonalizedFeedResp) GetNextLastVideoId() (v int64) {
	return p.NextLastVideoId
}
func (p *GetPersonalizedFeedResp) SetBaseResp(val *common.BaseResp) {
	p.BaseResp = val
}
func (p *GetPersonalizedFeedResp) SetVideos(val []*common.Video) {
	p.Videos = val
}
func (p *GetPersonalizedFeedResp) SetNextLastVideoId(val int64) {
	p.NextLastVideoId = val
}

func (p *GetPersonalizedFeedResp) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *GetPersonalizedFeedResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetPersonalizedFeedResp(%+v)", *p)
}

var fieldIDToName_GetPersonalizedFeedResp = map[int16]string{
	1: "BaseResp",
	2: "videos",
	3: "nextLastVideoId",
}

type RecommendService interface {
	GetRecommendVideos(ctx context.Context, req *GetRecommendVideosReq) (r *GetRecommendVideosResp, err error)

	GetRecommendUsers(ctx context.Context, req *GetRecommendUsersReq) (r *GetRecommendUsersResp, err error)

	RecordUserAction(ctx context.Context, req *UserActionReq) (r *UserActionResp, err error)

	GetHotTags(ctx context.Context, req *GetHotTagsReq) (r *GetHotTagsResp, err error)

	GetTagVideos(ctx context.Context, req *GetTagVideosReq) (r *GetTagVideosResp, err error)

	GetPersonalizedFeed(ctx context.Context, req *GetPersonalizedFeedReq) (r *GetPersonalizedFeedResp, err error)
}

type RecommendServiceGetRecommendVideosArgs struct {
	Req *GetRecommendVideosReq `thrift:"req,1" frugal:"1,default,GetRecommendVideosReq" json:"req"`
}

func NewRecommendServiceGetRecommendVideosArgs() *RecommendServiceGetRecommendVideosArgs {
	return &RecommendServiceGetRecommendVideosArgs{}
}

func (p *RecommendServiceGetRecommendVideosArgs) InitDefault() {
}

var RecommendServiceGetRecommendVideosArgs_Req_DEFAULT *GetRecommendVideosReq

func (p *RecommendServiceGetRecommendVideosArgs) GetReq() (v *GetRecommendVideosReq) {
	if !p.IsSetReq() {
		return RecommendServiceGetRecommendVideosArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *RecommendServiceGetRecommendVideosArgs) SetReq(val *GetRecommendVideosReq) {
	p.Req = val
}

func (p *RecommendServiceGetRecommendVideosArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *RecommendServiceGetRecommendVideosArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RecommendServiceGetRecommendVideosArgs(%+v)", *p)
}

var fieldIDToName_RecommendServiceGetRecommendVideosArgs = map[int16]string{
	1: "req",
}

type RecommendServiceGetRecommendVideosResult struct {
	Success *GetRecommendVideosResp `thrift:"success,0,optional" frugal:"0,optional,GetRecommendVideosResp" json:"success,omitempty"`
}

func NewRecommendServiceGetRecommendVideosResult() *RecommendServiceGetRecommendVideosResult {
	return &RecommendServiceGetRecommendVideosResult{}
}

func (p *RecommendServiceGetRecommendVideosResult) InitDefault() {
}

var RecommendServiceGetRecommendVideosResult_Success_DEFAULT *GetRecommendVideosResp

func (p *RecommendServiceGetRecommendVideosResult) GetSuccess() (v *GetRecommendVideosResp) {
	if !p.IsSetSuccess() {
		return RecommendServiceGetRecommendVideosResult_Success_DEFAULT
	}
	return p.Success
}
func (p *RecommendServiceGetRecommendVideosResult) SetSuccess(x interface{}) {
	p.Success = x.(*GetRecommendVideosResp)
}

func (p *RecommendServiceGetRecommendVideosResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *RecommendServiceGetRecommendVideosResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RecommendServiceGetRecommendVideosResult(%+v)", *p)
}

var fieldIDToName_RecommendServiceGetRecommendVideosResult = map[int16]string{
	0: "success",
}

type RecommendServiceGetRecommendUsersArgs struct {
	Req *GetRecommendUsersReq `thrift:"req,1" frugal:"1,default,GetRecommendUsersReq" json:"req"`
}

func NewRecommendServiceGetRecommendUsersArgs() *RecommendServiceGetRecommendUsersArgs {
	return &RecommendServiceGetRecommendUsersArgs{}
}

func (p *RecommendServiceGetRecommendUsersArgs) InitDefault() {
}

var RecommendServiceGetRecommendUsersArgs_Req_DEFAULT *GetRecommendUsersReq

func (p *RecommendServiceGetRecommendUsersArgs) GetReq() (v *GetRecommendUsersReq) {
	if !p.IsSetReq() {
		return RecommendServiceGetRecommendUsersArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *RecommendServiceGetRecommendUsersArgs) SetReq(val *GetRecommendUsersReq) {
	p.Req = val
}

func (p *RecommendServiceGetRecommendUsersArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *RecommendServiceGetRecommendUsersArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RecommendServiceGetRecommendUsersArgs(%+v)", *p)
}

var fieldIDToName_RecommendServiceGetRecommendUsersArgs = map[int16]string{
	1: "req",
}

type RecommendServiceGetRecommendUsersResult struct {
	Success *GetRecommendUsersResp `thrift:"success,0,optional" frugal:"0,optional,GetRecommendUsersResp" json:"success,omitempty"`
}

func NewRecommendServiceGetRecommendUsersResult() *RecommendServiceGetRecommendUsersResult {
	return &RecommendServiceGetRecommendUsersResult{}
}

func (p *RecommendServiceGetRecommendUsersResult) InitDefault() {
}

var RecommendServiceGetRecommendUsersResult_Success_DEFAULT *GetRecommendUsersResp

func (p *RecommendServiceGetRecommendUsersResult) GetSuccess() (v *GetRecommendUsersResp) {
	if !p.IsSetSuccess() {
		return RecommendServiceGetRecommendUsersResult_Success_DEFAULT
	}
	return p.Success
}
func (p *RecommendServiceGetRecommendUsersResult) SetSuccess(x interface{}) {
	p.Success = x.(*GetRecommendUsersResp)
}

func (p *RecommendServiceGetRecommendUsersResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *RecommendServiceGetRecommendUsersResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RecommendServiceGetRecommendUsersResult(%+v)", *p)
}

var fieldIDToName_RecommendServiceGetRecommendUsersResult = map[int16]string{
	0: "success",
}

type RecommendServiceRecordUserActionArgs struct {
	Req *UserActionReq `thrift:"req,1" frugal:"1,default,UserActionReq" json:"req"`
}

func NewRecommendServiceRecordUserActionArgs() *RecommendServiceRecordUserActionArgs {
	return &RecommendServiceRecordUserActionArgs{}
}

func (p *RecommendServiceRecordUserActionArgs) InitDefault() {
}

var RecommendServiceRecordUserActionArgs_Req_DEFAULT *UserActionReq

func (p *RecommendServiceRecordUserActionArgs) GetReq() (v *UserActionReq) {
	if !p.IsSetReq() {
		return RecommendServiceRecordUserActionArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *RecommendServiceRecordUserActionArgs) SetReq(val *UserActionReq) {
	p.Req = val
}

func (p *RecommendServiceRecordUserActionArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *RecommendServiceRecordUserActionArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RecommendServiceRecordUserActionArgs(%+v)", *p)
}

var fieldIDToName_RecommendServiceRecordUserActionArgs = map[int16]string{
	1: "req",
}

type RecommendServiceRecordUserActionResult struct {
	Success *UserActionResp `thrift:"success,0,optional" frugal:"0,optional,UserActionResp" json:"success,omitempty"`
}

func NewRecommendServiceRecordUserActionResult() *RecommendServiceRecordUserActionResult {
	return &RecommendServiceRecordUserActionResult{}
}

func (p *RecommendServiceRecordUserActionResult) InitDefault() {
}

var RecommendServiceRecordUserActionResult_Success_DEFAULT *UserActionResp

func (p *RecommendServiceRecordUserActionResult) GetSuccess() (v *UserActionResp) {
	if !p.IsSetSuccess() {
		return RecommendServiceRecordUserActionResult_Success_DEFAULT
	}
	return p.Success
}
func (p *RecommendServiceRecordUserActionResult) SetSuccess(x interface{}) {
	p.Success = x.(*UserActionResp)
}

func (p *RecommendServiceRecordUserActionResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *RecommendServiceRecordUserActionResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RecommendServiceRecordUserActionResult(%+v)", *p)
}

var fieldIDToName_RecommendServiceRecordUserActionResult = map[int16]string{
	0: "success",
}

type RecommendServiceGetHotTagsArgs struct {
	Req *GetHotTagsReq `thrift:"req,1" frugal:"1,default,GetHotTagsReq" json:"req"`
}

func NewRecommendServiceGetHotTagsArgs() *RecommendServiceGetHotTagsArgs {
	return &RecommendServiceGetHotTagsArgs{}
}

func (p *RecommendServiceGetHotTagsArgs) InitDefault() {
}

var RecommendServiceGetHotTagsArgs_Req_DEFAULT *GetHotTagsReq

func (p *RecommendServiceGetHotTagsArgs) GetReq() (v *GetHotTagsReq) {
	if !p.IsSetReq() {
		return RecommendServiceGetHotTagsArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *RecommendServiceGetHotTagsArgs) SetReq(val *GetHotTagsReq) {
	p.Req = val
}

func (p *RecommendServiceGetHotTagsArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *RecommendServiceGetHotTagsArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RecommendServiceGetHotTagsArgs(%+v)", *p)
}

var fieldIDToName_RecommendServiceGetHotTagsArgs = map[int16]string{
	1: "req",
}

type RecommendServiceGetHotTagsResult struct {
	Success *GetHotTagsResp `thrift:"success,0,optional" frugal:"0,optional,GetHotTagsResp" json:"success,omitempty"`
}

func NewRecommendServiceGetHotTagsResult() *RecommendServiceGetHotTagsResult {
	return &RecommendServiceGetHotTagsResult{}
}

func (p *RecommendServiceGetHotTagsResult) InitDefault() {
}

var RecommendServiceGetHotTagsResult_Success_DEFAULT *GetHotTagsResp

func (p *RecommendServiceGetHotTagsResult) GetSuccess() (v *GetHotTagsResp) {
	if !p.IsSetSuccess() {
		return RecommendServiceGetHotTagsResult_Success_DEFAULT
	}
	return p.Success
}
func (p *RecommendServiceGetHotTagsResult) SetSuccess(x interface{}) {
	p.Success = x.(*GetHotTagsResp)
}

func (p *RecommendServiceGetHotTagsResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *RecommendServiceGetHotTagsResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RecommendServiceGetHotTagsResult(%+v)", *p)
}

var fieldIDToName_RecommendServiceGetHotTagsResult = map[int16]string{
	0: "success",
}

type RecommendServiceGetTagVideosArgs struct {
	Req *GetTagVideosReq `thrift:"req,1" frugal:"1,default,GetTagVideosReq" json:"req"`
}

func NewRecommendServiceGetTagVideosArgs() *RecommendServiceGetTagVideosArgs {
	return &RecommendServiceGetTagVideosArgs{}
}

func (p *RecommendServiceGetTagVideosArgs) InitDefault() {
}

var RecommendServiceGetTagVideosArgs_Req_DEFAULT *GetTagVideosReq

func (p *RecommendServiceGetTagVideosArgs) GetReq() (v *GetTagVideosReq) {
	if !p.IsSetReq() {
		return RecommendServiceGetTagVideosArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *RecommendServiceGetTagVideosArgs) SetReq(val *GetTagVideosReq) {
	p.Req = val
}

func (p *RecommendServiceGetTagVideosArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *RecommendServiceGetTagVideosArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RecommendServiceGetTagVideosArgs(%+v)", *p)
}

var fieldIDToName_RecommendServiceGetTagVideosArgs = map[int16]string{
	1: "req",
}

type RecommendServiceGetTagVideosResult struct {
	Success *GetTagVideosResp `thrift:"success,0,optional" frugal:"0,optional,GetTagVideosResp" json:"success,omitempty"`
}

func NewRecommendServiceGetTagVideosResult() *RecommendServiceGetTagVideosResult {
	return &RecommendServiceGetTagVideosResult{}
}

func (p *RecommendServiceGetTagVideosResult) InitDefault() {
}

var RecommendServiceGetTagVideosResult_Success_DEFAULT *GetTagVideosResp

func (p *RecommendServiceGetTagVideosResult) GetSuccess() (v *GetTagVideosResp) {
	if !p.IsSetSuccess() {
		return RecommendServiceGetTagVideosResult_Success_DEFAULT
	}
	return p.Success
}
func (p *RecommendServiceGetTagVideosResult) SetSuccess(x interface{}) {
	p.Success = x.(*GetTagVideosResp)
}

func (p *RecommendServiceGetTagVideosResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *RecommendServiceGetTagVideosResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RecommendServiceGetTagVideosResult(%+v)", *p)
}

var fieldIDToName_RecommendServiceGetTagVideosResult = map[int16]string{
	0: "success",
}

type RecommendServiceGetPersonalizedFeedArgs struct {
	Req *GetPersonalizedFeedReq `thrift:"req,1" frugal:"1,default,GetPersonalizedFeedReq" json:"req"`
}

func NewRecommendServiceGetPersonalizedFeedArgs() *RecommendServiceGetPersonalizedFeedArgs {
	return &RecommendServiceGetPersonalizedFeedArgs{}
}

func (p *RecommendServiceGetPersonalizedFeedArgs) InitDefault() {
}

var RecommendServiceGetPersonalizedFeedArgs_Req_DEFAULT *GetPersonalizedFeedReq

func (p *RecommendServiceGetPersonalizedFeedArgs) GetReq() (v *GetPersonalizedFeedReq) {
	if !p.IsSetReq() {
		return RecommendServiceGetPersonalizedFeedArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *RecommendServiceGetPersonalizedFeedArgs) SetReq(val *GetPersonalizedFeedReq) {
	p.Req = val
}

func (p *RecommendServiceGetPersonalizedFeedArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *RecommendServiceGetPersonalizedFeedArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RecommendServiceGetPersonalizedFeedArgs(%+v)", *p)
}

var fieldIDToName_RecommendServiceGetPersonalizedFeedArgs = map[int16]string{
	1: "req",
}

type RecommendServiceGetPersonalizedFeedResult struct {
	Success *GetPersonalizedFeedResp `thrift:"success,0,optional" frugal:"0,optional,GetPersonalizedFeedResp" json:"success,omitempty"`
}

func NewRecommendServiceGetPersonalizedFeedResult() *RecommendServiceGetPersonalizedFeedResult {
	return &RecommendServiceGetPersonalizedFeedResult{}
}

func (p *RecommendServiceGetPersonalizedFeedResult) InitDefault() {
}

var RecommendServiceGetPersonalizedFeedResult_Success_DEFAULT *GetPersonalizedFeedResp

func (p *RecommendServiceGetPersonalizedFeedResult) GetSuccess() (v *GetPersonalizedFeedResp) {
	if !p.IsSetSuccess() {
		return RecommendServiceGetPersonalizedFeedResult_Success_DEFAULT
	}
	return p.Success
}
func (p *RecommendServiceGetPersonalizedFeedResult) SetSuccess(x interface{}) {
	p.Success = x.(*GetPersonalizedFeedResp)
}

func (p *RecommendServiceGetPersonalizedFeedResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *RecommendServiceGetPersonalizedFeedResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RecommendServiceGetPersonalizedFeedResult(%+v)", *p)
}

var fieldIDToName_RecommendServiceGetPersonalizedFeedResult = map[int16]string{
	0: "success",
}
