// Code generated by thriftgo (0.4.3). DO NOT EDIT.

package common

import (
	"fmt"
)

type BaseResp struct {
	StatusCode int32   `thrift:"statusCode,1" frugal:"1,default,i32" json:"statusCode"`
	Msg        *string `thrift:"msg,2,optional" frugal:"2,optional,string" json:"msg,omitempty"`
}

func NewBaseResp() *BaseResp {
	return &BaseResp{}
}

func (p *BaseResp) InitDefault() {
}

func (p *BaseResp) GetStatusCode() (v int32) {
	return p.StatusCode
}

var BaseResp_Msg_DEFAULT string

func (p *BaseResp) GetMsg() (v string) {
	if !p.IsSetMsg() {
		return BaseResp_Msg_DEFAULT
	}
	return *p.Msg
}
func (p *BaseResp) SetStatusCode(val int32) {
	p.StatusCode = val
}
func (p *BaseResp) SetMsg(val *string) {
	p.Msg = val
}

func (p *BaseResp) IsSetMsg() bool {
	return p.Msg != nil
}

func (p *BaseResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("BaseResp(%+v)", *p)
}

var fieldIDToName_BaseResp = map[int16]string{
	1: "statusCode",
	2: "msg",
}

type User struct {
	Id            int64   `thrift:"id,1" frugal:"1,default,i64" json:"id"`
	Username      string  `thrift:"username,2" frugal:"2,default,string" json:"username"`
	Password      string  `thrift:"password,3" frugal:"3,default,string" json:"password"`
	Avatar        *string `thrift:"avatar,4,optional" frugal:"4,optional,string" json:"avatar,omitempty"`
	About         *string `thrift:"about,5,optional" frugal:"5,optional,string" json:"about,omitempty"`
	FollowCount   int64   `thrift:"followCount,6" frugal:"6,default,i64" json:"followCount"`
	FollowerCount int64   `thrift:"followerCount,7" frugal:"7,default,i64" json:"followerCount"`
	IsFollow      bool    `thrift:"isFollow,8" frugal:"8,default,bool" json:"isFollow"`
}

func NewUser() *User {
	return &User{}
}

func (p *User) InitDefault() {
}

func (p *User) GetId() (v int64) {
	return p.Id
}

func (p *User) GetUsername() (v string) {
	return p.Username
}

func (p *User) GetPassword() (v string) {
	return p.Password
}

var User_Avatar_DEFAULT string

func (p *User) GetAvatar() (v string) {
	if !p.IsSetAvatar() {
		return User_Avatar_DEFAULT
	}
	return *p.Avatar
}

var User_About_DEFAULT string

func (p *User) GetAbout() (v string) {
	if !p.IsSetAbout() {
		return User_About_DEFAULT
	}
	return *p.About
}

func (p *User) GetFollowCount() (v int64) {
	return p.FollowCount
}

func (p *User) GetFollowerCount() (v int64) {
	return p.FollowerCount
}

func (p *User) GetIsFollow() (v bool) {
	return p.IsFollow
}
func (p *User) SetId(val int64) {
	p.Id = val
}
func (p *User) SetUsername(val string) {
	p.Username = val
}
func (p *User) SetPassword(val string) {
	p.Password = val
}
func (p *User) SetAvatar(val *string) {
	p.Avatar = val
}
func (p *User) SetAbout(val *string) {
	p.About = val
}
func (p *User) SetFollowCount(val int64) {
	p.FollowCount = val
}
func (p *User) SetFollowerCount(val int64) {
	p.FollowerCount = val
}
func (p *User) SetIsFollow(val bool) {
	p.IsFollow = val
}

func (p *User) IsSetAvatar() bool {
	return p.Avatar != nil
}

func (p *User) IsSetAbout() bool {
	return p.About != nil
}

func (p *User) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("User(%+v)", *p)
}

var fieldIDToName_User = map[int16]string{
	1: "id",
	2: "username",
	3: "password",
	4: "avatar",
	5: "about",
	6: "followCount",
	7: "followerCount",
	8: "isFollow",
}

type Video struct {
	Id           int64  `thrift:"id,1" frugal:"1,default,i64" json:"id"`
	AuthorId     int64  `thrift:"authorId,2" frugal:"2,default,i64" json:"authorId"`
	Url          string `thrift:"url,3" frugal:"3,default,string" json:"url"`
	CoverUrl     string `thrift:"coverUrl,4" frugal:"4,default,string" json:"coverUrl"`
	LikeCount    int64  `thrift:"likeCount,5" frugal:"5,default,i64" json:"likeCount"`
	CommentCount int64  `thrift:"commentCount,6" frugal:"6,default,i64" json:"commentCount"`
	IsLike       bool   `thrift:"isLike,7" frugal:"7,default,bool" json:"isLike"`
	Title        string `thrift:"title,8" frugal:"8,default,string" json:"title"`
	PublishTime  int64  `thrift:"publishTime,9" frugal:"9,default,i64" json:"publishTime"`
	Description  string `thrift:"description,10" frugal:"10,default,string" json:"description"`
}

func NewVideo() *Video {
	return &Video{}
}

func (p *Video) InitDefault() {
}

func (p *Video) GetId() (v int64) {
	return p.Id
}

func (p *Video) GetAuthorId() (v int64) {
	return p.AuthorId
}

func (p *Video) GetUrl() (v string) {
	return p.Url
}

func (p *Video) GetCoverUrl() (v string) {
	return p.CoverUrl
}

func (p *Video) GetLikeCount() (v int64) {
	return p.LikeCount
}

func (p *Video) GetCommentCount() (v int64) {
	return p.CommentCount
}

func (p *Video) GetIsLike() (v bool) {
	return p.IsLike
}

func (p *Video) GetTitle() (v string) {
	return p.Title
}

func (p *Video) GetPublishTime() (v int64) {
	return p.PublishTime
}

func (p *Video) GetDescription() (v string) {
	return p.Description
}
func (p *Video) SetId(val int64) {
	p.Id = val
}
func (p *Video) SetAuthorId(val int64) {
	p.AuthorId = val
}
func (p *Video) SetUrl(val string) {
	p.Url = val
}
func (p *Video) SetCoverUrl(val string) {
	p.CoverUrl = val
}
func (p *Video) SetLikeCount(val int64) {
	p.LikeCount = val
}
func (p *Video) SetCommentCount(val int64) {
	p.CommentCount = val
}
func (p *Video) SetIsLike(val bool) {
	p.IsLike = val
}
func (p *Video) SetTitle(val string) {
	p.Title = val
}
func (p *Video) SetPublishTime(val int64) {
	p.PublishTime = val
}
func (p *Video) SetDescription(val string) {
	p.Description = val
}

func (p *Video) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("Video(%+v)", *p)
}

var fieldIDToName_Video = map[int16]string{
	1:  "id",
	2:  "authorId",
	3:  "url",
	4:  "coverUrl",
	5:  "likeCount",
	6:  "commentCount",
	7:  "isLike",
	8:  "title",
	9:  "publishTime",
	10: "description",
}

type Comment struct {
	Id         int64  `thrift:"id,1" frugal:"1,default,i64" json:"id"`
	UserId     int64  `thrift:"userId,2" frugal:"2,default,i64" json:"userId"`
	VideoId    int64  `thrift:"videoId,3" frugal:"3,default,i64" json:"videoId"`
	Content    string `thrift:"content,4" frugal:"4,default,string" json:"content"`
	CreateTime string `thrift:"createTime,5" frugal:"5,default,string" json:"createTime"`
	ReplyToId  int64  `thrift:"replyToId,6" frugal:"6,default,i64" json:"replyToId"`
}

func NewComment() *Comment {
	return &Comment{}
}

func (p *Comment) InitDefault() {
}

func (p *Comment) GetId() (v int64) {
	return p.Id
}

func (p *Comment) GetUserId() (v int64) {
	return p.UserId
}

func (p *Comment) GetVideoId() (v int64) {
	return p.VideoId
}

func (p *Comment) GetContent() (v string) {
	return p.Content
}

func (p *Comment) GetCreateTime() (v string) {
	return p.CreateTime
}

func (p *Comment) GetReplyToId() (v int64) {
	return p.ReplyToId
}
func (p *Comment) SetId(val int64) {
	p.Id = val
}
func (p *Comment) SetUserId(val int64) {
	p.UserId = val
}
func (p *Comment) SetVideoId(val int64) {
	p.VideoId = val
}
func (p *Comment) SetContent(val string) {
	p.Content = val
}
func (p *Comment) SetCreateTime(val string) {
	p.CreateTime = val
}
func (p *Comment) SetReplyToId(val int64) {
	p.ReplyToId = val
}

func (p *Comment) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("Comment(%+v)", *p)
}

var fieldIDToName_Comment = map[int16]string{
	1: "id",
	2: "userId",
	3: "videoId",
	4: "content",
	5: "createTime",
	6: "replyToId",
}

type Message struct {
	Id         int64  `thrift:"id,1" frugal:"1,default,i64" json:"id"`
	ReceiveId  int64  `thrift:"receiveId,2" frugal:"2,default,i64" json:"receiveId"`
	SendId     int64  `thrift:"sendId,3" frugal:"3,default,i64" json:"sendId"`
	Content    string `thrift:"content,4" frugal:"4,default,string" json:"content"`
	CreateTime string `thrift:"createTime,5" frugal:"5,default,string" json:"createTime"`
	IsRead     bool   `thrift:"isRead,6" frugal:"6,default,bool" json:"isRead"`
}

func NewMessage() *Message {
	return &Message{}
}

func (p *Message) InitDefault() {
}

func (p *Message) GetId() (v int64) {
	return p.Id
}

func (p *Message) GetReceiveId() (v int64) {
	return p.ReceiveId
}

func (p *Message) GetSendId() (v int64) {
	return p.SendId
}

func (p *Message) GetContent() (v string) {
	return p.Content
}

func (p *Message) GetCreateTime() (v string) {
	return p.CreateTime
}

func (p *Message) GetIsRead() (v bool) {
	return p.IsRead
}
func (p *Message) SetId(val int64) {
	p.Id = val
}
func (p *Message) SetReceiveId(val int64) {
	p.ReceiveId = val
}
func (p *Message) SetSendId(val int64) {
	p.SendId = val
}
func (p *Message) SetContent(val string) {
	p.Content = val
}
func (p *Message) SetCreateTime(val string) {
	p.CreateTime = val
}
func (p *Message) SetIsRead(val bool) {
	p.IsRead = val
}

func (p *Message) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("Message(%+v)", *p)
}

var fieldIDToName_Message = map[int16]string{
	1: "id",
	2: "receiveId",
	3: "sendId",
	4: "content",
	5: "createTime",
	6: "isRead",
}

type LiveRoom struct {
	Id          int64  `thrift:"id,1" frugal:"1,default,i64" json:"id"`
	HostId      int64  `thrift:"hostId,2" frugal:"2,default,i64" json:"hostId"`
	Title       string `thrift:"title,3" frugal:"3,default,string" json:"title"`
	CoverUrl    string `thrift:"coverUrl,4" frugal:"4,default,string" json:"coverUrl"`
	RtmpUrl     string `thrift:"rtmpUrl,5" frugal:"5,default,string" json:"rtmpUrl"`
	HlsUrl      string `thrift:"hlsUrl,6" frugal:"6,default,string" json:"hlsUrl"`
	ViewerCount int64  `thrift:"viewerCount,7" frugal:"7,default,i64" json:"viewerCount"`
	IsLive      bool   `thrift:"isLive,8" frugal:"8,default,bool" json:"isLive"`
	CreateTime  string `thrift:"createTime,9" frugal:"9,default,string" json:"createTime"`
}

func NewLiveRoom() *LiveRoom {
	return &LiveRoom{}
}

func (p *LiveRoom) InitDefault() {
}

func (p *LiveRoom) GetId() (v int64) {
	return p.Id
}

func (p *LiveRoom) GetHostId() (v int64) {
	return p.HostId
}

func (p *LiveRoom) GetTitle() (v string) {
	return p.Title
}

func (p *LiveRoom) GetCoverUrl() (v string) {
	return p.CoverUrl
}

func (p *LiveRoom) GetRtmpUrl() (v string) {
	return p.RtmpUrl
}

func (p *LiveRoom) GetHlsUrl() (v string) {
	return p.HlsUrl
}

func (p *LiveRoom) GetViewerCount() (v int64) {
	return p.ViewerCount
}

func (p *LiveRoom) GetIsLive() (v bool) {
	return p.IsLive
}

func (p *LiveRoom) GetCreateTime() (v string) {
	return p.CreateTime
}
func (p *LiveRoom) SetId(val int64) {
	p.Id = val
}
func (p *LiveRoom) SetHostId(val int64) {
	p.HostId = val
}
func (p *LiveRoom) SetTitle(val string) {
	p.Title = val
}
func (p *LiveRoom) SetCoverUrl(val string) {
	p.CoverUrl = val
}
func (p *LiveRoom) SetRtmpUrl(val string) {
	p.RtmpUrl = val
}
func (p *LiveRoom) SetHlsUrl(val string) {
	p.HlsUrl = val
}
func (p *LiveRoom) SetViewerCount(val int64) {
	p.ViewerCount = val
}
func (p *LiveRoom) SetIsLive(val bool) {
	p.IsLive = val
}
func (p *LiveRoom) SetCreateTime(val string) {
	p.CreateTime = val
}

func (p *LiveRoom) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("LiveRoom(%+v)", *p)
}

var fieldIDToName_LiveRoom = map[int16]string{
	1: "id",
	2: "hostId",
	3: "title",
	4: "coverUrl",
	5: "rtmpUrl",
	6: "hlsUrl",
	7: "viewerCount",
	8: "isLive",
	9: "createTime",
}

type Danmu struct {
	Id         int64  `thrift:"id,1" frugal:"1,default,i64" json:"id"`
	UserId     int64  `thrift:"userId,2" frugal:"2,default,i64" json:"userId"`
	LiveId     int64  `thrift:"liveId,3" frugal:"3,default,i64" json:"liveId"`
	Content    string `thrift:"content,4" frugal:"4,default,string" json:"content"`
	Color      string `thrift:"color,5" frugal:"5,default,string" json:"color"`
	CreateTime string `thrift:"createTime,6" frugal:"6,default,string" json:"createTime"`
}

func NewDanmu() *Danmu {
	return &Danmu{}
}

func (p *Danmu) InitDefault() {
}

func (p *Danmu) GetId() (v int64) {
	return p.Id
}

func (p *Danmu) GetUserId() (v int64) {
	return p.UserId
}

func (p *Danmu) GetLiveId() (v int64) {
	return p.LiveId
}

func (p *Danmu) GetContent() (v string) {
	return p.Content
}

func (p *Danmu) GetColor() (v string) {
	return p.Color
}

func (p *Danmu) GetCreateTime() (v string) {
	return p.CreateTime
}
func (p *Danmu) SetId(val int64) {
	p.Id = val
}
func (p *Danmu) SetUserId(val int64) {
	p.UserId = val
}
func (p *Danmu) SetLiveId(val int64) {
	p.LiveId = val
}
func (p *Danmu) SetContent(val string) {
	p.Content = val
}
func (p *Danmu) SetColor(val string) {
	p.Color = val
}
func (p *Danmu) SetCreateTime(val string) {
	p.CreateTime = val
}

func (p *Danmu) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("Danmu(%+v)", *p)
}

var fieldIDToName_Danmu = map[int16]string{
	1: "id",
	2: "userId",
	3: "liveId",
	4: "content",
	5: "color",
	6: "createTime",
}
