// Code generated by thriftgo (0.4.3). DO NOT EDIT.

package social

import (
	"context"
	"fmt"
	"shortvideo/kitex_gen/common"
)

type FollowActionReq struct {
	UserId       int64 `thrift:"userId,1" frugal:"1,default,i64" json:"userId"`
	TargetUserId int64 `thrift:"targetUserId,2" frugal:"2,default,i64" json:"targetUserId"`
	Action       bool  `thrift:"action,3" frugal:"3,default,bool" json:"action"`
}

func NewFollowActionReq() *FollowActionReq {
	return &FollowActionReq{}
}

func (p *FollowActionReq) InitDefault() {
}

func (p *FollowActionReq) GetUserId() (v int64) {
	return p.UserId
}

func (p *FollowActionReq) GetTargetUserId() (v int64) {
	return p.TargetUserId
}

func (p *FollowActionReq) GetAction() (v bool) {
	return p.Action
}
func (p *FollowActionReq) SetUserId(val int64) {
	p.UserId = val
}
func (p *FollowActionReq) SetTargetUserId(val int64) {
	p.TargetUserId = val
}
func (p *FollowActionReq) SetAction(val bool) {
	p.Action = val
}

func (p *FollowActionReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("FollowActionReq(%+v)", *p)
}

var fieldIDToName_FollowActionReq = map[int16]string{
	1: "userId",
	2: "targetUserId",
	3: "action",
}

type FollowActionResp struct {
	BaseResp *common.BaseResp `thrift:"BaseResp,1" frugal:"1,default,common.BaseResp" json:"BaseResp"`
}

func NewFollowActionResp() *FollowActionResp {
	return &FollowActionResp{}
}

func (p *FollowActionResp) InitDefault() {
}

var FollowActionResp_BaseResp_DEFAULT *common.BaseResp

func (p *FollowActionResp) GetBaseResp() (v *common.BaseResp) {
	if !p.IsSetBaseResp() {
		return FollowActionResp_BaseResp_DEFAULT
	}
	return p.BaseResp
}
func (p *FollowActionResp) SetBaseResp(val *common.BaseResp) {
	p.BaseResp = val
}

func (p *FollowActionResp) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *FollowActionResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("FollowActionResp(%+v)", *p)
}

var fieldIDToName_FollowActionResp = map[int16]string{
	1: "BaseResp",
}

type FollowListReq struct {
	UserId        int64 `thrift:"userId,1" frugal:"1,default,i64" json:"userId"`
	CurrentUserId int64 `thrift:"currentUserId,2" frugal:"2,default,i64" json:"currentUserId"`
	Page          int32 `thrift:"page,3" frugal:"3,default,i32" json:"page"`
	PageSize      int32 `thrift:"pageSize,4" frugal:"4,default,i32" json:"pageSize"`
}

func NewFollowListReq() *FollowListReq {
	return &FollowListReq{}
}

func (p *FollowListReq) InitDefault() {
}

func (p *FollowListReq) GetUserId() (v int64) {
	return p.UserId
}

func (p *FollowListReq) GetCurrentUserId() (v int64) {
	return p.CurrentUserId
}

func (p *FollowListReq) GetPage() (v int32) {
	return p.Page
}

func (p *FollowListReq) GetPageSize() (v int32) {
	return p.PageSize
}
func (p *FollowListReq) SetUserId(val int64) {
	p.UserId = val
}
func (p *FollowListReq) SetCurrentUserId(val int64) {
	p.CurrentUserId = val
}
func (p *FollowListReq) SetPage(val int32) {
	p.Page = val
}
func (p *FollowListReq) SetPageSize(val int32) {
	p.PageSize = val
}

func (p *FollowListReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("FollowListReq(%+v)", *p)
}

var fieldIDToName_FollowListReq = map[int16]string{
	1: "userId",
	2: "currentUserId",
	3: "page",
	4: "pageSize",
}

type FollowListResp struct {
	BaseResp   *common.BaseResp `thrift:"BaseResp,1" frugal:"1,default,common.BaseResp" json:"BaseResp"`
	Users      []*common.User   `thrift:"users,2" frugal:"2,default,list<common.User>" json:"users"`
	TotalCount int32            `thrift:"totalCount,3" frugal:"3,default,i32" json:"totalCount"`
}

func NewFollowListResp() *FollowListResp {
	return &FollowListResp{}
}

func (p *FollowListResp) InitDefault() {
}

var FollowListResp_BaseResp_DEFAULT *common.BaseResp

func (p *FollowListResp) GetBaseResp() (v *common.BaseResp) {
	if !p.IsSetBaseResp() {
		return FollowListResp_BaseResp_DEFAULT
	}
	return p.BaseResp
}

func (p *FollowListResp) GetUsers() (v []*common.User) {
	return p.Users
}

func (p *FollowListResp) GetTotalCount() (v int32) {
	return p.TotalCount
}
func (p *FollowListResp) SetBaseResp(val *common.BaseResp) {
	p.BaseResp = val
}
func (p *FollowListResp) SetUsers(val []*common.User) {
	p.Users = val
}
func (p *FollowListResp) SetTotalCount(val int32) {
	p.TotalCount = val
}

func (p *FollowListResp) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *FollowListResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("FollowListResp(%+v)", *p)
}

var fieldIDToName_FollowListResp = map[int16]string{
	1: "BaseResp",
	2: "users",
	3: "totalCount",
}

type FollowerListReq struct {
	UserId        int64 `thrift:"userId,1" frugal:"1,default,i64" json:"userId"`
	CurrentUserId int64 `thrift:"currentUserId,2" frugal:"2,default,i64" json:"currentUserId"`
	Page          int32 `thrift:"page,3" frugal:"3,default,i32" json:"page"`
	PageSize      int32 `thrift:"pageSize,4" frugal:"4,default,i32" json:"pageSize"`
}

func NewFollowerListReq() *FollowerListReq {
	return &FollowerListReq{}
}

func (p *FollowerListReq) InitDefault() {
}

func (p *FollowerListReq) GetUserId() (v int64) {
	return p.UserId
}

func (p *FollowerListReq) GetCurrentUserId() (v int64) {
	return p.CurrentUserId
}

func (p *FollowerListReq) GetPage() (v int32) {
	return p.Page
}

func (p *FollowerListReq) GetPageSize() (v int32) {
	return p.PageSize
}
func (p *FollowerListReq) SetUserId(val int64) {
	p.UserId = val
}
func (p *FollowerListReq) SetCurrentUserId(val int64) {
	p.CurrentUserId = val
}
func (p *FollowerListReq) SetPage(val int32) {
	p.Page = val
}
func (p *FollowerListReq) SetPageSize(val int32) {
	p.PageSize = val
}

func (p *FollowerListReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("FollowerListReq(%+v)", *p)
}

var fieldIDToName_FollowerListReq = map[int16]string{
	1: "userId",
	2: "currentUserId",
	3: "page",
	4: "pageSize",
}

type FollowerListResp struct {
	BaseResp   *common.BaseResp `thrift:"BaseResp,1" frugal:"1,default,common.BaseResp" json:"BaseResp"`
	Users      []*common.User   `thrift:"users,2" frugal:"2,default,list<common.User>" json:"users"`
	TotalCount int32            `thrift:"totalCount,3" frugal:"3,default,i32" json:"totalCount"`
}

func NewFollowerListResp() *FollowerListResp {
	return &FollowerListResp{}
}

func (p *FollowerListResp) InitDefault() {
}

var FollowerListResp_BaseResp_DEFAULT *common.BaseResp

func (p *FollowerListResp) GetBaseResp() (v *common.BaseResp) {
	if !p.IsSetBaseResp() {
		return FollowerListResp_BaseResp_DEFAULT
	}
	return p.BaseResp
}

func (p *FollowerListResp) GetUsers() (v []*common.User) {
	return p.Users
}

func (p *FollowerListResp) GetTotalCount() (v int32) {
	return p.TotalCount
}
func (p *FollowerListResp) SetBaseResp(val *common.BaseResp) {
	p.BaseResp = val
}
func (p *FollowerListResp) SetUsers(val []*common.User) {
	p.Users = val
}
func (p *FollowerListResp) SetTotalCount(val int32) {
	p.TotalCount = val
}

func (p *FollowerListResp) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *FollowerListResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("FollowerListResp(%+v)", *p)
}

var fieldIDToName_FollowerListResp = map[int16]string{
	1: "BaseResp",
	2: "users",
	3: "totalCount",
}

type FriendListReq struct {
	UserId   int64 `thrift:"userId,1" frugal:"1,default,i64" json:"userId"`
	Page     int32 `thrift:"page,2" frugal:"2,default,i32" json:"page"`
	PageSize int32 `thrift:"pageSize,3" frugal:"3,default,i32" json:"pageSize"`
}

func NewFriendListReq() *FriendListReq {
	return &FriendListReq{}
}

func (p *FriendListReq) InitDefault() {
}

func (p *FriendListReq) GetUserId() (v int64) {
	return p.UserId
}

func (p *FriendListReq) GetPage() (v int32) {
	return p.Page
}

func (p *FriendListReq) GetPageSize() (v int32) {
	return p.PageSize
}
func (p *FriendListReq) SetUserId(val int64) {
	p.UserId = val
}
func (p *FriendListReq) SetPage(val int32) {
	p.Page = val
}
func (p *FriendListReq) SetPageSize(val int32) {
	p.PageSize = val
}

func (p *FriendListReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("FriendListReq(%+v)", *p)
}

var fieldIDToName_FriendListReq = map[int16]string{
	1: "userId",
	2: "page",
	3: "pageSize",
}

type FriendListResp struct {
	BaseResp   *common.BaseResp `thrift:"BaseResp,1" frugal:"1,default,common.BaseResp" json:"BaseResp"`
	Users      []*common.User   `thrift:"users,2" frugal:"2,default,list<common.User>" json:"users"`
	TotalCount int32            `thrift:"totalCount,3" frugal:"3,default,i32" json:"totalCount"`
}

func NewFriendListResp() *FriendListResp {
	return &FriendListResp{}
}

func (p *FriendListResp) InitDefault() {
}

var FriendListResp_BaseResp_DEFAULT *common.BaseResp

func (p *FriendListResp) GetBaseResp() (v *common.BaseResp) {
	if !p.IsSetBaseResp() {
		return FriendListResp_BaseResp_DEFAULT
	}
	return p.BaseResp
}

func (p *FriendListResp) GetUsers() (v []*common.User) {
	return p.Users
}

func (p *FriendListResp) GetTotalCount() (v int32) {
	return p.TotalCount
}
func (p *FriendListResp) SetBaseResp(val *common.BaseResp) {
	p.BaseResp = val
}
func (p *FriendListResp) SetUsers(val []*common.User) {
	p.Users = val
}
func (p *FriendListResp) SetTotalCount(val int32) {
	p.TotalCount = val
}

func (p *FriendListResp) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *FriendListResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("FriendListResp(%+v)", *p)
}

var fieldIDToName_FriendListResp = map[int16]string{
	1: "BaseResp",
	2: "users",
	3: "totalCount",
}

type CheckFollowReq struct {
	UserId       int64 `thrift:"userId,1" frugal:"1,default,i64" json:"userId"`
	TargetUserId int64 `thrift:"targetUserId,2" frugal:"2,default,i64" json:"targetUserId"`
}

func NewCheckFollowReq() *CheckFollowReq {
	return &CheckFollowReq{}
}

func (p *CheckFollowReq) InitDefault() {
}

func (p *CheckFollowReq) GetUserId() (v int64) {
	return p.UserId
}

func (p *CheckFollowReq) GetTargetUserId() (v int64) {
	return p.TargetUserId
}
func (p *CheckFollowReq) SetUserId(val int64) {
	p.UserId = val
}
func (p *CheckFollowReq) SetTargetUserId(val int64) {
	p.TargetUserId = val
}

func (p *CheckFollowReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CheckFollowReq(%+v)", *p)
}

var fieldIDToName_CheckFollowReq = map[int16]string{
	1: "userId",
	2: "targetUserId",
}

type CheckFollowResp struct {
	BaseResp    *common.BaseResp `thrift:"BaseResp,1" frugal:"1,default,common.BaseResp" json:"BaseResp"`
	IsFollowing bool             `thrift:"isFollowing,2" frugal:"2,default,bool" json:"isFollowing"`
}

func NewCheckFollowResp() *CheckFollowResp {
	return &CheckFollowResp{}
}

func (p *CheckFollowResp) InitDefault() {
}

var CheckFollowResp_BaseResp_DEFAULT *common.BaseResp

func (p *CheckFollowResp) GetBaseResp() (v *common.BaseResp) {
	if !p.IsSetBaseResp() {
		return CheckFollowResp_BaseResp_DEFAULT
	}
	return p.BaseResp
}

func (p *CheckFollowResp) GetIsFollowing() (v bool) {
	return p.IsFollowing
}
func (p *CheckFollowResp) SetBaseResp(val *common.BaseResp) {
	p.BaseResp = val
}
func (p *CheckFollowResp) SetIsFollowing(val bool) {
	p.IsFollowing = val
}

func (p *CheckFollowResp) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *CheckFollowResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CheckFollowResp(%+v)", *p)
}

var fieldIDToName_CheckFollowResp = map[int16]string{
	1: "BaseResp",
	2: "isFollowing",
}

type CheckMutualFollowReq struct {
	UserId1 int64 `thrift:"userId1,1" frugal:"1,default,i64" json:"userId1"`
	UserId2 int64 `thrift:"userId2,2" frugal:"2,default,i64" json:"userId2"`
}

func NewCheckMutualFollowReq() *CheckMutualFollowReq {
	return &CheckMutualFollowReq{}
}

func (p *CheckMutualFollowReq) InitDefault() {
}

func (p *CheckMutualFollowReq) GetUserId1() (v int64) {
	return p.UserId1
}

func (p *CheckMutualFollowReq) GetUserId2() (v int64) {
	return p.UserId2
}
func (p *CheckMutualFollowReq) SetUserId1(val int64) {
	p.UserId1 = val
}
func (p *CheckMutualFollowReq) SetUserId2(val int64) {
	p.UserId2 = val
}

func (p *CheckMutualFollowReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CheckMutualFollowReq(%+v)", *p)
}

var fieldIDToName_CheckMutualFollowReq = map[int16]string{
	1: "userId1",
	2: "userId2",
}

type CheckMutualFollowResp struct {
	BaseResp       *common.BaseResp `thrift:"BaseResp,1" frugal:"1,default,common.BaseResp" json:"BaseResp"`
	IsMutualFollow bool             `thrift:"isMutualFollow,2" frugal:"2,default,bool" json:"isMutualFollow"`
}

func NewCheckMutualFollowResp() *CheckMutualFollowResp {
	return &CheckMutualFollowResp{}
}

func (p *CheckMutualFollowResp) InitDefault() {
}

var CheckMutualFollowResp_BaseResp_DEFAULT *common.BaseResp

func (p *CheckMutualFollowResp) GetBaseResp() (v *common.BaseResp) {
	if !p.IsSetBaseResp() {
		return CheckMutualFollowResp_BaseResp_DEFAULT
	}
	return p.BaseResp
}

func (p *CheckMutualFollowResp) GetIsMutualFollow() (v bool) {
	return p.IsMutualFollow
}
func (p *CheckMutualFollowResp) SetBaseResp(val *common.BaseResp) {
	p.BaseResp = val
}
func (p *CheckMutualFollowResp) SetIsMutualFollow(val bool) {
	p.IsMutualFollow = val
}

func (p *CheckMutualFollowResp) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *CheckMutualFollowResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CheckMutualFollowResp(%+v)", *p)
}

var fieldIDToName_CheckMutualFollowResp = map[int16]string{
	1: "BaseResp",
	2: "isMutualFollow",
}

type FollowStatsReq struct {
	UserId int64 `thrift:"userId,1" frugal:"1,default,i64" json:"userId"`
}

func NewFollowStatsReq() *FollowStatsReq {
	return &FollowStatsReq{}
}

func (p *FollowStatsReq) InitDefault() {
}

func (p *FollowStatsReq) GetUserId() (v int64) {
	return p.UserId
}
func (p *FollowStatsReq) SetUserId(val int64) {
	p.UserId = val
}

func (p *FollowStatsReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("FollowStatsReq(%+v)", *p)
}

var fieldIDToName_FollowStatsReq = map[int16]string{
	1: "userId",
}

type FollowStats struct {
	UserId        int64 `thrift:"userId,1" frugal:"1,default,i64" json:"userId"`
	FollowCount   int64 `thrift:"followCount,2" frugal:"2,default,i64" json:"followCount"`
	FollowerCount int64 `thrift:"followerCount,3" frugal:"3,default,i64" json:"followerCount"`
	FriendCount   int64 `thrift:"friendCount,4" frugal:"4,default,i64" json:"friendCount"`
}

func NewFollowStats() *FollowStats {
	return &FollowStats{}
}

func (p *FollowStats) InitDefault() {
}

func (p *FollowStats) GetUserId() (v int64) {
	return p.UserId
}

func (p *FollowStats) GetFollowCount() (v int64) {
	return p.FollowCount
}

func (p *FollowStats) GetFollowerCount() (v int64) {
	return p.FollowerCount
}

func (p *FollowStats) GetFriendCount() (v int64) {
	return p.FriendCount
}
func (p *FollowStats) SetUserId(val int64) {
	p.UserId = val
}
func (p *FollowStats) SetFollowCount(val int64) {
	p.FollowCount = val
}
func (p *FollowStats) SetFollowerCount(val int64) {
	p.FollowerCount = val
}
func (p *FollowStats) SetFriendCount(val int64) {
	p.FriendCount = val
}

func (p *FollowStats) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("FollowStats(%+v)", *p)
}

var fieldIDToName_FollowStats = map[int16]string{
	1: "userId",
	2: "followCount",
	3: "followerCount",
	4: "friendCount",
}

type FollowStatsResp struct {
	BaseResp *common.BaseResp `thrift:"BaseResp,1" frugal:"1,default,common.BaseResp" json:"BaseResp"`
	Stats    *FollowStats     `thrift:"stats,2" frugal:"2,default,FollowStats" json:"stats"`
}

func NewFollowStatsResp() *FollowStatsResp {
	return &FollowStatsResp{}
}

func (p *FollowStatsResp) InitDefault() {
}

var FollowStatsResp_BaseResp_DEFAULT *common.BaseResp

func (p *FollowStatsResp) GetBaseResp() (v *common.BaseResp) {
	if !p.IsSetBaseResp() {
		return FollowStatsResp_BaseResp_DEFAULT
	}
	return p.BaseResp
}

var FollowStatsResp_Stats_DEFAULT *FollowStats

func (p *FollowStatsResp) GetStats() (v *FollowStats) {
	if !p.IsSetStats() {
		return FollowStatsResp_Stats_DEFAULT
	}
	return p.Stats
}
func (p *FollowStatsResp) SetBaseResp(val *common.BaseResp) {
	p.BaseResp = val
}
func (p *FollowStatsResp) SetStats(val *FollowStats) {
	p.Stats = val
}

func (p *FollowStatsResp) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *FollowStatsResp) IsSetStats() bool {
	return p.Stats != nil
}

func (p *FollowStatsResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("FollowStatsResp(%+v)", *p)
}

var fieldIDToName_FollowStatsResp = map[int16]string{
	1: "BaseResp",
	2: "stats",
}

type BatchCheckFollowReq struct {
	UserId        int64   `thrift:"userId,1" frugal:"1,default,i64" json:"userId"`
	TargetUserIds []int64 `thrift:"targetUserIds,2" frugal:"2,default,list<i64>" json:"targetUserIds"`
}

func NewBatchCheckFollowReq() *BatchCheckFollowReq {
	return &BatchCheckFollowReq{}
}

func (p *BatchCheckFollowReq) InitDefault() {
}

func (p *BatchCheckFollowReq) GetUserId() (v int64) {
	return p.UserId
}

func (p *BatchCheckFollowReq) GetTargetUserIds() (v []int64) {
	return p.TargetUserIds
}
func (p *BatchCheckFollowReq) SetUserId(val int64) {
	p.UserId = val
}
func (p *BatchCheckFollowReq) SetTargetUserIds(val []int64) {
	p.TargetUserIds = val
}

func (p *BatchCheckFollowReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("BatchCheckFollowReq(%+v)", *p)
}

var fieldIDToName_BatchCheckFollowReq = map[int16]string{
	1: "userId",
	2: "targetUserIds",
}

type BatchCheckFollowResp struct {
	BaseResp     *common.BaseResp `thrift:"BaseResp,1" frugal:"1,default,common.BaseResp" json:"BaseResp"`
	FollowStatus map[int64]bool   `thrift:"followStatus,2" frugal:"2,default,map<i64:bool>" json:"followStatus"`
}

func NewBatchCheckFollowResp() *BatchCheckFollowResp {
	return &BatchCheckFollowResp{}
}

func (p *BatchCheckFollowResp) InitDefault() {
}

var BatchCheckFollowResp_BaseResp_DEFAULT *common.BaseResp

func (p *BatchCheckFollowResp) GetBaseResp() (v *common.BaseResp) {
	if !p.IsSetBaseResp() {
		return BatchCheckFollowResp_BaseResp_DEFAULT
	}
	return p.BaseResp
}

func (p *BatchCheckFollowResp) GetFollowStatus() (v map[int64]bool) {
	return p.FollowStatus
}
func (p *BatchCheckFollowResp) SetBaseResp(val *common.BaseResp) {
	p.BaseResp = val
}
func (p *BatchCheckFollowResp) SetFollowStatus(val map[int64]bool) {
	p.FollowStatus = val
}

func (p *BatchCheckFollowResp) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *BatchCheckFollowResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("BatchCheckFollowResp(%+v)", *p)
}

var fieldIDToName_BatchCheckFollowResp = map[int16]string{
	1: "BaseResp",
	2: "followStatus",
}

type SocialService interface {
	FollowAction(ctx context.Context, req *FollowActionReq) (r *FollowActionResp, err error)

	GetFollowList(ctx context.Context, req *FollowListReq) (r *FollowListResp, err error)

	GetFollowerList(ctx context.Context, req *FollowerListReq) (r *FollowerListResp, err error)

	GetFriendList(ctx context.Context, req *FriendListReq) (r *FriendListResp, err error)

	CheckFollow(ctx context.Context, req *CheckFollowReq) (r *CheckFollowResp, err error)

	CheckMutualFollow(ctx context.Context, req *CheckMutualFollowReq) (r *CheckMutualFollowResp, err error)

	GetFollowStats(ctx context.Context, req *FollowStatsReq) (r *FollowStatsResp, err error)

	BatchCheckFollow(ctx context.Context, req *BatchCheckFollowReq) (r *BatchCheckFollowResp, err error)
}

type SocialServiceFollowActionArgs struct {
	Req *FollowActionReq `thrift:"req,1" frugal:"1,default,FollowActionReq" json:"req"`
}

func NewSocialServiceFollowActionArgs() *SocialServiceFollowActionArgs {
	return &SocialServiceFollowActionArgs{}
}

func (p *SocialServiceFollowActionArgs) InitDefault() {
}

var SocialServiceFollowActionArgs_Req_DEFAULT *FollowActionReq

func (p *SocialServiceFollowActionArgs) GetReq() (v *FollowActionReq) {
	if !p.IsSetReq() {
		return SocialServiceFollowActionArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *SocialServiceFollowActionArgs) SetReq(val *FollowActionReq) {
	p.Req = val
}

func (p *SocialServiceFollowActionArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *SocialServiceFollowActionArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SocialServiceFollowActionArgs(%+v)", *p)
}

var fieldIDToName_SocialServiceFollowActionArgs = map[int16]string{
	1: "req",
}

type SocialServiceFollowActionResult struct {
	Success *FollowActionResp `thrift:"success,0,optional" frugal:"0,optional,FollowActionResp" json:"success,omitempty"`
}

func NewSocialServiceFollowActionResult() *SocialServiceFollowActionResult {
	return &SocialServiceFollowActionResult{}
}

func (p *SocialServiceFollowActionResult) InitDefault() {
}

var SocialServiceFollowActionResult_Success_DEFAULT *FollowActionResp

func (p *SocialServiceFollowActionResult) GetSuccess() (v *FollowActionResp) {
	if !p.IsSetSuccess() {
		return SocialServiceFollowActionResult_Success_DEFAULT
	}
	return p.Success
}
func (p *SocialServiceFollowActionResult) SetSuccess(x interface{}) {
	p.Success = x.(*FollowActionResp)
}

func (p *SocialServiceFollowActionResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *SocialServiceFollowActionResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SocialServiceFollowActionResult(%+v)", *p)
}

var fieldIDToName_SocialServiceFollowActionResult = map[int16]string{
	0: "success",
}

type SocialServiceGetFollowListArgs struct {
	Req *FollowListReq `thrift:"req,1" frugal:"1,default,FollowListReq" json:"req"`
}

func NewSocialServiceGetFollowListArgs() *SocialServiceGetFollowListArgs {
	return &SocialServiceGetFollowListArgs{}
}

func (p *SocialServiceGetFollowListArgs) InitDefault() {
}

var SocialServiceGetFollowListArgs_Req_DEFAULT *FollowListReq

func (p *SocialServiceGetFollowListArgs) GetReq() (v *FollowListReq) {
	if !p.IsSetReq() {
		return SocialServiceGetFollowListArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *SocialServiceGetFollowListArgs) SetReq(val *FollowListReq) {
	p.Req = val
}

func (p *SocialServiceGetFollowListArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *SocialServiceGetFollowListArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SocialServiceGetFollowListArgs(%+v)", *p)
}

var fieldIDToName_SocialServiceGetFollowListArgs = map[int16]string{
	1: "req",
}

type SocialServiceGetFollowListResult struct {
	Success *FollowListResp `thrift:"success,0,optional" frugal:"0,optional,FollowListResp" json:"success,omitempty"`
}

func NewSocialServiceGetFollowListResult() *SocialServiceGetFollowListResult {
	return &SocialServiceGetFollowListResult{}
}

func (p *SocialServiceGetFollowListResult) InitDefault() {
}

var SocialServiceGetFollowListResult_Success_DEFAULT *FollowListResp

func (p *SocialServiceGetFollowListResult) GetSuccess() (v *FollowListResp) {
	if !p.IsSetSuccess() {
		return SocialServiceGetFollowListResult_Success_DEFAULT
	}
	return p.Success
}
func (p *SocialServiceGetFollowListResult) SetSuccess(x interface{}) {
	p.Success = x.(*FollowListResp)
}

func (p *SocialServiceGetFollowListResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *SocialServiceGetFollowListResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SocialServiceGetFollowListResult(%+v)", *p)
}

var fieldIDToName_SocialServiceGetFollowListResult = map[int16]string{
	0: "success",
}

type SocialServiceGetFollowerListArgs struct {
	Req *FollowerListReq `thrift:"req,1" frugal:"1,default,FollowerListReq" json:"req"`
}

func NewSocialServiceGetFollowerListArgs() *SocialServiceGetFollowerListArgs {
	return &SocialServiceGetFollowerListArgs{}
}

func (p *SocialServiceGetFollowerListArgs) InitDefault() {
}

var SocialServiceGetFollowerListArgs_Req_DEFAULT *FollowerListReq

func (p *SocialServiceGetFollowerListArgs) GetReq() (v *FollowerListReq) {
	if !p.IsSetReq() {
		return SocialServiceGetFollowerListArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *SocialServiceGetFollowerListArgs) SetReq(val *FollowerListReq) {
	p.Req = val
}

func (p *SocialServiceGetFollowerListArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *SocialServiceGetFollowerListArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SocialServiceGetFollowerListArgs(%+v)", *p)
}

var fieldIDToName_SocialServiceGetFollowerListArgs = map[int16]string{
	1: "req",
}

type SocialServiceGetFollowerListResult struct {
	Success *FollowerListResp `thrift:"success,0,optional" frugal:"0,optional,FollowerListResp" json:"success,omitempty"`
}

func NewSocialServiceGetFollowerListResult() *SocialServiceGetFollowerListResult {
	return &SocialServiceGetFollowerListResult{}
}

func (p *SocialServiceGetFollowerListResult) InitDefault() {
}

var SocialServiceGetFollowerListResult_Success_DEFAULT *FollowerListResp

func (p *SocialServiceGetFollowerListResult) GetSuccess() (v *FollowerListResp) {
	if !p.IsSetSuccess() {
		return SocialServiceGetFollowerListResult_Success_DEFAULT
	}
	return p.Success
}
func (p *SocialServiceGetFollowerListResult) SetSuccess(x interface{}) {
	p.Success = x.(*FollowerListResp)
}

func (p *SocialServiceGetFollowerListResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *SocialServiceGetFollowerListResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SocialServiceGetFollowerListResult(%+v)", *p)
}

var fieldIDToName_SocialServiceGetFollowerListResult = map[int16]string{
	0: "success",
}

type SocialServiceGetFriendListArgs struct {
	Req *FriendListReq `thrift:"req,1" frugal:"1,default,FriendListReq" json:"req"`
}

func NewSocialServiceGetFriendListArgs() *SocialServiceGetFriendListArgs {
	return &SocialServiceGetFriendListArgs{}
}

func (p *SocialServiceGetFriendListArgs) InitDefault() {
}

var SocialServiceGetFriendListArgs_Req_DEFAULT *FriendListReq

func (p *SocialServiceGetFriendListArgs) GetReq() (v *FriendListReq) {
	if !p.IsSetReq() {
		return SocialServiceGetFriendListArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *SocialServiceGetFriendListArgs) SetReq(val *FriendListReq) {
	p.Req = val
}

func (p *SocialServiceGetFriendListArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *SocialServiceGetFriendListArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SocialServiceGetFriendListArgs(%+v)", *p)
}

var fieldIDToName_SocialServiceGetFriendListArgs = map[int16]string{
	1: "req",
}

type SocialServiceGetFriendListResult struct {
	Success *FriendListResp `thrift:"success,0,optional" frugal:"0,optional,FriendListResp" json:"success,omitempty"`
}

func NewSocialServiceGetFriendListResult() *SocialServiceGetFriendListResult {
	return &SocialServiceGetFriendListResult{}
}

func (p *SocialServiceGetFriendListResult) InitDefault() {
}

var SocialServiceGetFriendListResult_Success_DEFAULT *FriendListResp

func (p *SocialServiceGetFriendListResult) GetSuccess() (v *FriendListResp) {
	if !p.IsSetSuccess() {
		return SocialServiceGetFriendListResult_Success_DEFAULT
	}
	return p.Success
}
func (p *SocialServiceGetFriendListResult) SetSuccess(x interface{}) {
	p.Success = x.(*FriendListResp)
}

func (p *SocialServiceGetFriendListResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *SocialServiceGetFriendListResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SocialServiceGetFriendListResult(%+v)", *p)
}

var fieldIDToName_SocialServiceGetFriendListResult = map[int16]string{
	0: "success",
}

type SocialServiceCheckFollowArgs struct {
	Req *CheckFollowReq `thrift:"req,1" frugal:"1,default,CheckFollowReq" json:"req"`
}

func NewSocialServiceCheckFollowArgs() *SocialServiceCheckFollowArgs {
	return &SocialServiceCheckFollowArgs{}
}

func (p *SocialServiceCheckFollowArgs) InitDefault() {
}

var SocialServiceCheckFollowArgs_Req_DEFAULT *CheckFollowReq

func (p *SocialServiceCheckFollowArgs) GetReq() (v *CheckFollowReq) {
	if !p.IsSetReq() {
		return SocialServiceCheckFollowArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *SocialServiceCheckFollowArgs) SetReq(val *CheckFollowReq) {
	p.Req = val
}

func (p *SocialServiceCheckFollowArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *SocialServiceCheckFollowArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SocialServiceCheckFollowArgs(%+v)", *p)
}

var fieldIDToName_SocialServiceCheckFollowArgs = map[int16]string{
	1: "req",
}

type SocialServiceCheckFollowResult struct {
	Success *CheckFollowResp `thrift:"success,0,optional" frugal:"0,optional,CheckFollowResp" json:"success,omitempty"`
}

func NewSocialServiceCheckFollowResult() *SocialServiceCheckFollowResult {
	return &SocialServiceCheckFollowResult{}
}

func (p *SocialServiceCheckFollowResult) InitDefault() {
}

var SocialServiceCheckFollowResult_Success_DEFAULT *CheckFollowResp

func (p *SocialServiceCheckFollowResult) GetSuccess() (v *CheckFollowResp) {
	if !p.IsSetSuccess() {
		return SocialServiceCheckFollowResult_Success_DEFAULT
	}
	return p.Success
}
func (p *SocialServiceCheckFollowResult) SetSuccess(x interface{}) {
	p.Success = x.(*CheckFollowResp)
}

func (p *SocialServiceCheckFollowResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *SocialServiceCheckFollowResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SocialServiceCheckFollowResult(%+v)", *p)
}

var fieldIDToName_SocialServiceCheckFollowResult = map[int16]string{
	0: "success",
}

type SocialServiceCheckMutualFollowArgs struct {
	Req *CheckMutualFollowReq `thrift:"req,1" frugal:"1,default,CheckMutualFollowReq" json:"req"`
}

func NewSocialServiceCheckMutualFollowArgs() *SocialServiceCheckMutualFollowArgs {
	return &SocialServiceCheckMutualFollowArgs{}
}

func (p *SocialServiceCheckMutualFollowArgs) InitDefault() {
}

var SocialServiceCheckMutualFollowArgs_Req_DEFAULT *CheckMutualFollowReq

func (p *SocialServiceCheckMutualFollowArgs) GetReq() (v *CheckMutualFollowReq) {
	if !p.IsSetReq() {
		return SocialServiceCheckMutualFollowArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *SocialServiceCheckMutualFollowArgs) SetReq(val *CheckMutualFollowReq) {
	p.Req = val
}

func (p *SocialServiceCheckMutualFollowArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *SocialServiceCheckMutualFollowArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SocialServiceCheckMutualFollowArgs(%+v)", *p)
}

var fieldIDToName_SocialServiceCheckMutualFollowArgs = map[int16]string{
	1: "req",
}

type SocialServiceCheckMutualFollowResult struct {
	Success *CheckMutualFollowResp `thrift:"success,0,optional" frugal:"0,optional,CheckMutualFollowResp" json:"success,omitempty"`
}

func NewSocialServiceCheckMutualFollowResult() *SocialServiceCheckMutualFollowResult {
	return &SocialServiceCheckMutualFollowResult{}
}

func (p *SocialServiceCheckMutualFollowResult) InitDefault() {
}

var SocialServiceCheckMutualFollowResult_Success_DEFAULT *CheckMutualFollowResp

func (p *SocialServiceCheckMutualFollowResult) GetSuccess() (v *CheckMutualFollowResp) {
	if !p.IsSetSuccess() {
		return SocialServiceCheckMutualFollowResult_Success_DEFAULT
	}
	return p.Success
}
func (p *SocialServiceCheckMutualFollowResult) SetSuccess(x interface{}) {
	p.Success = x.(*CheckMutualFollowResp)
}

func (p *SocialServiceCheckMutualFollowResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *SocialServiceCheckMutualFollowResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SocialServiceCheckMutualFollowResult(%+v)", *p)
}

var fieldIDToName_SocialServiceCheckMutualFollowResult = map[int16]string{
	0: "success",
}

type SocialServiceGetFollowStatsArgs struct {
	Req *FollowStatsReq `thrift:"req,1" frugal:"1,default,FollowStatsReq" json:"req"`
}

func NewSocialServiceGetFollowStatsArgs() *SocialServiceGetFollowStatsArgs {
	return &SocialServiceGetFollowStatsArgs{}
}

func (p *SocialServiceGetFollowStatsArgs) InitDefault() {
}

var SocialServiceGetFollowStatsArgs_Req_DEFAULT *FollowStatsReq

func (p *SocialServiceGetFollowStatsArgs) GetReq() (v *FollowStatsReq) {
	if !p.IsSetReq() {
		return SocialServiceGetFollowStatsArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *SocialServiceGetFollowStatsArgs) SetReq(val *FollowStatsReq) {
	p.Req = val
}

func (p *SocialServiceGetFollowStatsArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *SocialServiceGetFollowStatsArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SocialServiceGetFollowStatsArgs(%+v)", *p)
}

var fieldIDToName_SocialServiceGetFollowStatsArgs = map[int16]string{
	1: "req",
}

type SocialServiceGetFollowStatsResult struct {
	Success *FollowStatsResp `thrift:"success,0,optional" frugal:"0,optional,FollowStatsResp" json:"success,omitempty"`
}

func NewSocialServiceGetFollowStatsResult() *SocialServiceGetFollowStatsResult {
	return &SocialServiceGetFollowStatsResult{}
}

func (p *SocialServiceGetFollowStatsResult) InitDefault() {
}

var SocialServiceGetFollowStatsResult_Success_DEFAULT *FollowStatsResp

func (p *SocialServiceGetFollowStatsResult) GetSuccess() (v *FollowStatsResp) {
	if !p.IsSetSuccess() {
		return SocialServiceGetFollowStatsResult_Success_DEFAULT
	}
	return p.Success
}
func (p *SocialServiceGetFollowStatsResult) SetSuccess(x interface{}) {
	p.Success = x.(*FollowStatsResp)
}

func (p *SocialServiceGetFollowStatsResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *SocialServiceGetFollowStatsResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SocialServiceGetFollowStatsResult(%+v)", *p)
}

var fieldIDToName_SocialServiceGetFollowStatsResult = map[int16]string{
	0: "success",
}

type SocialServiceBatchCheckFollowArgs struct {
	Req *BatchCheckFollowReq `thrift:"req,1" frugal:"1,default,BatchCheckFollowReq" json:"req"`
}

func NewSocialServiceBatchCheckFollowArgs() *SocialServiceBatchCheckFollowArgs {
	return &SocialServiceBatchCheckFollowArgs{}
}

func (p *SocialServiceBatchCheckFollowArgs) InitDefault() {
}

var SocialServiceBatchCheckFollowArgs_Req_DEFAULT *BatchCheckFollowReq

func (p *SocialServiceBatchCheckFollowArgs) GetReq() (v *BatchCheckFollowReq) {
	if !p.IsSetReq() {
		return SocialServiceBatchCheckFollowArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *SocialServiceBatchCheckFollowArgs) SetReq(val *BatchCheckFollowReq) {
	p.Req = val
}

func (p *SocialServiceBatchCheckFollowArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *SocialServiceBatchCheckFollowArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SocialServiceBatchCheckFollowArgs(%+v)", *p)
}

var fieldIDToName_SocialServiceBatchCheckFollowArgs = map[int16]string{
	1: "req",
}

type SocialServiceBatchCheckFollowResult struct {
	Success *BatchCheckFollowResp `thrift:"success,0,optional" frugal:"0,optional,BatchCheckFollowResp" json:"success,omitempty"`
}

func NewSocialServiceBatchCheckFollowResult() *SocialServiceBatchCheckFollowResult {
	return &SocialServiceBatchCheckFollowResult{}
}

func (p *SocialServiceBatchCheckFollowResult) InitDefault() {
}

var SocialServiceBatchCheckFollowResult_Success_DEFAULT *BatchCheckFollowResp

func (p *SocialServiceBatchCheckFollowResult) GetSuccess() (v *BatchCheckFollowResp) {
	if !p.IsSetSuccess() {
		return SocialServiceBatchCheckFollowResult_Success_DEFAULT
	}
	return p.Success
}
func (p *SocialServiceBatchCheckFollowResult) SetSuccess(x interface{}) {
	p.Success = x.(*BatchCheckFollowResp)
}

func (p *SocialServiceBatchCheckFollowResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *SocialServiceBatchCheckFollowResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SocialServiceBatchCheckFollowResult(%+v)", *p)
}

var fieldIDToName_SocialServiceBatchCheckFollowResult = map[int16]string{
	0: "success",
}
