// Code generated by Kitex v0.15.2. DO NOT EDIT.

package interactionservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	interaction "shortvideo/kitex_gen/interaction"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	LikeAction(ctx context.Context, req *interaction.LikeActionReq, callOptions ...callopt.Option) (r *interaction.LikeActionResp, err error)
	GetLikeVideoList(ctx context.Context, req *interaction.LikeVideoListReq, callOptions ...callopt.Option) (r *interaction.LikeVideoListResp, err error)
	StarAction(ctx context.Context, req *interaction.StarActionReq, callOptions ...callopt.Option) (r *interaction.StarActionResp, err error)
	GetStarVideoList(ctx context.Context, req *interaction.StarVideoListReq, callOptions ...callopt.Option) (r *interaction.StarVideoListResp, err error)
	CommentAction(ctx context.Context, req *interaction.CommentActionReq, callOptions ...callopt.Option) (r *interaction.CommentActionResp, err error)
	GetCommentList(ctx context.Context, req *interaction.CommentListReq, callOptions ...callopt.Option) (r *interaction.CommentListResp, err error)
	DeleteComment(ctx context.Context, req *interaction.DeleteCommentReq, callOptions ...callopt.Option) (r *interaction.DeleteCommentResp, err error)
	ShareAction(ctx context.Context, req *interaction.ShareActionReq, callOptions ...callopt.Option) (r *interaction.ShareActionResp, err error)
	GetCount(ctx context.Context, req *interaction.CountReq, callOptions ...callopt.Option) (r *interaction.CountResp, err error)
	CheckLikeStatus(ctx context.Context, req *interaction.CheckLikeStatusReq, callOptions ...callopt.Option) (r *interaction.CheckLikeStatusResp, err error)
	CheckStarStatus(ctx context.Context, req *interaction.CheckStarStatusReq, callOptions ...callopt.Option) (r *interaction.CheckStarStatusResp, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfoForClient(), options...)
	if err != nil {
		return nil, err
	}
	return &kInteractionServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kInteractionServiceClient struct {
	*kClient
}

func (p *kInteractionServiceClient) LikeAction(ctx context.Context, req *interaction.LikeActionReq, callOptions ...callopt.Option) (r *interaction.LikeActionResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.LikeAction(ctx, req)
}

func (p *kInteractionServiceClient) GetLikeVideoList(ctx context.Context, req *interaction.LikeVideoListReq, callOptions ...callopt.Option) (r *interaction.LikeVideoListResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetLikeVideoList(ctx, req)
}

func (p *kInteractionServiceClient) StarAction(ctx context.Context, req *interaction.StarActionReq, callOptions ...callopt.Option) (r *interaction.StarActionResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.StarAction(ctx, req)
}

func (p *kInteractionServiceClient) GetStarVideoList(ctx context.Context, req *interaction.StarVideoListReq, callOptions ...callopt.Option) (r *interaction.StarVideoListResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetStarVideoList(ctx, req)
}

func (p *kInteractionServiceClient) CommentAction(ctx context.Context, req *interaction.CommentActionReq, callOptions ...callopt.Option) (r *interaction.CommentActionResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CommentAction(ctx, req)
}

func (p *kInteractionServiceClient) GetCommentList(ctx context.Context, req *interaction.CommentListReq, callOptions ...callopt.Option) (r *interaction.CommentListResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetCommentList(ctx, req)
}

func (p *kInteractionServiceClient) DeleteComment(ctx context.Context, req *interaction.DeleteCommentReq, callOptions ...callopt.Option) (r *interaction.DeleteCommentResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.DeleteComment(ctx, req)
}

func (p *kInteractionServiceClient) ShareAction(ctx context.Context, req *interaction.ShareActionReq, callOptions ...callopt.Option) (r *interaction.ShareActionResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ShareAction(ctx, req)
}

func (p *kInteractionServiceClient) GetCount(ctx context.Context, req *interaction.CountReq, callOptions ...callopt.Option) (r *interaction.CountResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetCount(ctx, req)
}

func (p *kInteractionServiceClient) CheckLikeStatus(ctx context.Context, req *interaction.CheckLikeStatusReq, callOptions ...callopt.Option) (r *interaction.CheckLikeStatusResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CheckLikeStatus(ctx, req)
}

func (p *kInteractionServiceClient) CheckStarStatus(ctx context.Context, req *interaction.CheckStarStatusReq, callOptions ...callopt.Option) (r *interaction.CheckStarStatusResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CheckStarStatus(ctx, req)
}
