// Code generated by Kitex v0.15.2. DO NOT EDIT.

package interactionservice

import (
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	interaction "shortvideo/kitex_gen/interaction"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"LikeAction": kitex.NewMethodInfo(
		likeActionHandler,
		newInteractionServiceLikeActionArgs,
		newInteractionServiceLikeActionResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetLikeVideoList": kitex.NewMethodInfo(
		getLikeVideoListHandler,
		newInteractionServiceGetLikeVideoListArgs,
		newInteractionServiceGetLikeVideoListResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"StarAction": kitex.NewMethodInfo(
		starActionHandler,
		newInteractionServiceStarActionArgs,
		newInteractionServiceStarActionResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetStarVideoList": kitex.NewMethodInfo(
		getStarVideoListHandler,
		newInteractionServiceGetStarVideoListArgs,
		newInteractionServiceGetStarVideoListResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"CommentAction": kitex.NewMethodInfo(
		commentActionHandler,
		newInteractionServiceCommentActionArgs,
		newInteractionServiceCommentActionResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetCommentList": kitex.NewMethodInfo(
		getCommentListHandler,
		newInteractionServiceGetCommentListArgs,
		newInteractionServiceGetCommentListResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"DeleteComment": kitex.NewMethodInfo(
		deleteCommentHandler,
		newInteractionServiceDeleteCommentArgs,
		newInteractionServiceDeleteCommentResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"ShareAction": kitex.NewMethodInfo(
		shareActionHandler,
		newInteractionServiceShareActionArgs,
		newInteractionServiceShareActionResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetCount": kitex.NewMethodInfo(
		getCountHandler,
		newInteractionServiceGetCountArgs,
		newInteractionServiceGetCountResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"CheckLikeStatus": kitex.NewMethodInfo(
		checkLikeStatusHandler,
		newInteractionServiceCheckLikeStatusArgs,
		newInteractionServiceCheckLikeStatusResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"CheckStarStatus": kitex.NewMethodInfo(
		checkStarStatusHandler,
		newInteractionServiceCheckStarStatusArgs,
		newInteractionServiceCheckStarStatusResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	interactionServiceServiceInfo                = NewServiceInfo()
	interactionServiceServiceInfoForClient       = NewServiceInfoForClient()
	interactionServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return interactionServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return interactionServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return interactionServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "InteractionService"
	handlerType := (*interaction.InteractionService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "interaction",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.15.2",
		Extra:           extra,
	}
	return svcInfo
}

func likeActionHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*interaction.InteractionServiceLikeActionArgs)
	realResult := result.(*interaction.InteractionServiceLikeActionResult)
	success, err := handler.(interaction.InteractionService).LikeAction(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newInteractionServiceLikeActionArgs() interface{} {
	return interaction.NewInteractionServiceLikeActionArgs()
}

func newInteractionServiceLikeActionResult() interface{} {
	return interaction.NewInteractionServiceLikeActionResult()
}

func getLikeVideoListHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*interaction.InteractionServiceGetLikeVideoListArgs)
	realResult := result.(*interaction.InteractionServiceGetLikeVideoListResult)
	success, err := handler.(interaction.InteractionService).GetLikeVideoList(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newInteractionServiceGetLikeVideoListArgs() interface{} {
	return interaction.NewInteractionServiceGetLikeVideoListArgs()
}

func newInteractionServiceGetLikeVideoListResult() interface{} {
	return interaction.NewInteractionServiceGetLikeVideoListResult()
}

func starActionHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*interaction.InteractionServiceStarActionArgs)
	realResult := result.(*interaction.InteractionServiceStarActionResult)
	success, err := handler.(interaction.InteractionService).StarAction(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newInteractionServiceStarActionArgs() interface{} {
	return interaction.NewInteractionServiceStarActionArgs()
}

func newInteractionServiceStarActionResult() interface{} {
	return interaction.NewInteractionServiceStarActionResult()
}

func getStarVideoListHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*interaction.InteractionServiceGetStarVideoListArgs)
	realResult := result.(*interaction.InteractionServiceGetStarVideoListResult)
	success, err := handler.(interaction.InteractionService).GetStarVideoList(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newInteractionServiceGetStarVideoListArgs() interface{} {
	return interaction.NewInteractionServiceGetStarVideoListArgs()
}

func newInteractionServiceGetStarVideoListResult() interface{} {
	return interaction.NewInteractionServiceGetStarVideoListResult()
}

func commentActionHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*interaction.InteractionServiceCommentActionArgs)
	realResult := result.(*interaction.InteractionServiceCommentActionResult)
	success, err := handler.(interaction.InteractionService).CommentAction(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newInteractionServiceCommentActionArgs() interface{} {
	return interaction.NewInteractionServiceCommentActionArgs()
}

func newInteractionServiceCommentActionResult() interface{} {
	return interaction.NewInteractionServiceCommentActionResult()
}

func getCommentListHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*interaction.InteractionServiceGetCommentListArgs)
	realResult := result.(*interaction.InteractionServiceGetCommentListResult)
	success, err := handler.(interaction.InteractionService).GetCommentList(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newInteractionServiceGetCommentListArgs() interface{} {
	return interaction.NewInteractionServiceGetCommentListArgs()
}

func newInteractionServiceGetCommentListResult() interface{} {
	return interaction.NewInteractionServiceGetCommentListResult()
}

func deleteCommentHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*interaction.InteractionServiceDeleteCommentArgs)
	realResult := result.(*interaction.InteractionServiceDeleteCommentResult)
	success, err := handler.(interaction.InteractionService).DeleteComment(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newInteractionServiceDeleteCommentArgs() interface{} {
	return interaction.NewInteractionServiceDeleteCommentArgs()
}

func newInteractionServiceDeleteCommentResult() interface{} {
	return interaction.NewInteractionServiceDeleteCommentResult()
}

func shareActionHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*interaction.InteractionServiceShareActionArgs)
	realResult := result.(*interaction.InteractionServiceShareActionResult)
	success, err := handler.(interaction.InteractionService).ShareAction(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newInteractionServiceShareActionArgs() interface{} {
	return interaction.NewInteractionServiceShareActionArgs()
}

func newInteractionServiceShareActionResult() interface{} {
	return interaction.NewInteractionServiceShareActionResult()
}

func getCountHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*interaction.InteractionServiceGetCountArgs)
	realResult := result.(*interaction.InteractionServiceGetCountResult)
	success, err := handler.(interaction.InteractionService).GetCount(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newInteractionServiceGetCountArgs() interface{} {
	return interaction.NewInteractionServiceGetCountArgs()
}

func newInteractionServiceGetCountResult() interface{} {
	return interaction.NewInteractionServiceGetCountResult()
}

func checkLikeStatusHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*interaction.InteractionServiceCheckLikeStatusArgs)
	realResult := result.(*interaction.InteractionServiceCheckLikeStatusResult)
	success, err := handler.(interaction.InteractionService).CheckLikeStatus(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newInteractionServiceCheckLikeStatusArgs() interface{} {
	return interaction.NewInteractionServiceCheckLikeStatusArgs()
}

func newInteractionServiceCheckLikeStatusResult() interface{} {
	return interaction.NewInteractionServiceCheckLikeStatusResult()
}

func checkStarStatusHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*interaction.InteractionServiceCheckStarStatusArgs)
	realResult := result.(*interaction.InteractionServiceCheckStarStatusResult)
	success, err := handler.(interaction.InteractionService).CheckStarStatus(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newInteractionServiceCheckStarStatusArgs() interface{} {
	return interaction.NewInteractionServiceCheckStarStatusArgs()
}

func newInteractionServiceCheckStarStatusResult() interface{} {
	return interaction.NewInteractionServiceCheckStarStatusResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) LikeAction(ctx context.Context, req *interaction.LikeActionReq) (r *interaction.LikeActionResp, err error) {
	var _args interaction.InteractionServiceLikeActionArgs
	_args.Req = req
	var _result interaction.InteractionServiceLikeActionResult
	if err = p.c.Call(ctx, "LikeAction", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetLikeVideoList(ctx context.Context, req *interaction.LikeVideoListReq) (r *interaction.LikeVideoListResp, err error) {
	var _args interaction.InteractionServiceGetLikeVideoListArgs
	_args.Req = req
	var _result interaction.InteractionServiceGetLikeVideoListResult
	if err = p.c.Call(ctx, "GetLikeVideoList", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) StarAction(ctx context.Context, req *interaction.StarActionReq) (r *interaction.StarActionResp, err error) {
	var _args interaction.InteractionServiceStarActionArgs
	_args.Req = req
	var _result interaction.InteractionServiceStarActionResult
	if err = p.c.Call(ctx, "StarAction", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetStarVideoList(ctx context.Context, req *interaction.StarVideoListReq) (r *interaction.StarVideoListResp, err error) {
	var _args interaction.InteractionServiceGetStarVideoListArgs
	_args.Req = req
	var _result interaction.InteractionServiceGetStarVideoListResult
	if err = p.c.Call(ctx, "GetStarVideoList", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) CommentAction(ctx context.Context, req *interaction.CommentActionReq) (r *interaction.CommentActionResp, err error) {
	var _args interaction.InteractionServiceCommentActionArgs
	_args.Req = req
	var _result interaction.InteractionServiceCommentActionResult
	if err = p.c.Call(ctx, "CommentAction", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetCommentList(ctx context.Context, req *interaction.CommentListReq) (r *interaction.CommentListResp, err error) {
	var _args interaction.InteractionServiceGetCommentListArgs
	_args.Req = req
	var _result interaction.InteractionServiceGetCommentListResult
	if err = p.c.Call(ctx, "GetCommentList", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) DeleteComment(ctx context.Context, req *interaction.DeleteCommentReq) (r *interaction.DeleteCommentResp, err error) {
	var _args interaction.InteractionServiceDeleteCommentArgs
	_args.Req = req
	var _result interaction.InteractionServiceDeleteCommentResult
	if err = p.c.Call(ctx, "DeleteComment", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ShareAction(ctx context.Context, req *interaction.ShareActionReq) (r *interaction.ShareActionResp, err error) {
	var _args interaction.InteractionServiceShareActionArgs
	_args.Req = req
	var _result interaction.InteractionServiceShareActionResult
	if err = p.c.Call(ctx, "ShareAction", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetCount(ctx context.Context, req *interaction.CountReq) (r *interaction.CountResp, err error) {
	var _args interaction.InteractionServiceGetCountArgs
	_args.Req = req
	var _result interaction.InteractionServiceGetCountResult
	if err = p.c.Call(ctx, "GetCount", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) CheckLikeStatus(ctx context.Context, req *interaction.CheckLikeStatusReq) (r *interaction.CheckLikeStatusResp, err error) {
	var _args interaction.InteractionServiceCheckLikeStatusArgs
	_args.Req = req
	var _result interaction.InteractionServiceCheckLikeStatusResult
	if err = p.c.Call(ctx, "CheckLikeStatus", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) CheckStarStatus(ctx context.Context, req *interaction.CheckStarStatusReq) (r *interaction.CheckStarStatusResp, err error) {
	var _args interaction.InteractionServiceCheckStarStatusArgs
	_args.Req = req
	var _result interaction.InteractionServiceCheckStarStatusResult
	if err = p.c.Call(ctx, "CheckStarStatus", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
