// Code generated by Kitex v0.15.2. DO NOT EDIT.

package liveservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	live "shortvideo/kitex_gen/live"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	CreateLiveRoom(ctx context.Context, req *live.CreateLiveRoomReq, callOptions ...callopt.Option) (r *live.CreateLiveRoomResp, err error)
	StartLive(ctx context.Context, req *live.StartLiveReq, callOptions ...callopt.Option) (r *live.StartLiveResp, err error)
	StopLive(ctx context.Context, req *live.StopLiveReq, callOptions ...callopt.Option) (r *live.StopLiveResp, err error)
	GetLiveRooms(ctx context.Context, req *live.GetLiveRoomsReq, callOptions ...callopt.Option) (r *live.GetLiveRoomsResp, err error)
	GetLiveRoomDetail(ctx context.Context, req *live.GetLiveRoomDetailReq, callOptions ...callopt.Option) (r *live.GetLiveRoomDetailResp, err error)
	JoinLiveRoom(ctx context.Context, req *live.JoinLiveRoomReq, callOptions ...callopt.Option) (r *live.JoinLiveRoomResp, err error)
	LeaveLiveRoom(ctx context.Context, req *live.LeaveLiveRoomReq, callOptions ...callopt.Option) (r *live.LeaveLiveRoomResp, err error)
	SendGift(ctx context.Context, req *live.SendGiftReq, callOptions ...callopt.Option) (r *live.SendGiftResp, err error)
	GetGiftList(ctx context.Context, callOptions ...callopt.Option) (r *live.GetGiftListResp, err error)
	SetRoomAdmin(ctx context.Context, req *live.SetRoomAdminReq, callOptions ...callopt.Option) (r *live.SetRoomAdminResp, err error)
	RecordLive(ctx context.Context, req *live.RecordLiveReq, callOptions ...callopt.Option) (r *live.RecordLiveResp, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfoForClient(), options...)
	if err != nil {
		return nil, err
	}
	return &kLiveServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kLiveServiceClient struct {
	*kClient
}

func (p *kLiveServiceClient) CreateLiveRoom(ctx context.Context, req *live.CreateLiveRoomReq, callOptions ...callopt.Option) (r *live.CreateLiveRoomResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CreateLiveRoom(ctx, req)
}

func (p *kLiveServiceClient) StartLive(ctx context.Context, req *live.StartLiveReq, callOptions ...callopt.Option) (r *live.StartLiveResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.StartLive(ctx, req)
}

func (p *kLiveServiceClient) StopLive(ctx context.Context, req *live.StopLiveReq, callOptions ...callopt.Option) (r *live.StopLiveResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.StopLive(ctx, req)
}

func (p *kLiveServiceClient) GetLiveRooms(ctx context.Context, req *live.GetLiveRoomsReq, callOptions ...callopt.Option) (r *live.GetLiveRoomsResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetLiveRooms(ctx, req)
}

func (p *kLiveServiceClient) GetLiveRoomDetail(ctx context.Context, req *live.GetLiveRoomDetailReq, callOptions ...callopt.Option) (r *live.GetLiveRoomDetailResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetLiveRoomDetail(ctx, req)
}

func (p *kLiveServiceClient) JoinLiveRoom(ctx context.Context, req *live.JoinLiveRoomReq, callOptions ...callopt.Option) (r *live.JoinLiveRoomResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.JoinLiveRoom(ctx, req)
}

func (p *kLiveServiceClient) LeaveLiveRoom(ctx context.Context, req *live.LeaveLiveRoomReq, callOptions ...callopt.Option) (r *live.LeaveLiveRoomResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.LeaveLiveRoom(ctx, req)
}

func (p *kLiveServiceClient) SendGift(ctx context.Context, req *live.SendGiftReq, callOptions ...callopt.Option) (r *live.SendGiftResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.SendGift(ctx, req)
}

func (p *kLiveServiceClient) GetGiftList(ctx context.Context, callOptions ...callopt.Option) (r *live.GetGiftListResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetGiftList(ctx)
}

func (p *kLiveServiceClient) SetRoomAdmin(ctx context.Context, req *live.SetRoomAdminReq, callOptions ...callopt.Option) (r *live.SetRoomAdminResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.SetRoomAdmin(ctx, req)
}

func (p *kLiveServiceClient) RecordLive(ctx context.Context, req *live.RecordLiveReq, callOptions ...callopt.Option) (r *live.RecordLiveResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.RecordLive(ctx, req)
}
