// Code generated by Kitex v0.15.2. DO NOT EDIT.

package liveservice

import (
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	live "shortvideo/kitex_gen/live"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"CreateLiveRoom": kitex.NewMethodInfo(
		createLiveRoomHandler,
		newLiveServiceCreateLiveRoomArgs,
		newLiveServiceCreateLiveRoomResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"StartLive": kitex.NewMethodInfo(
		startLiveHandler,
		newLiveServiceStartLiveArgs,
		newLiveServiceStartLiveResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"StopLive": kitex.NewMethodInfo(
		stopLiveHandler,
		newLiveServiceStopLiveArgs,
		newLiveServiceStopLiveResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetLiveRooms": kitex.NewMethodInfo(
		getLiveRoomsHandler,
		newLiveServiceGetLiveRoomsArgs,
		newLiveServiceGetLiveRoomsResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetLiveRoomDetail": kitex.NewMethodInfo(
		getLiveRoomDetailHandler,
		newLiveServiceGetLiveRoomDetailArgs,
		newLiveServiceGetLiveRoomDetailResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"JoinLiveRoom": kitex.NewMethodInfo(
		joinLiveRoomHandler,
		newLiveServiceJoinLiveRoomArgs,
		newLiveServiceJoinLiveRoomResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"LeaveLiveRoom": kitex.NewMethodInfo(
		leaveLiveRoomHandler,
		newLiveServiceLeaveLiveRoomArgs,
		newLiveServiceLeaveLiveRoomResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"SendGift": kitex.NewMethodInfo(
		sendGiftHandler,
		newLiveServiceSendGiftArgs,
		newLiveServiceSendGiftResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetGiftList": kitex.NewMethodInfo(
		getGiftListHandler,
		newLiveServiceGetGiftListArgs,
		newLiveServiceGetGiftListResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"SetRoomAdmin": kitex.NewMethodInfo(
		setRoomAdminHandler,
		newLiveServiceSetRoomAdminArgs,
		newLiveServiceSetRoomAdminResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"RecordLive": kitex.NewMethodInfo(
		recordLiveHandler,
		newLiveServiceRecordLiveArgs,
		newLiveServiceRecordLiveResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	liveServiceServiceInfo                = NewServiceInfo()
	liveServiceServiceInfoForClient       = NewServiceInfoForClient()
	liveServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return liveServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return liveServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return liveServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "LiveService"
	handlerType := (*live.LiveService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "live",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.15.2",
		Extra:           extra,
	}
	return svcInfo
}

func createLiveRoomHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*live.LiveServiceCreateLiveRoomArgs)
	realResult := result.(*live.LiveServiceCreateLiveRoomResult)
	success, err := handler.(live.LiveService).CreateLiveRoom(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newLiveServiceCreateLiveRoomArgs() interface{} {
	return live.NewLiveServiceCreateLiveRoomArgs()
}

func newLiveServiceCreateLiveRoomResult() interface{} {
	return live.NewLiveServiceCreateLiveRoomResult()
}

func startLiveHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*live.LiveServiceStartLiveArgs)
	realResult := result.(*live.LiveServiceStartLiveResult)
	success, err := handler.(live.LiveService).StartLive(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newLiveServiceStartLiveArgs() interface{} {
	return live.NewLiveServiceStartLiveArgs()
}

func newLiveServiceStartLiveResult() interface{} {
	return live.NewLiveServiceStartLiveResult()
}

func stopLiveHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*live.LiveServiceStopLiveArgs)
	realResult := result.(*live.LiveServiceStopLiveResult)
	success, err := handler.(live.LiveService).StopLive(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newLiveServiceStopLiveArgs() interface{} {
	return live.NewLiveServiceStopLiveArgs()
}

func newLiveServiceStopLiveResult() interface{} {
	return live.NewLiveServiceStopLiveResult()
}

func getLiveRoomsHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*live.LiveServiceGetLiveRoomsArgs)
	realResult := result.(*live.LiveServiceGetLiveRoomsResult)
	success, err := handler.(live.LiveService).GetLiveRooms(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newLiveServiceGetLiveRoomsArgs() interface{} {
	return live.NewLiveServiceGetLiveRoomsArgs()
}

func newLiveServiceGetLiveRoomsResult() interface{} {
	return live.NewLiveServiceGetLiveRoomsResult()
}

func getLiveRoomDetailHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*live.LiveServiceGetLiveRoomDetailArgs)
	realResult := result.(*live.LiveServiceGetLiveRoomDetailResult)
	success, err := handler.(live.LiveService).GetLiveRoomDetail(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newLiveServiceGetLiveRoomDetailArgs() interface{} {
	return live.NewLiveServiceGetLiveRoomDetailArgs()
}

func newLiveServiceGetLiveRoomDetailResult() interface{} {
	return live.NewLiveServiceGetLiveRoomDetailResult()
}

func joinLiveRoomHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*live.LiveServiceJoinLiveRoomArgs)
	realResult := result.(*live.LiveServiceJoinLiveRoomResult)
	success, err := handler.(live.LiveService).JoinLiveRoom(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newLiveServiceJoinLiveRoomArgs() interface{} {
	return live.NewLiveServiceJoinLiveRoomArgs()
}

func newLiveServiceJoinLiveRoomResult() interface{} {
	return live.NewLiveServiceJoinLiveRoomResult()
}

func leaveLiveRoomHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*live.LiveServiceLeaveLiveRoomArgs)
	realResult := result.(*live.LiveServiceLeaveLiveRoomResult)
	success, err := handler.(live.LiveService).LeaveLiveRoom(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newLiveServiceLeaveLiveRoomArgs() interface{} {
	return live.NewLiveServiceLeaveLiveRoomArgs()
}

func newLiveServiceLeaveLiveRoomResult() interface{} {
	return live.NewLiveServiceLeaveLiveRoomResult()
}

func sendGiftHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*live.LiveServiceSendGiftArgs)
	realResult := result.(*live.LiveServiceSendGiftResult)
	success, err := handler.(live.LiveService).SendGift(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newLiveServiceSendGiftArgs() interface{} {
	return live.NewLiveServiceSendGiftArgs()
}

func newLiveServiceSendGiftResult() interface{} {
	return live.NewLiveServiceSendGiftResult()
}

func getGiftListHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	_ = arg.(*live.LiveServiceGetGiftListArgs)
	realResult := result.(*live.LiveServiceGetGiftListResult)
	success, err := handler.(live.LiveService).GetGiftList(ctx)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newLiveServiceGetGiftListArgs() interface{} {
	return live.NewLiveServiceGetGiftListArgs()
}

func newLiveServiceGetGiftListResult() interface{} {
	return live.NewLiveServiceGetGiftListResult()
}

func setRoomAdminHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*live.LiveServiceSetRoomAdminArgs)
	realResult := result.(*live.LiveServiceSetRoomAdminResult)
	success, err := handler.(live.LiveService).SetRoomAdmin(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newLiveServiceSetRoomAdminArgs() interface{} {
	return live.NewLiveServiceSetRoomAdminArgs()
}

func newLiveServiceSetRoomAdminResult() interface{} {
	return live.NewLiveServiceSetRoomAdminResult()
}

func recordLiveHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*live.LiveServiceRecordLiveArgs)
	realResult := result.(*live.LiveServiceRecordLiveResult)
	success, err := handler.(live.LiveService).RecordLive(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newLiveServiceRecordLiveArgs() interface{} {
	return live.NewLiveServiceRecordLiveArgs()
}

func newLiveServiceRecordLiveResult() interface{} {
	return live.NewLiveServiceRecordLiveResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) CreateLiveRoom(ctx context.Context, req *live.CreateLiveRoomReq) (r *live.CreateLiveRoomResp, err error) {
	var _args live.LiveServiceCreateLiveRoomArgs
	_args.Req = req
	var _result live.LiveServiceCreateLiveRoomResult
	if err = p.c.Call(ctx, "CreateLiveRoom", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) StartLive(ctx context.Context, req *live.StartLiveReq) (r *live.StartLiveResp, err error) {
	var _args live.LiveServiceStartLiveArgs
	_args.Req = req
	var _result live.LiveServiceStartLiveResult
	if err = p.c.Call(ctx, "StartLive", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) StopLive(ctx context.Context, req *live.StopLiveReq) (r *live.StopLiveResp, err error) {
	var _args live.LiveServiceStopLiveArgs
	_args.Req = req
	var _result live.LiveServiceStopLiveResult
	if err = p.c.Call(ctx, "StopLive", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetLiveRooms(ctx context.Context, req *live.GetLiveRoomsReq) (r *live.GetLiveRoomsResp, err error) {
	var _args live.LiveServiceGetLiveRoomsArgs
	_args.Req = req
	var _result live.LiveServiceGetLiveRoomsResult
	if err = p.c.Call(ctx, "GetLiveRooms", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetLiveRoomDetail(ctx context.Context, req *live.GetLiveRoomDetailReq) (r *live.GetLiveRoomDetailResp, err error) {
	var _args live.LiveServiceGetLiveRoomDetailArgs
	_args.Req = req
	var _result live.LiveServiceGetLiveRoomDetailResult
	if err = p.c.Call(ctx, "GetLiveRoomDetail", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) JoinLiveRoom(ctx context.Context, req *live.JoinLiveRoomReq) (r *live.JoinLiveRoomResp, err error) {
	var _args live.LiveServiceJoinLiveRoomArgs
	_args.Req = req
	var _result live.LiveServiceJoinLiveRoomResult
	if err = p.c.Call(ctx, "JoinLiveRoom", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) LeaveLiveRoom(ctx context.Context, req *live.LeaveLiveRoomReq) (r *live.LeaveLiveRoomResp, err error) {
	var _args live.LiveServiceLeaveLiveRoomArgs
	_args.Req = req
	var _result live.LiveServiceLeaveLiveRoomResult
	if err = p.c.Call(ctx, "LeaveLiveRoom", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) SendGift(ctx context.Context, req *live.SendGiftReq) (r *live.SendGiftResp, err error) {
	var _args live.LiveServiceSendGiftArgs
	_args.Req = req
	var _result live.LiveServiceSendGiftResult
	if err = p.c.Call(ctx, "SendGift", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetGiftList(ctx context.Context) (r *live.GetGiftListResp, err error) {
	var _args live.LiveServiceGetGiftListArgs
	var _result live.LiveServiceGetGiftListResult
	if err = p.c.Call(ctx, "GetGiftList", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) SetRoomAdmin(ctx context.Context, req *live.SetRoomAdminReq) (r *live.SetRoomAdminResp, err error) {
	var _args live.LiveServiceSetRoomAdminArgs
	_args.Req = req
	var _result live.LiveServiceSetRoomAdminResult
	if err = p.c.Call(ctx, "SetRoomAdmin", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) RecordLive(ctx context.Context, req *live.RecordLiveReq) (r *live.RecordLiveResp, err error) {
	var _args live.LiveServiceRecordLiveArgs
	_args.Req = req
	var _result live.LiveServiceRecordLiveResult
	if err = p.c.Call(ctx, "RecordLive", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
